using System.Text;
using DotBoxD.Plugins.Analyzer.Analysis.Lowering;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using TypeNames = DotBoxD.Plugins.Analyzer.Analysis.Lowering.DotBoxDGenerationNames.TypeNames;

namespace DotBoxD.Plugins.Analyzer.Analysis.MergeableIr;

internal static class MergeableIrStepSourceEmitter
{
    public static void Emit(SourceProductionContext context, MergeableIrStepModel model)
        => context.AddSource(model.HintName, SourceText.From(Build(model), Encoding.UTF8));

    private static string Build(MergeableIrStepModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        if (!string.IsNullOrWhiteSpace(model.Namespace))
        {
            builder.Append("namespace ").Append(model.Namespace).AppendLine(";");
            builder.AppendLine();
        }

        builder.Append("public static class ").Append(model.ClassName).AppendLine();
        builder.AppendLine("{");
        builder.Append("    private static readonly ").Append(TypeNames.GlobalSourceSpan).Append(" Span = new(")
            .Append(DotBoxDGenerationNames.GeneratedSpanLine)
            .Append(", ")
            .Append(DotBoxDGenerationNames.GeneratedSpanColumn)
            .AppendLine(");");
        builder.AppendLine();
        builder.Append("    public static ").Append(MergeableIrContractNames.GlobalLoweredPipelineStep).AppendLine(" Create()");
        builder.AppendLine("        => new(");
        builder.Append("            ").Append(MergeableIrContractNames.GlobalLoweredPipelineStepKind).Append('.').Append(model.Kind).AppendLine(",");
        builder.AppendLine($"            {LiteralReader.StringLiteral(model.InputType)},");
        builder.AppendLine($"            {LiteralReader.StringLiteral(model.OutputType)},");
        builder.Append("            new ").Append(TypeNames.GlobalParameter).Append("[] { ").Append(model.ParameterSource).AppendLine(" },");
        builder.Append("            ").Append(TypeNames.GlobalArray).Append(".Empty<").Append(TypeNames.GlobalStatement).AppendLine(">(),");
        builder.Append("            ").Append(model.ValueSource).AppendLine(",");
        builder.Append("            ").Append(StringArray(model.RequiredCapabilities)).AppendLine(",");
        builder.Append("            ").Append(StringArray(model.Effects)).AppendLine(");");
        builder.AppendLine();
        if (model.IRFuncType is not null)
        {
            builder.Append("    public static ").Append(model.IRFuncType).AppendLine(" CreateIRFunc()");
            builder.Append("        => ").Append(model.IRFuncType).AppendLine(".FromStep(Create());");
            builder.AppendLine();
        }

        MergeableIrExpressionHelperEmitter.Emit(builder);
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string StringArray(EquatableArray<string> values)
    {
        if (values.Count == 0)
        {
            return TypeNames.GlobalArray + ".Empty<string>()";
        }

        var builder = new StringBuilder();
        builder.Append("new string[] { ");
        for (var i = 0; i < values.Count; i++)
        {
            if (i > 0)
            {
                builder.Append(", ");
            }

            builder.Append(LiteralReader.StringLiteral(values[i]));
        }

        builder.Append(" }");
        return builder.ToString();
    }
}
