using System.Text;
using Microsoft.CodeAnalysis;
using TypeNames = DotBoxD.Plugins.Analyzer.Analysis.Lowering.DotBoxDGenerationNames.TypeNames;

namespace DotBoxD.Plugins.Analyzer.Analysis.HookChains;

internal static class InterceptsLocationAttributeEmitter
{
    public const string HintName = "DotBoxDInterceptsLocationAttribute.g.cs";

    private const string Source =
        "// <auto-generated/>\n" +
        "namespace System.Runtime.CompilerServices\n" +
        "{\n" +
        "    [" + TypeNames.GlobalAttributeUsage + "(" + TypeNames.GlobalAttributeTargets + ".Method, AllowMultiple = true)]\n" +
        "    file sealed class InterceptsLocationAttribute : " + TypeNames.GlobalAttribute + "\n" +
        "    {\n" +
        "        public InterceptsLocationAttribute(int version, string data) { _ = version; _ = data; }\n" +
        "    }\n" +
        "}\n";

    public static void Append(StringBuilder builder)
        => builder.Append(Source).AppendLine();

    public static void Emit(SourceProductionContext context)
        => context.AddSource(HintName, Source);
}
