// @ts-check
import { existsSync, readFileSync } from 'node:fs';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mermaid from 'astro-mermaid';

// The API reference sidebar is generated by scripts/postprocess-api.mjs after
// `dotnet docfx metadata docfx.json` (run from the repo root). When the generated
// content is absent (fresh clone, content-only work), the site builds without the
// API section instead of failing.
const apiSidebarPath = new URL('./src/generated/api-sidebar.json', import.meta.url);
const apiSidebar = existsSync(apiSidebarPath)
  ? JSON.parse(readFileSync(apiSidebarPath, 'utf8'))
  : [];

export default defineConfig({
  site: 'https://dotboxd.kamsker.at',
  integrations: [
    // Renders ```mermaid code fences client-side; must come before starlight().
    mermaid({ autoTheme: true }),
    starlight({
      title: 'DotBoxD',
      description:
        'Source-generated, contract-first .NET extension runtime: Services (RPC), sandboxed Kernels, and Pushdown from one C# contract.',
      logo: { src: './src/assets/logo.svg' },
      favicon: '/favicon.svg',
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/JKamsker/DotBoxD' },
        { icon: 'seti:c-sharp', label: 'NuGet', href: 'https://www.nuget.org/packages?q=DotBoxD' },
      ],
      editLink: {
        baseUrl: 'https://github.com/JKamsker/DotBoxD/edit/main/docs-site/',
      },
      lastUpdated: true,
      customCss: ['./src/styles/custom.css'],
      sidebar: [
        { label: 'Overview', slug: 'overview' },
        { label: 'Getting started', slug: 'getting-started' },
        {
          label: 'Tutorials',
          items: [
            { label: 'All tutorials', slug: 'tutorials' },
            { label: '1 · First service (RPC)', slug: 'tutorials/first-service' },
            { label: '2 · Event pipelines (RunLocal)', slug: 'tutorials/event-pipeline-runlocal' },
            { label: '3 · Pushdown server extension', slug: 'tutorials/pushdown-server-extension' },
          ],
        },
        {
          label: 'Concepts',
          items: [
            { label: 'Services (RPC)', slug: 'concepts/services' },
            { label: 'Kernels (sandbox)', slug: 'concepts/kernels' },
            { label: 'Pushdown', slug: 'concepts/pushdown' },
            { label: 'Event pipelines', slug: 'concepts/event-pipelines' },
            { label: 'Kernel runtime', slug: 'concepts/runtime' },
            { label: 'Channels & transports', slug: 'concepts/channels-transports' },
          ],
        },
        {
          label: 'Examples',
          items: [
            { label: 'Overview', slug: 'examples' },
            { label: 'GameServer walkthrough', slug: 'examples/gameserver-walkthrough' },
            { label: 'Coverage gaps', slug: 'examples/coverage-gaps' },
          ],
        },
        {
          label: 'Security',
          items: [
            { label: 'Sandbox caveats', slug: 'security/sandbox-caveats' },
            {
              label: 'Security policy',
              link: 'https://github.com/JKamsker/DotBoxD/blob/main/SECURITY.md',
            },
          ],
        },
        {
          label: 'Reference',
          items: [
            { label: 'Diagnostics (DBXS / DBXK)', slug: 'reference/diagnostics' },
            { label: 'Schemas', slug: 'reference/schemas' },
            { label: 'Glossary', slug: 'reference/glossary' },
            {
              label: 'Specifications',
              link: 'https://github.com/JKamsker/DotBoxD/tree/main/docs/Specs',
            },
          ],
        },
        {
          label: 'Channels (RPC) guide',
          collapsed: true,
          items: [
            { label: 'Quick start', slug: 'channels/quick-start' },
            { label: 'API reference', slug: 'channels/api-reference' },
            { label: 'Named-pipe transport', slug: 'channels/named-pipe-transport' },
            { label: 'WebSocket setup', slug: 'channels/websocket-setup' },
            { label: 'Unity integration', slug: 'channels/unity-integration' },
            { label: 'Performance', slug: 'channels/performance' },
          ],
        },
        {
          label: 'Contributing',
          items: [
            { label: 'Migration from standalone repos', slug: 'contributing/migration-from-standalone-repos' },
          ],
        },
        ...apiSidebar,
      ],
    }),
  ],
});
