using System.Text;
using DotBoxD.Plugins.Analyzer.Analysis;

namespace DotBoxD.Plugins.Analyzer.Analysis.PluginServer;

internal static class PluginServerFacadeEmitter
{
    public static GeneratedPluginPackage Emit(PluginServerFacadeModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System.Linq;");
        builder.AppendLine();
        if (!string.IsNullOrEmpty(model.Namespace))
        {
            builder.Append("namespace ").Append(model.Namespace).AppendLine(";");
            builder.AppendLine();
        }

        AppendFacade(builder, model);
        builder.AppendLine();
        PluginServerFacadeSurfaceEmitter.AppendServerInterface(builder, model);
        builder.AppendLine();
        PluginServerSetupEmitter.AppendBuilder(builder, model);
        PluginServerSetupEmitter.AppendSetupInterfaces(builder, model);
        return new GeneratedPluginPackage(HintName(model), builder.ToString());
    }

    private static void AppendFacade(StringBuilder builder, PluginServerFacadeModel model)
    {
        PluginServerXmlDocumentation.AppendSummary(
            builder,
            string.Empty,
            "Generated plugin-side client for the remote world domain. Call StartAsync before using runtime domain, hook, subscription, or server extension APIs.");
        builder.Append(model.Accessibility).Append(" partial class ").Append(model.ClassName)
            .Append(" : ").AppendLine(model.ServerInterfaceName);
        builder.AppendLine("{");
        builder.AppendLine("    private const string NotStartedMessage = \"Call StartAsync() before using the server.\";");
        builder.AppendLine("    private readonly global::System.Func<global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<global::DotBoxD.Services.Peer.RpcPeerSession>>? _connectionFactory;");
        builder.AppendLine("    private readonly global::System.Collections.Concurrent.ConcurrentDictionary<string, global::System.Lazy<global::System.Threading.Tasks.Task<string>>> _anonymousKernels = new();");
        builder.AppendLine("    private readonly global::System.Collections.Generic.Dictionary<global::System.Type, string> _serverExtensions = new();");
        builder.AppendLine("    private readonly global::System.Collections.Generic.List<RecordedInstall> _setupInstalls;");
        builder.Append("    private ").Append(model.ControlServiceType).AppendLine("? _control;");
        builder.Append("    private ").Append(model.WorldType).AppendLine("? _world;");
        builder.AppendLine("    private global::DotBoxD.Plugins.Runtime.RemoteHookRegistry? _hooks;");
        builder.AppendLine("    private global::DotBoxD.Plugins.Runtime.RemoteSubscriptionRegistry? _subscriptions;");
        builder.AppendLine("    private global::DotBoxD.Services.Peer.RpcPeerSession? _session;");
        foreach (var control in model.Controls)
        {
            builder.Append("    private ").Append(control.WrapperName).Append("? _")
                .Append(FieldName(control.Name)).AppendLine(";");
        }
        builder.AppendLine("    private bool _started;");
        builder.AppendLine("    private bool _setupReplayed;");
        builder.AppendLine("    private bool _configured;");
        builder.AppendLine("    private bool _disposed;");
        builder.AppendLine();
        PluginServerXmlDocumentation.AppendSummary(
            builder,
            "    ",
            "Creates a generated plugin server over an already connected control-plane service.");
        builder.Append("    public ").Append(model.ClassName).Append('(').Append(model.ControlServiceType)
            .Append(" control, ").Append(model.WorldType).AppendLine("? world = null)");
        builder.AppendLine("        : this(control, world, setup: null)");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine();
        PluginServerXmlDocumentation.AppendSummary(
            builder,
            "    ",
            "Creates a generated plugin server and records setup actions for replay when the server starts.");
        builder.Append("    public ").Append(model.ClassName).Append('(').Append(model.ControlServiceType)
            .Append(" control, ").Append(model.WorldType).Append("? world, global::System.Action<")
            .Append(model.SetupInterfaceName).AppendLine(">? setup)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(control);");
        builder.AppendLine("        _setupInstalls = RecordSetup(setup);");
        builder.AppendLine("        Initialize(control, world);");
        builder.AppendLine("        _started = true;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.Append("    internal ").Append(model.ClassName)
            .AppendLine("(global::System.Func<global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<global::DotBoxD.Services.Peer.RpcPeerSession>> connectionFactory)");
        builder.AppendLine("        : this(connectionFactory, setup: null)");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.Append("    internal ").Append(model.ClassName)
            .Append("(global::System.Func<global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<global::DotBoxD.Services.Peer.RpcPeerSession>> connectionFactory, global::System.Action<")
            .Append(model.SetupInterfaceName).AppendLine(">? setup)");
        builder.AppendLine("    {");
        builder.AppendLine("        _connectionFactory = connectionFactory ?? throw new global::System.ArgumentNullException(nameof(connectionFactory));");
        builder.AppendLine("        _setupInstalls = RecordSetup(setup);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    partial void OnConfigured();");
        PluginServerFacadeSurfaceEmitter.AppendProperties(builder, model);
        AppendLifecycle(builder, model);
        AppendWorldForwarders(builder, model);
        PluginServerFacadeSurfaceEmitter.AppendInstallSurface(builder, model);
        PluginServerSetupEmitter.AppendSetupMembers(builder, model);
        AppendLiveSettingsHandle(builder, model);
        foreach (var control in model.Controls)
        {
            PluginServerWrapperEmitter.AppendControlWrapper(builder, model, control);
        }
        builder.AppendLine("}");
    }

    private static void AppendLifecycle(StringBuilder builder, PluginServerFacadeModel model)
    {
        builder.AppendLine();
        PluginServerXmlDocumentation.AppendSummary(
            builder,
            "    ",
            "Connects the generated plugin server, initializes runtime domain, hook, subscription, and extension APIs, and replays setup registrations once.");
        builder.AppendLine("    public async global::System.Threading.Tasks.ValueTask StartAsync(global::System.Threading.CancellationToken cancellationToken = default)");
        builder.AppendLine("    {");
        builder.AppendLine("        ThrowIfDisposed();");
        builder.AppendLine("        if (!_started)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (_connectionFactory is null) { throw new global::System.InvalidOperationException(NotStartedMessage); }");
        builder.AppendLine("            _session = await _connectionFactory(cancellationToken).ConfigureAwait(false);");
        builder.AppendLine("            var control = _session.Get<" + model.ControlServiceType + ">();");
            builder.AppendLine("            var world = global::DotBoxD.Services.Generated.DotBoxDGeneratedExtensions.Get" + model.WorldExtensionSuffix + "(_session.Peer);");
        builder.AppendLine("            Initialize(control, world);");
        builder.AppendLine("            _started = true;");
        builder.AppendLine("        }");
        builder.AppendLine("        await ReplaySetupAsync(cancellationToken).ConfigureAwait(false);");
        builder.AppendLine("        if (!_configured)");
        builder.AppendLine("        {");
        builder.AppendLine("            OnConfigured();");
        builder.AppendLine("            _configured = true;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
        PluginServerXmlDocumentation.AppendSummary(
            builder,
            "    ",
            "Starts the generated plugin server and then waits until the remote host shuts down or the operation is cancelled.");
        builder.AppendLine("    public async global::System.Threading.Tasks.ValueTask RunAsync(global::System.Threading.CancellationToken cancellationToken = default)");
        builder.AppendLine("    {");
        builder.AppendLine("        await StartAsync(cancellationToken).ConfigureAwait(false);");
        builder.AppendLine("        await HoldUntilShutdownAsync(cancellationToken).ConfigureAwait(false);");
        builder.AppendLine("    }");
        builder.AppendLine();
        PluginServerXmlDocumentation.AppendSummary(
            builder,
            "    ",
            "Waits for the remote host to signal shutdown after the generated plugin server has started.");
        builder.AppendLine("    public global::System.Threading.Tasks.ValueTask HoldUntilShutdownAsync(global::System.Threading.CancellationToken cancellationToken = default)");
        builder.AppendLine("        => RequireControl().HoldUntilShutdownAsync(cancellationToken);");
        builder.AppendLine();
        PluginServerXmlDocumentation.AppendSummary(
            builder,
            "    ",
            "Synchronously releases the generated plugin server session and any owned connection.");
        builder.AppendLine("    public void Dispose() => DisposeAsync().AsTask().GetAwaiter().GetResult();");
        PluginServerXmlDocumentation.AppendSummary(
            builder,
            "    ",
            "Asynchronously releases the generated plugin server session and any owned connection.");
        builder.AppendLine("    public async global::System.Threading.Tasks.ValueTask DisposeAsync()");
        builder.AppendLine("    {");
        builder.AppendLine("        if (_disposed) { return; }");
        builder.AppendLine("        _disposed = true;");
        builder.AppendLine("        if (_session is not null) { await _session.DisposeAsync().ConfigureAwait(false); }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private void Initialize(" + model.ControlServiceType + " control, " + model.WorldType + "? world)");
        builder.AppendLine("    {");
        builder.AppendLine("        _control = control;");
        builder.AppendLine("        _world = world;");
        builder.AppendLine("        _hooks = new global::DotBoxD.Plugins.Runtime.RemoteHookRegistry(package => InstallPluginPackageAsync(package));");
        builder.AppendLine("        _subscriptions = new global::DotBoxD.Plugins.Runtime.RemoteSubscriptionRegistry(package => InstallSubscriptionPackageAsync(package));");
        foreach (var control in model.Controls)
        {
            builder.Append("        _").Append(FieldName(control.Name)).Append(" = world is null ? null : new ")
                .Append(control.WrapperName).Append("(this, world.").Append(control.Name).AppendLine(");");
        }
        builder.AppendLine("    }");
        builder.AppendLine("    private " + model.ControlServiceType + " RequireControl() => _started && _control is not null ? _control : throw new global::System.InvalidOperationException(NotStartedMessage);");
        builder.AppendLine("    private " + model.WorldType + " RequireWorld() => _started && _world is not null ? _world : throw new global::System.InvalidOperationException(NotStartedMessage);");
        builder.AppendLine("    private void ThrowIfDisposed() => global::System.ObjectDisposedException.ThrowIf(_disposed, this);");
    }

    private static void AppendWorldForwarders(StringBuilder builder, PluginServerFacadeModel model)
    {
        foreach (var method in model.WorldMethods)
        {
            PluginServerXmlDocumentation.Append(builder, "    ", method.Documentation);
            builder.Append("    public ").Append(method.ReturnType).Append(' ').Append(method.Name)
                .Append('(').Append(ParameterList(method)).Append(") => RequireWorld().")
                .Append(method.Name).Append('(').Append(ArgumentList(method)).AppendLine(");");
        }

        if (model.WorldMethods.Count > 0)
        {
            builder.AppendLine();
        }
    }

    private static void AppendLiveSettingsHandle(StringBuilder builder, PluginServerFacadeModel model)
    {
        builder.AppendLine("    private sealed class LiveSettingsHandle<TKernel> : global::DotBoxD.Abstractions.ILiveSettingsHandle<TKernel> where TKernel : class, new()");
        builder.AppendLine("    {");
        builder.AppendLine("        private readonly " + model.ClassName + " _owner;");
        builder.AppendLine("        private readonly string _pluginId;");
        builder.AppendLine("        private readonly global::System.Collections.Generic.List<" + model.LiveSettingUpdateType + "> _updates = new();");
        builder.AppendLine("        public LiveSettingsHandle(" + model.ClassName + " owner, string pluginId) { _owner = owner; _pluginId = pluginId; }");
        builder.AppendLine("        public global::DotBoxD.Abstractions.ILiveSettingsHandle<TKernel> Set<TValue>(global::System.Linq.Expressions.Expression<global::System.Func<TKernel, TValue>> member, TValue value)");
        builder.AppendLine("        {");
        builder.AppendLine("            var body = member.Body is global::System.Linq.Expressions.UnaryExpression unary ? unary.Operand : member.Body;");
        builder.AppendLine("            if (body is not global::System.Linq.Expressions.MemberExpression { Member: global::System.Reflection.PropertyInfo property })");
        builder.AppendLine("            {");
        builder.AppendLine("                throw new global::System.ArgumentException(\"Live setting expression must select a property.\", nameof(member));");
        builder.AppendLine("            }");
        builder.AppendLine("            if (property.GetCustomAttributes(typeof(global::DotBoxD.Abstractions.LiveSettingAttribute), inherit: true).Length == 0)");
        builder.AppendLine("            {");
        builder.AppendLine("                throw new global::System.ArgumentException($\"Property '{property.Name}' is not a live setting.\", nameof(member));");
        builder.AppendLine("            }");
        builder.AppendLine("            _updates.Add(new " + model.LiveSettingUpdateType + "(property.Name, global::System.Convert.ToString(value, global::System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty));");
        builder.AppendLine("            return this;");
        builder.AppendLine("        }");
        builder.AppendLine("        public global::System.Threading.Tasks.ValueTask ApplyAsync(bool atomic = false)");
        builder.AppendLine("            => _owner.RequireControl().UpdateSettingsAsync(_pluginId, _updates.ToArray(), atomic);");
        builder.AppendLine("        public global::System.Threading.Tasks.ValueTask SetValuesAsync(global::System.Action<TKernel> set, bool atomic = false)");
        builder.AppendLine("        {");
            builder.AppendLine("            var draft = new TKernel();");
        builder.AppendLine("            set(draft);");
        builder.AppendLine("            var updates = typeof(TKernel).GetProperties(global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Instance)");
        builder.AppendLine("                .Where(p => p.GetMethod is not null && p.GetCustomAttributes(typeof(global::DotBoxD.Abstractions.LiveSettingAttribute), inherit: true).Length != 0)");
        builder.AppendLine("                .Select(p => new " + model.LiveSettingUpdateType + "(p.Name, global::System.Convert.ToString(p.GetValue(draft), global::System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty))");
        builder.AppendLine("                .ToArray();");
        builder.AppendLine("            return _owner.RequireControl().UpdateSettingsAsync(_pluginId, updates, atomic);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static string ParameterList(PluginServerForwardedMethod method)
        => string.Join(", ", method.Parameters.Select(p => p.Type + " @" + p.Name));

    private static string ArgumentList(PluginServerForwardedMethod method)
        => string.Join(", ", method.Parameters.Select(p => "@" + p.Name));

    private static string FieldName(string propertyName)
        => char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);

    private static string HintName(PluginServerFacadeModel model)
        => (string.IsNullOrWhiteSpace(model.Namespace) ? model.ClassName : model.Namespace + "." + model.ClassName) +
           ".PluginServer.g.cs";
}
