using System.Text;
using DotBoxD.Plugins.Analyzer.Analysis.Lowering.Expressions;

namespace DotBoxD.Plugins.Analyzer.Analysis.PluginServer;

internal static partial class PluginServerFacadeEmitter
{
    public static GeneratedPluginPackage Emit(PluginServerFacadeModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System.Linq;");
        builder.AppendLine();
        AppendKernelMethodDescriptors(builder, model);

        AppendNamespace(builder, model.Namespace, () =>
        {
            AppendFacade(builder, model);
            builder.AppendLine();
            PluginServerFacadeSurfaceEmitter.AppendServerInterface(builder, model);
            builder.AppendLine();
            if (string.Equals(model.ContextNamespace, model.Namespace, StringComparison.Ordinal))
            {
                PluginServerContextSurfaceEmitter.AppendContext(builder, model);
                builder.AppendLine();
            }

            PluginServerContextSurfaceEmitter.AppendRegistries(builder, model);
            builder.AppendLine();
            PluginServerSetupEmitter.AppendBuilder(builder, model);
            PluginServerSetupEmitter.AppendSetupInterfaces(builder, model);
        });
        if (!string.Equals(model.ContextNamespace, model.Namespace, StringComparison.Ordinal))
        {
            builder.AppendLine();
            AppendNamespace(builder, model.ContextNamespace, () =>
                PluginServerContextSurfaceEmitter.AppendContext(builder, model));
        }

        return new GeneratedPluginPackage(HintName(model), builder.ToString(), model.Namespace, model.ClassName);
    }

    private static void AppendNamespace(StringBuilder builder, string ns, Action append)
    {
        if (string.IsNullOrEmpty(ns))
        {
            append();
            return;
        }

        builder.Append("namespace ").Append(ns).AppendLine();
        builder.AppendLine("{");
        append();
        builder.AppendLine("}");
    }

    private static void AppendKernelMethodDescriptors(StringBuilder builder, PluginServerFacadeModel model)
    {
        foreach (var descriptor in model.KernelMethodDescriptors)
        {
            builder.Append("[assembly: global::DotBoxD.Abstractions.GeneratedKernelMethodDescriptorAttribute(")
                .Append(KernelMethodDescriptorPayload.CurrentVersion.ToString(System.Globalization.CultureInfo.InvariantCulture))
                .Append(", typeof(").Append(descriptor.ContextType).Append("), ")
                .Append(LiteralReader.StringLiteral(descriptor.MethodMetadataName)).Append(", ")
                .Append(LiteralReader.StringLiteral(descriptor.NormalizedSignature)).Append(", ")
                .Append(LiteralReader.StringLiteral(descriptor.DescriptorHash)).Append(", ")
                .Append(LiteralReader.StringLiteral(descriptor.DescriptorPayload)).AppendLine(")]");
        }

        if (model.KernelMethodDescriptors.Count > 0)
        {
            builder.AppendLine();
        }
    }

    private static void AppendFacade(StringBuilder builder, PluginServerFacadeModel model)
    {
        PluginServerXmlDocumentation.AppendSummary(
            builder,
            string.Empty,
            "Generated plugin-side client for the remote world domain. Call StartAsync before using runtime domain, hook, subscription, or server extension APIs.");
        builder.Append(model.Accessibility).Append(" partial class ")
            .Append(PluginServerIdentifier.Escape(model.ClassName))
            .Append(" : ").AppendLine(model.ServerInterfaceName);
        builder.AppendLine("{");
        builder.AppendLine("    private const string NotStartedMessage = \"Call StartAsync() before using the server.\";");
        builder.AppendLine("    private readonly global::System.Func<global::System.Action<global::DotBoxD.Services.Peer.RpcPeer>?, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<global::DotBoxD.Services.Peer.RpcPeerSession>>? _connectionFactory;");
        builder.AppendLine("    private readonly global::System.Collections.Concurrent.ConcurrentDictionary<string, global::System.Lazy<global::System.Threading.Tasks.Task<string>>> _anonymousKernels = new();");
        builder.AppendLine("    private readonly global::System.Collections.Generic.HashSet<string> _installedPluginIds = new(global::System.StringComparer.Ordinal);");
        builder.AppendLine("    private readonly global::System.Collections.Generic.Dictionary<global::System.Type, string> _serverExtensions = new();");
        builder.AppendLine("    private readonly global::System.Collections.Generic.List<RecordedInstall> _setupInstalls;");
        builder.Append("    private ").Append(model.ControlServiceType).AppendLine("? _control;");
        builder.Append("    private ").Append(model.WorldType).AppendLine("? _world;");
        builder.Append("    private ").Append(model.HookRegistryName).AppendLine("? _hooks;");
        builder.Append("    private ").Append(model.SubscriptionRegistryName).AppendLine("? _subscriptions;");
        if (model.EventCallbackType is not null)
        {
            // Owns the native RunLocal terminals; the server pushes filtered+projected values back to it via the
            // reverse event callback provided on the peer in StartAsync.
            builder.AppendLine("    private readonly global::DotBoxD.Plugins.Runtime.Hooks.RemoteLocalHandlerRegistry _localHandlers = new();");
        }
        builder.AppendLine("    private global::DotBoxD.Services.Peer.RpcPeerSession? _session;");
        foreach (var control in model.Controls)
        {
            builder.Append("    private ").Append(control.WrapperName).Append("? ")
                .Append(control.FieldName).AppendLine(";");
        }
        builder.AppendLine("    private readonly global::System.Threading.SemaphoreSlim _startGate = new(1, 1);");
        builder.AppendLine("    private bool _started;");
        builder.AppendLine("    private bool _setupReplayed;");
        builder.AppendLine("    private int _setupReplayIndex;");
        builder.AppendLine("    private bool _configured;");
        builder.AppendLine("    private bool _disposed;");
        builder.AppendLine();
        PluginServerXmlDocumentation.AppendSummary(
            builder,
            "    ",
            "Creates a generated plugin server over an already connected control-plane service.");
        builder.Append("    public ").Append(PluginServerIdentifier.Escape(model.ClassName)).Append('(')
            .Append(model.ControlServiceType)
            .Append(" control, ").Append(model.WorldType).AppendLine("? world = null)");
        builder.AppendLine("        : this(control, world, setup: null)");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine();
        PluginServerXmlDocumentation.AppendSummary(
            builder,
            "    ",
            "Creates a generated plugin server and records setup actions for replay when the server starts.");
        builder.Append("    public ").Append(PluginServerIdentifier.Escape(model.ClassName)).Append('(')
            .Append(model.ControlServiceType)
            .Append(" control, ").Append(model.WorldType).Append("? world, global::System.Action<")
            .Append(model.SetupInterfaceName).AppendLine(">? setup)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(control);");
        builder.AppendLine("        _setupInstalls = RecordSetup(setup);");
        builder.AppendLine("        Initialize(control, world);");
        builder.AppendLine("        _started = true;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.Append("    internal ").Append(PluginServerIdentifier.Escape(model.ClassName))
            .AppendLine("(global::System.Func<global::System.Action<global::DotBoxD.Services.Peer.RpcPeer>?, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<global::DotBoxD.Services.Peer.RpcPeerSession>> connectionFactory)");
        builder.AppendLine("        : this(connectionFactory, setup: null)");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.Append("    internal ").Append(PluginServerIdentifier.Escape(model.ClassName))
            .Append("(global::System.Func<global::System.Action<global::DotBoxD.Services.Peer.RpcPeer>?, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<global::DotBoxD.Services.Peer.RpcPeerSession>> connectionFactory, global::System.Action<")
            .Append(model.SetupInterfaceName).AppendLine(">? setup)");
        builder.AppendLine("    {");
        builder.AppendLine("        _connectionFactory = connectionFactory ?? throw new global::System.ArgumentNullException(nameof(connectionFactory));");
        builder.AppendLine("        _setupInstalls = RecordSetup(setup);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    partial void OnConfigured();");
        PluginServerFacadeSurfaceEmitter.AppendProperties(builder, model);
        AppendLifecycle(builder, model);
        AppendWorldForwarders(builder, model);
        PluginServerFacadeSurfaceEmitter.AppendInstallSurface(builder, model);
        PluginServerSetupEmitter.AppendSetupMembers(builder, model);
        AppendLiveSettingsHandle(builder, model);
        PluginServerRemoteLocalEventSinkEmitter.Append(builder, model);
        foreach (var control in model.Controls)
        {
            PluginServerWrapperEmitter.AppendControlWrapper(builder, model, control);
        }
        builder.AppendLine("}");
    }

    private static void AppendWorldForwarders(StringBuilder builder, PluginServerFacadeModel model)
    {
        foreach (var property in model.WorldProperties)
        {
            PluginServerXmlDocumentation.Append(builder, "    ", property.Documentation);
            PluginServerFlowAttributeSource.Append(builder, "    ", property.Attributes);
            builder.Append("    public ").Append(property.Type).Append(' ')
                .Append(PluginServerIdentifier.Escape(property.Name))
                .Append(" => RequireWorld().")
                .Append(PluginServerIdentifier.Escape(property.Name)).AppendLine(";");
        }

        foreach (var method in model.WorldMethods)
        {
            PluginServerXmlDocumentation.Append(builder, "    ", method.Documentation);
            PluginServerFlowAttributeSource.Append(builder, "    ", method.ReturnAttributes);
            builder.Append("    public ").Append(method.ReturnType).Append(' ')
                .Append(PluginServerIdentifier.Escape(method.Name))
                .Append('(').Append(ParameterList(method)).Append(") => ((")
                .Append(method.ReceiverType).Append(")RequireWorld()).")
                .Append(PluginServerIdentifier.Escape(method.Name)).Append('(')
                .Append(ArgumentList(method)).AppendLine(");");
        }

        if (model.WorldProperties.Count > 0 || model.WorldMethods.Count > 0)
        {
            builder.AppendLine();
        }
    }

    private static string ParameterList(PluginServerForwardedMethod method)
        => string.Join(", ", method.Parameters.Select(p => p.Type + " @" + p.Name + p.DefaultClause));

    private static string ArgumentList(PluginServerForwardedMethod method)
        => string.Join(", ", method.Parameters.Select(p => "@" + p.Name));

    private static string HintName(PluginServerFacadeModel model)
        => (string.IsNullOrWhiteSpace(model.Namespace) ? model.ClassName : model.Namespace + "." + model.ClassName) +
           ".PluginServer.g.cs";
}
