namespace DotBoxD.Plugins.Analyzer.Analysis.PluginServer;

using System.Text;

internal static partial class PluginServerFacadeEmitter
{
    private static void AppendLiveSettingsHandle(StringBuilder builder, PluginServerFacadeModel model)
    {
        builder.AppendLine("    private sealed class LiveSettingsHandle<TKernel> : global::DotBoxD.Abstractions.ILiveSettingsHandle<TKernel> where TKernel : class, new()");
        builder.AppendLine("    {");
        builder.AppendLine("        private readonly " + PluginServerIdentifier.Escape(model.ClassName) + " _owner;");
        builder.AppendLine("        private readonly string _pluginId;");
        builder.AppendLine("        private readonly global::System.Collections.Generic.List<" + model.LiveSettingUpdateType + "> _updates = new();");
        builder.AppendLine("        private readonly global::System.Collections.Generic.List<(string Name, object? Value)> _pendingValues = new();");
        builder.AppendLine("        public LiveSettingsHandle(" + PluginServerIdentifier.Escape(model.ClassName) + " owner, string pluginId) { _owner = owner; _pluginId = pluginId; }");
        builder.AppendLine("        public global::DotBoxD.Abstractions.ILiveSettingsHandle<TKernel> Set<TValue>(global::System.Linq.Expressions.Expression<global::System.Func<TKernel, TValue>> member, TValue value)");
        builder.AppendLine("        {");
        builder.AppendLine("            _owner.ThrowIfDisposed();");
        builder.AppendLine("            if (member is null) throw new global::System.ArgumentNullException(nameof(member));");
        builder.AppendLine("            var body = member.Body is global::System.Linq.Expressions.UnaryExpression unary ? unary.Operand : member.Body;");
        builder.AppendLine("            if (body is not global::System.Linq.Expressions.MemberExpression { Member: global::System.Reflection.PropertyInfo property })");
        builder.AppendLine("            {");
        builder.AppendLine("                throw new global::System.ArgumentException(\"Live setting expression must select a property.\", nameof(member));");
        builder.AppendLine("            }");
        builder.AppendLine("            if (!IsKernelProperty(property))");
        builder.AppendLine("            {");
        builder.AppendLine("                throw new global::System.ArgumentException($\"Live setting expression must select a public instance property on '{typeof(TKernel).FullName}'.\", nameof(member));");
        builder.AppendLine("            }");
        builder.AppendLine("            if (!IsLiveSetting(property))");
        builder.AppendLine("            {");
        builder.AppendLine("                throw new global::System.ArgumentException($\"Property '{property.Name}' is not a live setting.\", nameof(member));");
        builder.AppendLine("            }");
        builder.AppendLine("            if (value is null && IsRequired(property) && CanObserveMissingRequiredValue(property))");
        builder.AppendLine("            {");
        builder.AppendLine("                throw new global::System.ArgumentException($\"Required live setting '{property.Name}' must be assigned a non-null value.\", nameof(value));");
        builder.AppendLine("            }");
        builder.AppendLine("            _updates.Add(new " + model.LiveSettingUpdateType + "(property.Name, global::System.Convert.ToString(value, global::System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty));");
        builder.AppendLine("            _pendingValues.Add((property.Name, value));");
        builder.AppendLine("            return this;");
        builder.AppendLine("        }");
        builder.AppendLine("        public async global::System.Threading.Tasks.ValueTask ApplyAsync(bool atomic = false)");
        builder.AppendLine("        {");
        builder.AppendLine("            _owner.ThrowIfDisposed();");
        builder.AppendLine("            _owner.RequireInstalledKernel<TKernel>(_pluginId);");
        builder.AppendLine("            await _owner.RequireControl().UpdateSettingsAsync(_pluginId, _updates.ToArray(), atomic, default).ConfigureAwait(false);");
        builder.AppendLine("            foreach (var value in _pendingValues)");
        builder.AppendLine("            {");
        builder.AppendLine("                _owner.RecordLiveSettingValue(_pluginId, value.Name, value.Value);");
        builder.AppendLine("            }");
        builder.AppendLine("            _updates.Clear();");
        builder.AppendLine("            _pendingValues.Clear();");
        builder.AppendLine("        }");
        builder.AppendLine("        public async global::System.Threading.Tasks.ValueTask SetValuesAsync(global::System.Action<TKernel> set, bool atomic = false)");
        builder.AppendLine("        {");
        builder.AppendLine("            _owner.ThrowIfDisposed();");
        builder.AppendLine("            if (set is null) throw new global::System.ArgumentNullException(nameof(set));");
        builder.AppendLine("            var currentValues = _owner.SnapshotLiveSettingValues(_pluginId);");
        builder.AppendLine("            var draft = new TKernel();");
        builder.AppendLine("            var properties = typeof(TKernel).GetProperties(global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Instance)");
        builder.AppendLine("                .Where(static p => p.GetMethod is not null && p.GetIndexParameters().Length == 0)");
        builder.AppendLine("                .ToArray();");
        builder.AppendLine("            foreach (var property in properties.Where(static p => IsLiveSetting(p)))");
        builder.AppendLine("            {");
        builder.AppendLine("                if (currentValues.TryGetValue(property.Name, out var currentValue))");
        builder.AppendLine("                {");
        builder.AppendLine("                    property.SetValue(draft, CoerceLiveSettingValue(property, currentValue));");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            var nonLiveValues = properties");
        builder.AppendLine("                .Where(static p => p.SetMethod is not null && !IsLiveSetting(p))");
        builder.AppendLine("                .Select(p => new { Property = p, Value = p.GetValue(draft) })");
        builder.AppendLine("                .ToArray();");
        builder.AppendLine("            var requiredLiveValues = properties");
        builder.AppendLine("                .Where(static p => IsLiveSetting(p) && IsRequired(p) && CanObserveMissingRequiredValue(p))");
        builder.AppendLine("                .Select(static p => new { Property = p })");
        builder.AppendLine("                .ToArray();");
        builder.AppendLine("            set(draft);");
        builder.AppendLine("            foreach (var entry in nonLiveValues)");
        builder.AppendLine("            {");
        builder.AppendLine("                if (!global::System.Object.Equals(entry.Value, entry.Property.GetValue(draft)))");
        builder.AppendLine("                {");
        builder.AppendLine("                    throw new global::System.InvalidOperationException($\"Property '{entry.Property.Name}' is not a live setting and cannot be written by SetValuesAsync.\");");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            foreach (var entry in requiredLiveValues)");
        builder.AppendLine("            {");
        builder.AppendLine("                if (entry.Property.GetValue(draft) is null)");
        builder.AppendLine("                {");
        builder.AppendLine("                    throw new global::System.InvalidOperationException($\"Required live setting '{entry.Property.Name}' must be assigned a non-null value by SetValuesAsync.\");");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("            var changedValues = properties");
        builder.AppendLine("                .Where(static p => IsLiveSetting(p))");
        builder.AppendLine("                .Select(p => new { Property = p, Value = p.GetValue(draft) })");
        builder.AppendLine("                .Where(entry => !currentValues.TryGetValue(entry.Property.Name, out var currentValue) || !global::System.Object.Equals(CoerceLiveSettingValue(entry.Property, currentValue), entry.Value))");
        builder.AppendLine("                .ToArray();");
        builder.AppendLine("            var updates = changedValues");
        builder.AppendLine("                .Select(entry => new " + model.LiveSettingUpdateType + "(entry.Property.Name, global::System.Convert.ToString(entry.Value, global::System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty))");
        builder.AppendLine("                .ToArray();");
        builder.AppendLine("            _owner.RequireInstalledKernel<TKernel>(_pluginId);");
        builder.AppendLine("            await _owner.RequireControl().UpdateSettingsAsync(_pluginId, updates, atomic, default).ConfigureAwait(false);");
        builder.AppendLine("            foreach (var entry in changedValues)");
        builder.AppendLine("            {");
        builder.AppendLine("                _owner.RecordLiveSettingValue(_pluginId, entry.Property.Name, entry.Value);");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("        private static bool IsKernelProperty(global::System.Reflection.PropertyInfo property)");
        builder.AppendLine("            => property.DeclaringType is { } declaringType &&");
        builder.AppendLine("                declaringType.IsAssignableFrom(typeof(TKernel)) &&");
        builder.AppendLine("                property.GetMethod is { IsPublic: true, IsStatic: false } &&");
        builder.AppendLine("                property.SetMethod is { IsPublic: true, IsStatic: false } &&");
        builder.AppendLine("                property.GetIndexParameters().Length == 0;");
        builder.AppendLine("        private static bool IsLiveSetting(global::System.Reflection.PropertyInfo property)");
        builder.AppendLine("            => property.GetCustomAttributes(typeof(global::DotBoxD.Abstractions.LiveSettingAttribute), inherit: true).Length != 0;");
        builder.AppendLine("        private static bool IsRequired(global::System.Reflection.PropertyInfo property)");
        builder.AppendLine("            => property.GetCustomAttributes(inherit: true).Any(static attribute => string.Equals(attribute.GetType().FullName, \"System.Runtime.CompilerServices.RequiredMemberAttribute\", global::System.StringComparison.Ordinal));");
        builder.AppendLine("        private static bool CanObserveMissingRequiredValue(global::System.Reflection.PropertyInfo property)");
        builder.AppendLine("            => !property.PropertyType.IsValueType || global::System.Nullable.GetUnderlyingType(property.PropertyType) is not null;");
        builder.AppendLine("        private static object? CoerceLiveSettingValue(global::System.Reflection.PropertyInfo property, object? value)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (value is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                return null;");
        builder.AppendLine("            }");
        builder.AppendLine("            var targetType = global::System.Nullable.GetUnderlyingType(property.PropertyType) ?? property.PropertyType;");
        builder.AppendLine("            return targetType.IsInstanceOfType(value)");
        builder.AppendLine("                ? value");
        builder.AppendLine("                : global::System.Convert.ChangeType(value, targetType, global::System.Globalization.CultureInfo.InvariantCulture);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }
}
