using System.Text;
using DotBoxD.Plugins.Analyzer.Analysis.Lowering;
using DotBoxD.Plugins.Analyzer.Analysis.Lowering.Expressions;
using TypeNames = DotBoxD.Plugins.Analyzer.Analysis.Lowering.DotBoxDGenerationNames.TypeNames;

namespace DotBoxD.Plugins.Analyzer.Analysis;

internal static class DotBoxDPackageSourceEmitter
{
    public static GeneratedPluginPackage Emit(PluginKernelModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        if (!string.IsNullOrWhiteSpace(model.Namespace)) {
            builder.Append("namespace ").Append(model.Namespace).AppendLine(";");
            builder.AppendLine();
        }

        builder.Append("public static class ").Append(model.PackageName).AppendLine();
        builder.AppendLine("{");
        EmitBody(builder, model);
        builder.AppendLine("}");
        return new GeneratedPluginPackage(
            HintName(model),
            builder.ToString(),
            model.Namespace,
            model.PackageName);
    }

    private static string HintName(PluginKernelModel model)
        => string.IsNullOrWhiteSpace(model.Namespace)
            ? model.PackageName + ".g.cs"
            : HintNamePart(model.Namespace) + "." + model.PackageName + ".g.cs";

    private static string HintNamePart(string value)
        => value.Replace(DotBoxDGenerationNames.CSharpIdentifiers.EscapePrefix, string.Empty);

    private static void EmitBody(StringBuilder builder, PluginKernelModel model)
    {
        builder.Append("    private static readonly ").Append(TypeNames.GlobalSourceSpan).Append(" Span = new(")
            .Append(DotBoxDGenerationNames.GeneratedSpanLine)
            .Append(", ")
            .Append(DotBoxDGenerationNames.GeneratedSpanColumn)
            .AppendLine(");");
        builder.AppendLine();
        builder.Append("    public static ").Append(TypeNames.GlobalPluginPackage).AppendLine(" Create()");
        builder.AppendLine("    {");
        EmitSettings(builder, model);
        builder.Append("        var manifest = new ").Append(TypeNames.GlobalPluginManifest).AppendLine("(");
        builder.AppendLine($"            {LiteralReader.StringLiteral(model.PluginId)},");
        builder.AppendLine(
            $"            {LiteralReader.StringLiteral(DotBoxDGenerationNames.Contracts.EventKernel(model.EventName))},");
        builder.AppendLine($"            {TypeNames.GlobalExecutionMode}.Auto,");
        EmitEffects(builder, model.ManifestEffects);
        builder.AppendLine("            settings,");
        builder.AppendLine($"            [new {TypeNames.GlobalHookSubscriptionManifest}({LiteralReader.StringLiteral(model.EventName)}, {LiteralReader.StringLiteral(model.KernelName)})])");
        EmitRequiredCapabilities(builder, model.RequiredCapabilities);
        builder.Append("        return ").Append(TypeNames.GlobalPluginPackage).AppendLine(".Create(manifest, CreateModule(settings));");
        builder.AppendLine("    }");
        builder.AppendLine();
        EmitModule(builder, model);
        EmitFunctions(builder, model);
        EmitHelpers(builder, model);
    }

    private static void EmitSettings(StringBuilder builder, PluginKernelModel model)
    {
        if (model.LiveSettings.Count == 0) {
            builder.Append("        var settings = ").Append(EmptyArray(TypeNames.GlobalLiveSettingDefinition)).AppendLine(";");
            return;
        }

        builder.Append("        var settings = new ").Append(ArrayOf(TypeNames.GlobalLiveSettingDefinition)).AppendLine(" {");
        foreach (var setting in model.LiveSettings) {
            builder.Append("            new ").Append(TypeNames.GlobalLiveSettingDefinition).Append('(');
            builder.Append(LiteralReader.StringLiteral(setting.Name)).Append(", ");
            builder.Append(LiteralReader.StringLiteral(setting.Type)).Append(", ");
            builder.Append(setting.DefaultValue);
            if (setting.Min is not null || setting.Max is not null) {
                builder.Append(", ")
                    .Append(setting.Min ?? DotBoxDGenerationNames.CSharpLiterals.Null)
                    .Append(", ")
                    .Append(setting.Max ?? DotBoxDGenerationNames.CSharpLiterals.Null);
            }

            builder.AppendLine("),");
        }

        builder.AppendLine("        };");
    }

    private static void EmitEffects(StringBuilder builder, EquatableArray<string> effects)
    {
        builder.Append("            [");
        for (var i = 0; i < effects.Count; i++) {
            if (i > 0) {
                builder.Append(", ");
            }

            builder.Append(LiteralReader.StringLiteral(effects[i]));
        }

        builder.AppendLine("],");
    }

    private static void EmitRequiredCapabilities(StringBuilder builder, EquatableArray<string> capabilities)
    {
        builder.AppendLine("        {");
        builder.Append("            RequiredCapabilities = [");
        for (var i = 0; i < capabilities.Count; i++) {
            if (i > 0) {
                builder.Append(", ");
            }

            builder.Append(LiteralReader.StringLiteral(capabilities[i]));
        }

        builder.AppendLine("],");
        builder.AppendLine("        };");
    }

    private static void EmitModule(StringBuilder builder, PluginKernelModel model)
    {
        builder.Append("    private static ").Append(TypeNames.GlobalSandboxModule).Append(" CreateModule(")
            .Append(ReadOnlyListOf(TypeNames.GlobalLiveSettingDefinition)).AppendLine(" settings)");
        builder.AppendLine("    {");
        builder.AppendLine("        var parameters = Parameters(settings);");
        builder.Append("        return new ").Append(TypeNames.GlobalSandboxModule).AppendLine("(");
        builder.AppendLine($"            {LiteralReader.StringLiteral(model.PluginId)},");
        builder.AppendLine($"            {TypeNames.GlobalSemVersion}.One,");
        builder.AppendLine($"            {TypeNames.GlobalSemVersion}.One,");
        DotBoxDCapabilityRequestSourceEmitter.Emit(builder, model.RequiredCapabilities);
        builder.Append("            [")
            .Append(DotBoxDGenerationNames.Entrypoints.ShouldHandle)
            .Append("(parameters), ")
            .Append(DotBoxDGenerationNames.Entrypoints.Handle)
            .AppendLine("(parameters)],");
        builder.AppendLine($"            new {Generic(TypeNames.GlobalDictionary, "string", "string")} {{ [{LiteralReader.StringLiteral(DotBoxDGenerationNames.ModuleMetadata.PluginId)}] = {LiteralReader.StringLiteral(model.PluginId)}, [{LiteralReader.StringLiteral(DotBoxDGenerationNames.ModuleMetadata.Kernel)}] = {LiteralReader.StringLiteral(model.KernelName)} }});");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitFunctions(StringBuilder builder, PluginKernelModel model)
    {
        builder.Append("    private static ").Append(TypeNames.GlobalSandboxFunction).Append(' ')
            .Append(DotBoxDGenerationNames.Entrypoints.ShouldHandle)
            .Append('(').Append(ReadOnlyListOf(TypeNames.GlobalParameter)).AppendLine(" parameters)");
        builder.AppendLine("        => new(");
        builder.AppendLine($"            {LiteralReader.StringLiteral(DotBoxDGenerationNames.Entrypoints.ShouldHandle)}, true, parameters, {TypeNames.GlobalSandboxType}.Bool,");
        builder.AppendLine($"            {model.ShouldHandle.Source});");
        builder.AppendLine();
        builder.Append("    private static ").Append(TypeNames.GlobalSandboxFunction).Append(' ')
            .Append(DotBoxDGenerationNames.Entrypoints.Handle)
            .Append('(').Append(ReadOnlyListOf(TypeNames.GlobalParameter)).AppendLine(" parameters)");
        builder.AppendLine("        => new(");
        builder.AppendLine($"            {LiteralReader.StringLiteral(DotBoxDGenerationNames.Entrypoints.Handle)}, true, parameters, {TypeNames.GlobalSandboxType}.Unit,");
        builder.AppendLine($"            {HandleBody(model.Handle).Source});");
        builder.AppendLine();
    }

    private static void EmitHelpers(StringBuilder builder, PluginKernelModel model)
    {
        builder.Append("    private static ").Append(ReadOnlyListOf(TypeNames.GlobalParameter)).Append(" Parameters(")
            .Append(ReadOnlyListOf(TypeNames.GlobalLiveSettingDefinition)).AppendLine(" settings)");
        builder.AppendLine("    {");
        if (model.EventProperties.Count == 0) {
            builder.AppendLine("        if (settings.Count == 0) {");
            builder.Append("            return ").Append(EmptyArray(TypeNames.GlobalParameter)).AppendLine(";");
            builder.AppendLine("        }");
        }

        builder.Append("        var parameters = new ").Append(TypeNames.GlobalParameter).Append("[settings.Count + ")
            .Append(model.EventProperties.Count)
            .AppendLine("];");
        var parameterIndex = 0;
        foreach (var property in model.EventProperties) {
            builder.Append("        parameters[")
                .Append(parameterIndex)
                .Append("] = new ").Append(TypeNames.GlobalParameter).Append('(');
            builder.Append(LiteralReader.StringLiteral(DotBoxDExpressionModelFactory.EventVariable(property.Name)));
            builder.Append(", TypeOf(").Append(LiteralReader.StringLiteral(property.Type)).AppendLine("));");
            parameterIndex++;
        }

        builder.AppendLine("        for (var i = 0; i < settings.Count; i++) {");
        builder.AppendLine("            var setting = settings[i];");
        builder.Append("            parameters[i + ")
            .Append(model.EventProperties.Count)
            .Append("] = new ").Append(TypeNames.GlobalParameter).AppendLine("(setting.Name, TypeOf(setting.Type));");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return parameters;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.Append("    private static ").Append(TypeNames.GlobalSandboxType).Append(" TypeOf(")
            .Append(Parameter(DotBoxDGenerationNames.CSharpTypes.String, "type"))
            .AppendLine(") => type switch {");
        builder.AppendLine($"        {LiteralReader.StringLiteral(DotBoxDGenerationNames.ManifestTypes.Bool)} => {TypeNames.GlobalSandboxType}.Bool,");
        builder.AppendLine($"        {LiteralReader.StringLiteral(DotBoxDGenerationNames.ManifestTypes.Int)} => {TypeNames.GlobalSandboxType}.I32,");
        builder.AppendLine($"        {LiteralReader.StringLiteral(DotBoxDGenerationNames.ManifestTypes.Long)} => {TypeNames.GlobalSandboxType}.I64,");
        builder.AppendLine($"        {LiteralReader.StringLiteral(DotBoxDGenerationNames.ManifestTypes.Double)} => {TypeNames.GlobalSandboxType}.F64,");
        builder.AppendLine($"        {LiteralReader.StringLiteral(DotBoxDGenerationNames.ManifestTypes.String)} => {TypeNames.GlobalSandboxType}.String,");
        builder.AppendLine($"        _ => throw new {TypeNames.GlobalInvalidOperationException}($\"Unsupported generated setting type '{{type}}'.\")");
        builder.AppendLine("    };");
        builder.AppendLine();
        EmitHelper(
            builder,
            DotBoxDGenerationNames.Helpers.Var,
            Parameter(DotBoxDGenerationNames.CSharpTypes.String, "name"),
            $"new {TypeNames.GlobalVariableExpression}(name, Span)");
        EmitHelper(
            builder,
            DotBoxDGenerationNames.Helpers.Str,
            Parameter(DotBoxDGenerationNames.CSharpTypes.String, "value"),
            $"new {TypeNames.GlobalLiteralExpression}({TypeNames.GlobalSandboxValue}.FromString(value), Span)");
        EmitInt32ToStringHelper(builder);
        EmitStringLengthHelper(builder);
        EmitStringSubstringHelper(builder);
        EmitStringConcatHelper(builder);
        EmitStringEqualsHelper(builder);
        EmitHelper(
            builder,
            DotBoxDGenerationNames.Helpers.I32,
            Parameter(DotBoxDGenerationNames.CSharpTypes.Int, "value"),
            $"new {TypeNames.GlobalLiteralExpression}({TypeNames.GlobalSandboxValue}.FromInt32(value), Span)");
        EmitHelper(
            builder,
            DotBoxDGenerationNames.Helpers.I64,
            Parameter(DotBoxDGenerationNames.CSharpTypes.Long, "value"),
            $"new {TypeNames.GlobalLiteralExpression}({TypeNames.GlobalSandboxValue}.FromInt64(value), Span)");
        EmitHelper(
            builder,
            DotBoxDGenerationNames.Helpers.F64,
            Parameter(DotBoxDGenerationNames.CSharpTypes.Double, "value"),
            $"new {TypeNames.GlobalLiteralExpression}({TypeNames.GlobalSandboxValue}.FromDouble(value), Span)");
        EmitHelper(
            builder,
            DotBoxDGenerationNames.Helpers.Bool,
            Parameter(DotBoxDGenerationNames.CSharpTypes.Bool, "value"),
            $"new {TypeNames.GlobalLiteralExpression}({TypeNames.GlobalSandboxValue}.FromBool(value), Span)");
        EmitUnaryHelper(builder, DotBoxDGenerationNames.Helpers.Not, DotBoxDGenerationNames.Operators.LogicalNot);
        EmitUnaryHelper(builder, DotBoxDGenerationNames.Helpers.Neg, DotBoxDGenerationNames.Operators.Minus);
        EmitBinaryHelper(builder, DotBoxDGenerationNames.Helpers.Eq, DotBoxDGenerationNames.Operators.EqualTo);
        EmitBinaryHelper(builder, DotBoxDGenerationNames.Helpers.Ne, DotBoxDGenerationNames.Operators.NotEqualTo);
        EmitBinaryHelper(builder, DotBoxDGenerationNames.Helpers.Ge, DotBoxDGenerationNames.Operators.GreaterThanOrEqual);
        EmitBinaryHelper(builder, DotBoxDGenerationNames.Helpers.Gt, DotBoxDGenerationNames.Operators.GreaterThan);
        EmitBinaryHelper(builder, DotBoxDGenerationNames.Helpers.Le, DotBoxDGenerationNames.Operators.LessThanOrEqual);
        EmitBinaryHelper(builder, DotBoxDGenerationNames.Helpers.Lt, DotBoxDGenerationNames.Operators.LessThan);
        EmitBinaryHelper(builder, DotBoxDGenerationNames.Helpers.And, DotBoxDGenerationNames.Operators.LogicalAnd);
        EmitBinaryHelper(builder, DotBoxDGenerationNames.Helpers.Or, DotBoxDGenerationNames.Operators.LogicalOr);
        EmitBinaryHelper(builder, DotBoxDGenerationNames.Helpers.Add, DotBoxDGenerationNames.Operators.Add);
        EmitBinaryHelper(builder, DotBoxDGenerationNames.Helpers.Sub, DotBoxDGenerationNames.Operators.Minus);
        EmitBinaryHelper(builder, DotBoxDGenerationNames.Helpers.Mul, DotBoxDGenerationNames.Operators.Multiply);
        EmitBinaryHelper(builder, DotBoxDGenerationNames.Helpers.Div, DotBoxDGenerationNames.Operators.Divide);
        EmitBinaryHelper(builder, DotBoxDGenerationNames.Helpers.Mod, DotBoxDGenerationNames.Operators.Modulo);
    }

    private static void EmitHelper(StringBuilder builder, string name, string parameters, string expression)
        => builder.Append("    private static ").Append(TypeNames.GlobalExpression).Append(' ')
            .Append(name)
            .Append('(')
            .Append(parameters)
            .Append(") => ")
            .Append(expression)
            .AppendLine(";");

    private static void EmitStringConcatHelper(StringBuilder builder)
        => EmitBindingCallHelper(
            builder,
            DotBoxDGenerationNames.Helpers.ConcatString,
            DotBoxDGenerationNames.BindingIds.StringConcatBudgeted,
            $"{TypeNames.GlobalExpression} left, {TypeNames.GlobalExpression} right",
            "left, right");

    private static void EmitInt32ToStringHelper(StringBuilder builder)
        => EmitBindingCallHelper(
            builder,
            DotBoxDGenerationNames.Helpers.Int32ToStr,
            DotBoxDGenerationNames.BindingIds.Int32ToStringInvariant,
            $"{TypeNames.GlobalExpression} value",
            "value");

    private static void EmitStringLengthHelper(StringBuilder builder)
        => EmitBindingCallHelper(
            builder,
            DotBoxDGenerationNames.Helpers.StringLength,
            DotBoxDGenerationNames.BindingIds.StringLength,
            $"{TypeNames.GlobalExpression} value",
            "value");

    private static void EmitStringSubstringHelper(StringBuilder builder)
        => EmitBindingCallHelper(
            builder,
            DotBoxDGenerationNames.Helpers.StringSubstring,
            DotBoxDGenerationNames.BindingIds.StringSubstringBudgeted,
            $"{TypeNames.GlobalExpression} value, {TypeNames.GlobalExpression} startIndex, {TypeNames.GlobalExpression} length",
            "value, startIndex, length");

    private static void EmitStringEqualsHelper(StringBuilder builder)
        => EmitBindingCallHelper(
            builder,
            DotBoxDGenerationNames.Helpers.StringEquals,
            DotBoxDGenerationNames.BindingIds.StringEquals,
            $"{TypeNames.GlobalExpression} left, {TypeNames.GlobalExpression} right",
            "left, right");

    private static void EmitBindingCallHelper(
        StringBuilder builder,
        string helper,
        string bindingId,
        string parameters,
        string arguments)
        => EmitHelper(
            builder,
            helper,
            parameters,
            "new " + TypeNames.GlobalCallExpression + "(" +
            LiteralReader.StringLiteral(bindingId) +
            ", [" + arguments + "], null, Span)");

    private static string Parameter(string type, string name) => type + " " + name;

    private static string ArrayOf(string elementType) => elementType + "[]";

    private static string EmptyArray(string elementType) => TypeNames.GlobalArray + ".Empty<" + elementType + ">()";

    private static string ReadOnlyListOf(string elementType) => Generic(TypeNames.GlobalReadOnlyList, elementType);

    private static string Generic(string typeName, string argument) => typeName + "<" + argument + ">";

    private static string Generic(string typeName, string firstArgument, string secondArgument)
        => typeName + "<" + firstArgument + ", " + secondArgument + ">";

    private static void EmitUnaryHelper(StringBuilder builder, string name, string op)
        => EmitHelper(
            builder,
            name,
            $"{TypeNames.GlobalExpression} operand",
            $"new {TypeNames.GlobalUnaryExpression}({LiteralReader.StringLiteral(op)}, operand, Span)");

    private static void EmitBinaryHelper(StringBuilder builder, string name, string op)
        => EmitHelper(
            builder,
            name,
            $"{TypeNames.GlobalExpression} left, {TypeNames.GlobalExpression} right",
            $"new {TypeNames.GlobalBinaryExpression}(left, {LiteralReader.StringLiteral(op)}, right, Span)");

    private static string HandleExpression(DotBoxDHandleModel handle)
        => $"new {TypeNames.GlobalCallExpression}({TypeNames.GlobalPluginMessageBindings}.SendBindingId, [{handle.Target.Source}, {handle.Message.Source}], null, Span)";

    private static DotBoxDStatementBodyModel HandleBody(DotBoxDHandleModel handle)
    {
        var returned = DotBoxDStatementBodyModelFactory.Return(
            HandleExpression(handle),
            handle.Target.Allocates || handle.Message.Allocates);
        return handle.Prefix is null
            ? returned
            : DotBoxDStatementBodyModelFactory.Concat(handle.Prefix, returned);
    }
}
