using System.Text;

namespace ShaRPC.SourceGenerator;

/// <summary>
/// Generates server dispatcher classes for ShaRPC services. The dispatcher's
/// <c>DispatchAsync</c> is itself async, but it calls the user's service method using
/// the exact shape declared on the interface (sync vs async, with or without a
/// <see cref="System.Threading.CancellationToken"/>). All emitted type references are
/// fully qualified.
/// </summary>
internal static class DispatcherGenerator
{
    public static string Generate(ServiceModel service)
    {
        var sb = new StringBuilder();
        var dispatcherName = NamingHelpers.StripInterfacePrefix(service.InterfaceName) + "Dispatcher";
        var qualifiedInterface = QualifyServiceType(service, service.InterfaceName);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine($"namespace {service.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Server dispatcher for {service.InterfaceName}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public sealed class {dispatcherName} : global::ShaRPC.Core.Server.IServiceDispatcher");
        sb.AppendLine("    {");
        sb.AppendLine($"        private readonly {qualifiedInterface} _service;");
        sb.AppendLine();
        sb.AppendLine($"        public {dispatcherName}({qualifiedInterface} service)");
        sb.AppendLine("        {");
        sb.AppendLine("            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public string ServiceName => \"{service.ServiceName}\";");
        sb.AppendLine();
        // CS1998 is suppressed because services whose methods are all synchronous would
        // otherwise leave the async DispatchAsync with no `await`. The signature must
        // remain async to satisfy IServiceDispatcher.
        sb.AppendLine("#pragma warning disable CS1998");
        sb.AppendLine("        public async global::System.Threading.Tasks.Task<byte[]> DispatchAsync(string method, byte[] payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::System.Threading.CancellationToken ct = default)");
        sb.AppendLine("#pragma warning restore CS1998");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (method)");
        sb.AppendLine("            {");

        foreach (var m in service.Methods.Array)
        {
            GenerateDispatchCase(sb, m);
        }

        sb.AppendLine("                default:");
        sb.AppendLine($"                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException($\"Method '{{method}}' not found on service '{service.ServiceName}'.\");");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string QualifyServiceType(ServiceModel service, string typeName) =>
        string.IsNullOrEmpty(service.Namespace)
            ? "global::" + typeName
            : $"global::{service.Namespace}.{typeName}";

    private static void GenerateDispatchCase(StringBuilder sb, MethodModel method)
    {
        // Methods whose shape we cannot marshal (ref/in/out parameters) get no switch case;
        // an inbound call for them falls through to the default ShaRpcNotFoundException
        // branch, which is the same behaviour as calling an unknown method name.
        if (method.UnsupportedReason is not null)
        {
            return;
        }

        sb.AppendLine($"                case \"{method.RpcName}\":");
        sb.AppendLine("                {");

        var argList = new StringBuilder();
        if (method.Parameters.Count == 1)
        {
            sb.AppendLine($"                    var arg = serializer.Deserialize<{method.Parameters[0].Type}>(payload);");
            argList.Append("arg");
        }
        else if (method.Parameters.Count > 1)
        {
            var tupleTypes = new StringBuilder();
            for (var i = 0; i < method.Parameters.Count; i++)
            {
                if (i > 0) tupleTypes.Append(", ");
                tupleTypes.Append(method.Parameters[i].Type);
            }

            sb.AppendLine($"                    var args = serializer.Deserialize<({tupleTypes})>(payload);");
            for (var i = 0; i < method.Parameters.Count; i++)
            {
                if (i > 0) argList.Append(", ");
                argList.Append("args.Item").Append(i + 1);
            }
        }

        if (method.HasCancellationToken)
        {
            if (argList.Length > 0) argList.Append(", ");
            argList.Append("ct");
        }

        var call = $"_service.{method.Name}({argList})";

        switch (method.ReturnKind)
        {
            case MethodReturnKind.Void:
                sb.AppendLine($"                    {call};");
                sb.AppendLine("                    return global::System.Array.Empty<byte>();");
                break;

            case MethodReturnKind.Sync:
                sb.AppendLine($"                    var result = {call};");
                sb.AppendLine("                    return serializer.Serialize(result);");
                break;

            case MethodReturnKind.Task:
            case MethodReturnKind.ValueTask:
                sb.AppendLine($"                    await {call};");
                sb.AppendLine("                    return global::System.Array.Empty<byte>();");
                break;

            case MethodReturnKind.TaskOf:
            case MethodReturnKind.ValueTaskOf:
                sb.AppendLine($"                    var result = await {call};");
                sb.AppendLine("                    return serializer.Serialize(result);");
                break;
        }

        sb.AppendLine("                }");
    }
}
