using System;
using System.Linq;
using System.Text;

namespace ShaRPC.SourceGenerator;

/// <summary>
/// Generates client proxy classes for ShaRPC services.
/// </summary>
internal static class ProxyGenerator
{
    public static string Generate(ServiceModel service)
    {
        var sb = new StringBuilder();
        var proxyName = service.InterfaceName.StartsWith("I", StringComparison.Ordinal)
            ? service.InterfaceName.Substring(1) + "Proxy"
            : service.InterfaceName + "Proxy";

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ShaRPC.Core.Client;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine($"namespace {service.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Client proxy for {service.InterfaceName}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public sealed class {proxyName} : {service.InterfaceName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly IShaRpcClient _client;");
        sb.AppendLine();
        sb.AppendLine($"        public {proxyName}(IShaRpcClient client)");
        sb.AppendLine("        {");
        sb.AppendLine("            _client = client ?? throw new ArgumentNullException(nameof(client));");
        sb.AppendLine("        }");

        foreach (var method in service.Methods)
        {
            sb.AppendLine();
            GenerateProxyMethod(sb, service, method);
        }

        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void GenerateProxyMethod(StringBuilder sb, ServiceModel service, MethodModel method)
    {
        var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
        var ctParam = method.Parameters.Count > 0 ? ", CancellationToken ct = default" : "CancellationToken ct = default";

        sb.AppendLine($"        public async {method.ReturnType} {method.Name}({parameters}{ctParam})");
        sb.AppendLine("        {");

        if (method.Parameters.Count == 0)
        {
            if (method.ReturnsVoid)
            {
                sb.AppendLine($"            await _client.InvokeAsync<object>(\"{service.ServiceName}\", \"{method.RpcName}\", new object(), ct);");
            }
            else
            {
                sb.AppendLine($"            return await _client.InvokeAsync<object, {method.UnwrappedReturnType}>(\"{service.ServiceName}\", \"{method.RpcName}\", new object(), ct);");
            }
        }
        else if (method.Parameters.Count == 1)
        {
            var param = method.Parameters[0];
            if (method.ReturnsVoid)
            {
                sb.AppendLine($"            await _client.InvokeAsync(\"{service.ServiceName}\", \"{method.RpcName}\", {param.Name}, ct);");
            }
            else
            {
                sb.AppendLine($"            return await _client.InvokeAsync<{param.Type}, {method.UnwrappedReturnType}>(\"{service.ServiceName}\", \"{method.RpcName}\", {param.Name}, ct);");
            }
        }
        else
        {
            var tupleTypes = string.Join(", ", method.Parameters.Select(p => p.Type));
            var tupleValues = string.Join(", ", method.Parameters.Select(p => p.Name));

            if (method.ReturnsVoid)
            {
                sb.AppendLine($"            await _client.InvokeAsync(\"{service.ServiceName}\", \"{method.RpcName}\", ({tupleValues}), ct);");
            }
            else
            {
                sb.AppendLine($"            return await _client.InvokeAsync<({tupleTypes}), {method.UnwrappedReturnType}>(\"{service.ServiceName}\", \"{method.RpcName}\", ({tupleValues}), ct);");
            }
        }

        sb.AppendLine("        }");
    }
}
