namespace SafeIR.PluginAnalyzer;

using System.Text;
using Microsoft.CodeAnalysis.CSharp.Syntax;

internal static class SafeIrPackageSourceEmitter
{
    public static GeneratedPluginPackage Emit(PluginKernelModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        if (!string.IsNullOrWhiteSpace(model.Namespace)) {
            builder.Append("namespace ").Append(model.Namespace).AppendLine(";");
            builder.AppendLine();
        }

        builder.Append("public static class ").Append(model.PackageName).AppendLine();
        builder.AppendLine("{");
        EmitBody(builder, model);
        builder.AppendLine("}");
        return new GeneratedPluginPackage(model.PackageName + ".g.cs", builder.ToString());
    }

    private static void EmitBody(StringBuilder builder, PluginKernelModel model)
    {
        builder.AppendLine("    private static readonly global::SafeIR.SourceSpan Span = new(1, 1);");
        builder.AppendLine();
        builder.AppendLine("    public static global::SafeIR.Plugins.PluginPackage Create()");
        builder.AppendLine("    {");
        EmitSettings(builder, model);
        builder.AppendLine("        var manifest = new global::SafeIR.Plugins.PluginManifest(");
        builder.AppendLine($"            {LiteralReader.StringLiteral(model.PluginId)},");
        builder.AppendLine($"            {LiteralReader.StringLiteral($"IEventKernel<{model.EventName}>")},");
        builder.AppendLine("            global::SafeIR.ExecutionMode.Auto,");
        builder.AppendLine("            [\"Cpu\", \"Alloc\", \"GameStateWrite\", \"Audit\"],");
        builder.AppendLine("            settings,");
        builder.AppendLine($"            [new global::SafeIR.Plugins.HookSubscriptionManifest({LiteralReader.StringLiteral(model.EventName)}, {LiteralReader.StringLiteral(model.KernelName)})]);");
        builder.AppendLine("        return global::SafeIR.Plugins.PluginPackage.Create(manifest, CreateModule(settings));");
        builder.AppendLine("    }");
        builder.AppendLine();
        EmitModule(builder, model);
        EmitFunctions(builder, model);
        EmitHelpers(builder, model);
    }

    private static void EmitSettings(StringBuilder builder, PluginKernelModel model)
    {
        builder.AppendLine("        var settings = new global::SafeIR.Plugins.LiveSettingDefinition[] {");
        foreach (var setting in model.LiveSettings) {
            builder.Append("            new global::SafeIR.Plugins.LiveSettingDefinition(");
            builder.Append(LiteralReader.StringLiteral(setting.Name)).Append(", ");
            builder.Append(LiteralReader.StringLiteral(setting.Type)).Append(", ");
            builder.Append(setting.DefaultValue);
            if (setting.Min is not null || setting.Max is not null) {
                builder.Append(", ").Append(setting.Min ?? "null").Append(", ").Append(setting.Max ?? "null");
            }

            builder.AppendLine("),");
        }

        builder.AppendLine("        };");
    }

    private static void EmitModule(StringBuilder builder, PluginKernelModel model)
    {
        builder.AppendLine("    private static global::SafeIR.SandboxModule CreateModule(global::System.Collections.Generic.IReadOnlyList<global::SafeIR.Plugins.LiveSettingDefinition> settings)");
        builder.AppendLine("        => new(");
        builder.AppendLine($"            {LiteralReader.StringLiteral(model.PluginId)},");
        builder.AppendLine("            global::SafeIR.SemVersion.One,");
        builder.AppendLine("            global::SafeIR.SemVersion.One,");
        builder.AppendLine("            [new global::SafeIR.CapabilityRequest(global::SafeIR.Plugins.PluginMessageBindings.CapabilityId, \"send damage notifications\")],");
        builder.AppendLine("            [ShouldHandle(settings), Handle(settings)],");
        builder.AppendLine($"            new global::System.Collections.Generic.Dictionary<string, string> {{ [\"pluginId\"] = {LiteralReader.StringLiteral(model.PluginId)} }});");
        builder.AppendLine();
    }

    private static void EmitFunctions(StringBuilder builder, PluginKernelModel model)
    {
        var expressionEmitter = new SafeIrExpressionEmitter(model);
        builder.AppendLine("    private static global::SafeIR.SandboxFunction ShouldHandle(global::System.Collections.Generic.IReadOnlyList<global::SafeIR.Plugins.LiveSettingDefinition> settings)");
        builder.AppendLine("        => new(");
        builder.AppendLine("            \"ShouldHandle\", true, Parameters(settings), global::SafeIR.SandboxType.Bool,");
        builder.AppendLine($"            [new global::SafeIR.ReturnStatement({expressionEmitter.Emit(ReturnExpression(model.ShouldHandle))}, Span)]);");
        builder.AppendLine();
        builder.AppendLine("    private static global::SafeIR.SandboxFunction Handle(global::System.Collections.Generic.IReadOnlyList<global::SafeIR.Plugins.LiveSettingDefinition> settings)");
        builder.AppendLine("        => new(");
        builder.AppendLine("            \"Handle\", true, Parameters(settings), global::SafeIR.SandboxType.Unit,");
        builder.AppendLine($"            [new global::SafeIR.ReturnStatement({HandleExpression(model)}, Span)]);");
        builder.AppendLine();
    }

    private static void EmitHelpers(StringBuilder builder, PluginKernelModel model)
    {
        builder.AppendLine("    private static global::System.Collections.Generic.IReadOnlyList<global::SafeIR.Parameter> Parameters(global::System.Collections.Generic.IReadOnlyList<global::SafeIR.Plugins.LiveSettingDefinition> settings)");
        builder.AppendLine("        => global::System.Linq.Enumerable.ToArray(global::System.Linq.Enumerable.Concat(");
        builder.AppendLine("            EventParameters(),");
        builder.AppendLine("            global::System.Linq.Enumerable.Select(settings, s => new global::SafeIR.Parameter(s.Name, TypeOf(s.Type)))));");
        builder.AppendLine();
        builder.AppendLine("    private static global::System.Collections.Generic.IReadOnlyList<global::SafeIR.Parameter> EventParameters()");
        builder.AppendLine("        => [");
        foreach (var property in model.EventProperties) {
            builder.Append("            new global::SafeIR.Parameter(");
            builder.Append(LiteralReader.StringLiteral(SafeIrExpressionEmitter.EventVariable(property.Name)));
            builder.Append(", TypeOf(").Append(LiteralReader.StringLiteral(property.Type)).AppendLine(")),");
        }

        builder.AppendLine("        ];");
        builder.AppendLine();
        builder.AppendLine("    private static global::SafeIR.SandboxType TypeOf(string type) => type switch {");
        builder.AppendLine("        \"bool\" => global::SafeIR.SandboxType.Bool,");
        builder.AppendLine("        \"int\" => global::SafeIR.SandboxType.I32,");
        builder.AppendLine("        \"long\" => global::SafeIR.SandboxType.I64,");
        builder.AppendLine("        \"double\" => global::SafeIR.SandboxType.F64,");
        builder.AppendLine("        \"string\" => global::SafeIR.SandboxType.String,");
        builder.AppendLine("        _ => throw new global::System.InvalidOperationException($\"Unsupported generated setting type '{type}'.\")");
        builder.AppendLine("    };");
        builder.AppendLine();
        builder.AppendLine("    private static global::SafeIR.Expression Var(string name) => new global::SafeIR.VariableExpression(name, Span);");
        builder.AppendLine("    private static global::SafeIR.Expression Str(string value) => new global::SafeIR.LiteralExpression(global::SafeIR.SandboxValue.FromString(value), Span);");
        builder.AppendLine("    private static global::SafeIR.Expression I32(int value) => new global::SafeIR.LiteralExpression(global::SafeIR.SandboxValue.FromInt32(value), Span);");
        builder.AppendLine("    private static global::SafeIR.Expression Bool(bool value) => new global::SafeIR.LiteralExpression(global::SafeIR.SandboxValue.FromBool(value), Span);");
        builder.AppendLine("    private static global::SafeIR.Expression Eq(global::SafeIR.Expression left, global::SafeIR.Expression right) => new global::SafeIR.BinaryExpression(left, \"==\", right, Span);");
        builder.AppendLine("    private static global::SafeIR.Expression Ne(global::SafeIR.Expression left, global::SafeIR.Expression right) => new global::SafeIR.BinaryExpression(left, \"!=\", right, Span);");
        builder.AppendLine("    private static global::SafeIR.Expression Ge(global::SafeIR.Expression left, global::SafeIR.Expression right) => new global::SafeIR.BinaryExpression(left, \">=\", right, Span);");
        builder.AppendLine("    private static global::SafeIR.Expression Gt(global::SafeIR.Expression left, global::SafeIR.Expression right) => new global::SafeIR.BinaryExpression(left, \">\", right, Span);");
        builder.AppendLine("    private static global::SafeIR.Expression Le(global::SafeIR.Expression left, global::SafeIR.Expression right) => new global::SafeIR.BinaryExpression(left, \"<=\", right, Span);");
        builder.AppendLine("    private static global::SafeIR.Expression Lt(global::SafeIR.Expression left, global::SafeIR.Expression right) => new global::SafeIR.BinaryExpression(left, \"<\", right, Span);");
        builder.AppendLine("    private static global::SafeIR.Expression And(global::SafeIR.Expression left, global::SafeIR.Expression right) => new global::SafeIR.BinaryExpression(left, \"&&\", right, Span);");
        builder.AppendLine("    private static global::SafeIR.Expression Or(global::SafeIR.Expression left, global::SafeIR.Expression right) => new global::SafeIR.BinaryExpression(left, \"||\", right, Span);");
    }

    private static ExpressionSyntax ReturnExpression(MethodDeclarationSyntax method)
        => method.ExpressionBody?.Expression ??
           method.Body?.Statements.OfType<ReturnStatementSyntax>().FirstOrDefault()?.Expression ??
           throw new NotSupportedException("Kernel ShouldHandle must return an expression.");

    private static string HandleExpression(PluginKernelModel model)
    {
        var invocation = FindMessageSendInvocation(model);
        if (invocation is null || invocation.ArgumentList.Arguments.Count != 2) {
            throw new NotSupportedException("Kernel Handle must call ctx.Messages.Send(targetId, message).");
        }

        var emitter = new SafeIrExpressionEmitter(model, model.HandleEventParameterName);
        return $"new global::SafeIR.CallExpression(global::SafeIR.Plugins.PluginMessageBindings.SendBindingId, [{emitter.Emit(invocation.ArgumentList.Arguments[0].Expression)}, {emitter.Emit(invocation.ArgumentList.Arguments[1].Expression)}], null, Span)";
    }

    private static InvocationExpressionSyntax? FindMessageSendInvocation(PluginKernelModel model)
    {
        var invocation = model.Handle.ExpressionBody?.Expression as InvocationExpressionSyntax ??
            model.Handle.Body?.Statements.OfType<ExpressionStatementSyntax>()
                .Select(s => s.Expression)
                .OfType<InvocationExpressionSyntax>()
                .FirstOrDefault();
        if (invocation is null || !IsContextMessageSend(invocation.Expression, model.HandleContextParameterName)) {
            return null;
        }

        return invocation;
    }

    private static bool IsContextMessageSend(ExpressionSyntax expression, string contextParameterName)
    {
        if (expression is not MemberAccessExpressionSyntax sendAccess ||
            !string.Equals(sendAccess.Name.Identifier.ValueText, "Send", StringComparison.Ordinal) ||
            sendAccess.Expression is not MemberAccessExpressionSyntax messagesAccess ||
            !string.Equals(messagesAccess.Name.Identifier.ValueText, "Messages", StringComparison.Ordinal)) {
            return false;
        }

        return messagesAccess.Expression is IdentifierNameSyntax context &&
            string.Equals(context.Identifier.ValueText, contextParameterName, StringComparison.Ordinal);
    }
}
