//HintName: ShaRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace ShaRPC.Generated
{
    /// <summary>
    /// Extension methods for registering generated ShaRPC services.
    /// </summary>
    public static class ShaRpcGeneratedExtensions
    {

        /// <summary>
        /// Creates a proxy for IHello.
        /// </summary>
        public static global::Snap.Renamed.IHello CreateHelloProxy(this global::ShaRPC.Core.Client.IShaRpcClient client)
            => new global::Snap.Renamed.HelloProxy(client);

        /// <summary>
        /// Registers IHello with the server.
        /// </summary>
        public static global::ShaRPC.Core.Server.ShaRpcServerBuilder AddHello(this global::ShaRPC.Core.Server.ShaRpcServerBuilder builder, global::Snap.Renamed.IHello implementation)
            => builder.AddDispatcher(new global::Snap.Renamed.HelloDispatcher(implementation));
    }
}
