//HintName: ShaRpcGenerated.g.cs
// <auto-generated />
#nullable enable

namespace ShaRPC.Generated
{
    /// <summary>
    /// Factory methods for ShaRPC-generated proxies and dispatchers.
    /// </summary>
    public static class ShaRpcGenerated
    {
        static ShaRpcGenerated()
        {
            global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.Register<global::Snap.Inherit.IDerived>(
                static client => new global::Snap.Inherit.DerivedProxy(client),
                static implementation => new global::Snap.Inherit.DerivedDispatcher((global::Snap.Inherit.IDerived)implementation));
        }

        /// <summary>
        /// Creates the generated client proxy for <typeparamref name="TService" />.
        /// </summary>
        public static TService CreateProxy<TService>(global::ShaRPC.Core.Client.IShaRpcClient client)
            where TService : class
            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateProxy<TService>(client);

        /// <summary>
        /// Creates the generated client proxy for <paramref name="serviceInterface" />.
        /// </summary>
        public static object CreateProxy(global::System.Type serviceInterface, global::ShaRPC.Core.Client.IShaRpcClient client)
            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateProxy(serviceInterface, client);

        /// <summary>
        /// Creates the generated server dispatcher for <paramref name="implementation" />.
        /// </summary>
        public static global::ShaRPC.Core.Server.IServiceDispatcher CreateDispatcher<TService>(TService implementation)
            where TService : class
            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateDispatcher<TService>(implementation);

        /// <summary>
        /// Creates the generated server dispatcher for <paramref name="implementation" />.
        /// </summary>
        public static global::ShaRPC.Core.Server.IServiceDispatcher CreateDispatcher(global::System.Type serviceInterface, object implementation)
            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateDispatcher(serviceInterface, implementation);
    }
}
