//HintName: ShaRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace ShaRPC.Generated
{
    /// <summary>
    /// Extension methods for registering generated ShaRPC services.
    /// </summary>
    public static class ShaRpcGeneratedExtensions
    {

        /// <summary>
        /// Creates a proxy for IOne.
        /// </summary>
        public static global::Snap.Two.IOne CreateOneProxy(this global::ShaRPC.Core.Client.IShaRpcClient client)
            => new global::Snap.Two.OneProxy(client);

        /// <summary>
        /// Registers IOne with the server.
        /// </summary>
        public static global::ShaRPC.Core.Server.ShaRpcServerBuilder AddOne(this global::ShaRPC.Core.Server.ShaRpcServerBuilder builder, global::Snap.Two.IOne implementation)
            => builder.AddDispatcher(new global::Snap.Two.OneDispatcher(implementation));

        /// <summary>
        /// Creates a proxy for ITwo.
        /// </summary>
        public static global::Snap.Two.ITwo CreateTwoProxy(this global::ShaRPC.Core.Client.IShaRpcClient client)
            => new global::Snap.Two.TwoProxy(client);

        /// <summary>
        /// Registers ITwo with the server.
        /// </summary>
        public static global::ShaRPC.Core.Server.ShaRpcServerBuilder AddTwo(this global::ShaRPC.Core.Server.ShaRpcServerBuilder builder, global::Snap.Two.ITwo implementation)
            => builder.AddDispatcher(new global::Snap.Two.TwoDispatcher(implementation));
    }
}
