//HintName: ShaRpcExtensions.g.cs
// <auto-generated />
#nullable enable

using System;
using ShaRPC.Core.Client;
using ShaRPC.Core.Server;

namespace ShaRPC.Generated
{
    /// <summary>
    /// Extension methods for registering generated ShaRPC services.
    /// </summary>
    public static class ShaRpcGeneratedExtensions
    {

        /// <summary>
        /// Creates a proxy for IHello.
        /// </summary>
        public static Snap.Renamed.IHello CreateHelloProxy(this IShaRpcClient client)
            => new Snap.Renamed.HelloProxy(client);

        /// <summary>
        /// Registers IHello with the server.
        /// </summary>
        public static ShaRpcServerBuilder AddHello(this ShaRpcServerBuilder builder, Snap.Renamed.IHello implementation)
            => builder.AddDispatcher(new Snap.Renamed.HelloDispatcher(implementation));
    }
}
