//HintName: ITwo.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using ShaRPC.Core.Serialization;
using ShaRPC.Core.Server;
using ShaRPC.Core.Exceptions;

namespace Snap.Two
{
    /// <summary>
    /// Server dispatcher for ITwo.
    /// </summary>
    public sealed class TwoDispatcher : IServiceDispatcher
    {
        private readonly ITwo _service;

        public TwoDispatcher(ITwo service)
        {
            _service = service ?? throw new ArgumentNullException(nameof(service));
        }

        public string ServiceName => "ITwo";

        public async Task<byte[]> DispatchAsync(string method, byte[] payload, ISerializer serializer, CancellationToken ct = default)
        {
            switch (method)
            {
                case "BAsync":
                {
                    var result = await _service.BAsync(ct);
                    return serializer.Serialize(result);
                }
                default:
                    throw new ShaRpcNotFoundException($"Method '{method}' not found on service 'ITwo'.");
            }
        }
    }
}
