//HintName: ShaRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace ShaRPC.Generated
{
    /// <summary>
    /// Extension methods for registering generated ShaRPC services.
    /// </summary>
    public static class ShaRpcGeneratedExtensions
    {

        /// <summary>
        /// Creates a proxy for ICalculator.
        /// </summary>
        public static global::Snap.One.ICalculator CreateCalculatorProxy(this global::ShaRPC.Core.Client.IShaRpcClient client)
            => new global::Snap.One.CalculatorProxy(client);

        /// <summary>
        /// Registers ICalculator with the server.
        /// </summary>
        public static global::ShaRPC.Core.Server.ShaRpcServerBuilder AddCalculator(this global::ShaRPC.Core.Server.ShaRpcServerBuilder builder, global::Snap.One.ICalculator implementation)
            => builder.AddDispatcher(new global::Snap.One.CalculatorDispatcher(implementation));
    }
}
