//HintName: Snap_RefOut_IRefOutSnap.ShaRpcAsync.g.cs
// <auto-generated />
#nullable enable

namespace Snap.RefOut
{
    /// <summary>
    /// Auto-generated async sibling of <see cref="IRefOutSnap"/>. Use this
    /// interface from callers that must not block on RPC calls.
    /// </summary>
    public interface IRefOutSnapAsync
    {
        global::System.Threading.Tasks.Task<int> GoodAsync(int a, global::System.Threading.CancellationToken ct = default);
    }
}
