//HintName: ShaRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace ShaRPC.Generated
{
    /// <summary>
    /// Extension methods for registering generated ShaRPC services.
    /// </summary>
    public static class ShaRpcGeneratedExtensions
    {

        /// <summary>
        /// Creates a proxy for IRootSnap.
        /// </summary>
        public static global::Snap.Nested.IRootSnap CreateRootSnapProxy(this global::ShaRPC.Core.Client.IShaRpcClient client)
            => new global::Snap.Nested.RootSnapProxy(client);

        /// <summary>
        /// Registers IRootSnap with the server.
        /// </summary>
        public static global::ShaRPC.Core.Server.ShaRpcServerBuilder AddRootSnap(this global::ShaRPC.Core.Server.ShaRpcServerBuilder builder, global::Snap.Nested.IRootSnap implementation)
            => builder.AddDispatcher(new global::Snap.Nested.RootSnapDispatcher(implementation));

        /// <summary>
        /// Creates a proxy for ISubSnap.
        /// </summary>
        public static global::Snap.Nested.ISubSnap CreateSubSnapProxy(this global::ShaRPC.Core.Client.IShaRpcClient client)
            => new global::Snap.Nested.SubSnapProxy(client);

        /// <summary>
        /// Registers ISubSnap with the server.
        /// </summary>
        public static global::ShaRPC.Core.Server.ShaRpcServerBuilder AddSubSnap(this global::ShaRPC.Core.Server.ShaRpcServerBuilder builder, global::Snap.Nested.ISubSnap implementation)
            => builder.AddDispatcher(new global::Snap.Nested.SubSnapDispatcher(implementation));
    }
}
