//HintName: Snap_Two_IOne.ShaRpcAsync.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Two
{
    /// <summary>
    /// Auto-generated async sibling of <see cref="IOne"/>. Use this
    /// interface from callers that must not block on RPC calls.
    /// </summary>
    public interface IOneAsync
    {
        global::System.Threading.Tasks.Task<int> AAsync(int x, global::System.Threading.CancellationToken ct = default);
    }
}
