//HintName: ShaRpcExtensions.g.cs
// <auto-generated />
#nullable enable

using System;
using ShaRPC.Core.Client;
using ShaRPC.Core.Server;

namespace ShaRPC.Generated
{
    /// <summary>
    /// Extension methods for registering generated ShaRPC services.
    /// </summary>
    public static class ShaRpcGeneratedExtensions
    {

        /// <summary>
        /// Creates a proxy for IMix.
        /// </summary>
        public static Snap.Mixed.IMix CreateMixProxy(this IShaRpcClient client)
            => new Snap.Mixed.MixProxy(client);

        /// <summary>
        /// Registers IMix with the server.
        /// </summary>
        public static ShaRpcServerBuilder AddMix(this ShaRpcServerBuilder builder, Snap.Mixed.IMix implementation)
            => builder.AddDispatcher(new Snap.Mixed.MixDispatcher(implementation));
    }
}
