using System.Collections.Generic;
using System.Text;
using System.Threading;
using DotBoxD.Services.SourceGenerator.Infrastructure;
using DotBoxD.Services.SourceGenerator.Models;

namespace DotBoxD.Services.SourceGenerator.Generation;

internal static class DispatcherGenerator
{
    public static string Generate(ServiceModel service, CancellationToken ct = default)
    {
        var sb = new StringBuilder();
        var dispatcherName = NamingHelpers.StripInterfacePrefix(service.InterfaceName) + "Dispatcher";
        var qualifiedInterface = QualifyServiceType(service, service.InterfaceName);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine($"namespace {IdentifierHelpers.EscapeNamespace(service.Namespace)}");
            sb.AppendLine("{");
        }

        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Server dispatcher for {service.InterfaceName}.");
        sb.AppendLine("    /// </summary>");
        var dispatcherInterfaces = DispatcherGeneratorHelpers.CanDispatchWithoutStreaming(service)
            ? $"{ServicesGeneratorTypeNames.GlobalServiceDispatcher}, {ServicesGeneratorTypeNames.GlobalNonStreamingServiceDispatcher}"
            : ServicesGeneratorTypeNames.GlobalServiceDispatcher;
        sb.AppendLine($"    public sealed class {dispatcherName} : {dispatcherInterfaces}");
        sb.AppendLine("    {");
        sb.AppendLine($"        private readonly {qualifiedInterface}? _service;");
        sb.AppendLine();
        sb.AppendLine($"        internal {dispatcherName}()");
        sb.AppendLine("        {");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public {dispatcherName}({qualifiedInterface} service)");
        sb.AppendLine("        {");
        sb.AppendLine($"            _service = service ?? throw new {ServicesGeneratorTypeNames.GlobalArgumentNullException}(nameof(service));");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public string ServiceName => \"{service.ServiceName}\";");

        EmitDispatchAsync(sb, service, qualifiedInterface, isInstanceScoped: false, ct);
        EmitDispatchAsync(sb, service, qualifiedInterface, isInstanceScoped: true, ct);

        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string QualifyServiceType(ServiceModel service, string typeName) =>
        IdentifierHelpers.QualifyTypeName(service.Namespace, typeName);

    private static void EmitDispatchAsync(
        StringBuilder sb,
        ServiceModel service,
        string qualifiedInterface,
        bool isInstanceScoped,
        CancellationToken ct)
    {
        sb.AppendLine();
        if (isInstanceScoped)
        {
            sb.AppendLine($"        public {ServicesGeneratorTypeNames.GlobalTask} DispatchOnInstanceAsync(string instanceId, string method, {ServicesGeneratorTypeNames.Generic(ServicesGeneratorTypeNames.GlobalReadOnlyMemory, "byte")} payload, {ServicesGeneratorTypeNames.GlobalSerializer} serializer, {ServicesGeneratorTypeNames.GlobalInstanceRegistry} registry, {ServicesGeneratorTypeNames.Generic(ServicesGeneratorTypeNames.GlobalBufferWriter, "byte")} output, {ServicesGeneratorTypeNames.GlobalCancellationToken} ct = default) =>");
            sb.AppendLine($"            DispatchOnInstanceAsync(instanceId, method, payload, serializer, registry, output, {ServicesGeneratorTypeNames.GlobalRpcStreamingContext}.Disabled, ct);");
            sb.AppendLine();
            sb.AppendLine("#pragma warning disable CS1998");
            sb.AppendLine($"        public async {ServicesGeneratorTypeNames.GlobalTask} DispatchOnInstanceAsync(string instanceId, string method, {ServicesGeneratorTypeNames.Generic(ServicesGeneratorTypeNames.GlobalReadOnlyMemory, "byte")} payload, {ServicesGeneratorTypeNames.GlobalSerializer} serializer, {ServicesGeneratorTypeNames.GlobalInstanceRegistry} registry, {ServicesGeneratorTypeNames.Generic(ServicesGeneratorTypeNames.GlobalBufferWriter, "byte")} output, {ServicesGeneratorTypeNames.GlobalRpcStreamingContextInterface} streaming, {ServicesGeneratorTypeNames.GlobalCancellationToken} ct = default)");
        }
        else
        {
            sb.AppendLine($"        public {ServicesGeneratorTypeNames.GlobalTask} DispatchAsync(string method, {ServicesGeneratorTypeNames.Generic(ServicesGeneratorTypeNames.GlobalReadOnlyMemory, "byte")} payload, {ServicesGeneratorTypeNames.GlobalSerializer} serializer, {ServicesGeneratorTypeNames.GlobalInstanceRegistry} registry, {ServicesGeneratorTypeNames.Generic(ServicesGeneratorTypeNames.GlobalBufferWriter, "byte")} output, {ServicesGeneratorTypeNames.GlobalCancellationToken} ct = default) =>");
            sb.AppendLine($"            DispatchAsync(method, payload, serializer, registry, output, {ServicesGeneratorTypeNames.GlobalRpcStreamingContext}.Disabled, ct);");
            sb.AppendLine();
            sb.AppendLine("#pragma warning disable CS1998");
            sb.AppendLine($"        public async {ServicesGeneratorTypeNames.GlobalTask} DispatchAsync(string method, {ServicesGeneratorTypeNames.Generic(ServicesGeneratorTypeNames.GlobalReadOnlyMemory, "byte")} payload, {ServicesGeneratorTypeNames.GlobalSerializer} serializer, {ServicesGeneratorTypeNames.GlobalInstanceRegistry} registry, {ServicesGeneratorTypeNames.Generic(ServicesGeneratorTypeNames.GlobalBufferWriter, "byte")} output, {ServicesGeneratorTypeNames.GlobalRpcStreamingContextInterface} streaming, {ServicesGeneratorTypeNames.GlobalCancellationToken} ct = default)");
        }
        sb.AppendLine("#pragma warning restore CS1998");
        sb.AppendLine("        {");

        string receiver;
        if (isInstanceScoped)
        {
            sb.AppendLine($"            if (!registry.TryGet(\"{service.ServiceName}\", instanceId, out var __obj) || __obj is not {qualifiedInterface} __inst)");
            sb.AppendLine("            {");
            sb.AppendLine($"                throw new {ServicesGeneratorTypeNames.GlobalServiceNotFoundException}(\"Instance '\" + instanceId + \"' not found for service '{service.ServiceName}'.\", {ServicesGeneratorTypeNames.GlobalServiceNotFoundKind}.Instance);");
            sb.AppendLine("            }");
            receiver = "__inst";
        }
        else
        {
            sb.AppendLine("            if (_service is null)");
            sb.AppendLine("            {");
            sb.AppendLine($"                throw new {ServicesGeneratorTypeNames.GlobalServiceNotFoundException}(\"Service '{service.ServiceName}' can only dispatch instance calls.\", {ServicesGeneratorTypeNames.GlobalServiceNotFoundKind}.Service);");
            sb.AppendLine("            }");
            sb.AppendLine("            var __service = _service;");
            receiver = "__service";
        }

        sb.AppendLine("            switch (method)");
        sb.AppendLine("            {");

        foreach (var m in service.Methods.Array)
        {
            ct.ThrowIfCancellationRequested();
            GenerateDispatchCase(sb, service, m, receiver, ct);
        }

        sb.AppendLine("                default:");
        sb.AppendLine($"                    throw new {ServicesGeneratorTypeNames.GlobalServiceNotFoundException}(\"Method '\" + method + \"' not found on service '{service.ServiceName}'.\", {ServicesGeneratorTypeNames.GlobalServiceNotFoundKind}.Method);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static void GenerateDispatchCase(
        StringBuilder sb,
        ServiceModel service,
        MethodModel method,
        string receiver,
        CancellationToken ct)
    {
        // Methods whose shape we cannot marshal (ref/in/out parameters) get no switch case;
        // an inbound call for them falls through to the default ServiceNotFoundException
        // branch, which is the same behaviour as calling an unknown method name.
        if (method.UnsupportedReason is not null)
        {
            return;
        }

        sb.AppendLine($"                case \"{method.RpcName}\":");
        sb.AppendLine("                {");

            var requestParameters = DispatcherGeneratorHelpers.GetRequestParameters(method.Parameters, ct);
        if (requestParameters.Count == 1)
        {
            var wireType = ProxyGenerationHelpers.GetWireType(requestParameters[0]);
            sb.AppendLine($"                    var arg = serializer.Deserialize<{wireType}>(payload);");
        }
        else if (requestParameters.Count > 1)
        {
            var tupleTypes = new StringBuilder();
            for (var i = 0; i < requestParameters.Count; i++)
            {
                ct.ThrowIfCancellationRequested();

                if (i > 0) tupleTypes.Append(", ");
                tupleTypes.Append(ProxyGenerationHelpers.GetWireType(requestParameters[i]));
            }

            sb.AppendLine($"                    var args = serializer.Deserialize<({tupleTypes})>(payload);");
        }

        var locals = new GeneratedLocalNames(method.Parameters, ct);
        var argumentExpressions = new string[method.Parameters.Count];
        var argumentRequestIndex = 0;
        for (var i = 0; i < method.Parameters.Count; i++)
        {
            ct.ThrowIfCancellationRequested();

            var parameter = method.Parameters[i];
            if (parameter.IsCancellationToken)
            {
                argumentExpressions[i] = "ct";
                continue;
            }

            argumentRequestIndex++;
            var source = requestParameters.Count == 1
                ? "arg"
                : "args.Item" + argumentRequestIndex;
            if (parameter.StreamKind == ParameterStreamKind.None)
            {
                argumentExpressions[i] = source;
                continue;
            }

                    var local = locals.Reserve("__dotboxd_arg" + argumentRequestIndex, ct);
                    sb.AppendLine($"                    var {local} = {DispatcherGeneratorHelpers.BuildStreamingArgument(parameter, source)};");
            argumentExpressions[i] = local;
        }

        var argList = new StringBuilder();
        for (var i = 0; i < method.Parameters.Count; i++)
        {
            ct.ThrowIfCancellationRequested();

            if (i > 0) argList.Append(", ");
            argList.Append(argumentExpressions[i]);
        }

        var target = method.RequiresDispatcherReceiverCast
            ? $"(({method.ExplicitImplementationType}){receiver})"
            : receiver;
        var call = $"{target}.{method.Name}({argList})";

        switch (method.ReturnKind)
        {
            case MethodReturnKind.Void:
                sb.AppendLine($"                    {call};");
                sb.AppendLine("                    return;");
                break;

            case MethodReturnKind.Sync:
                sb.AppendLine($"                    var result = {call};");
                sb.AppendLine("                    serializer.Serialize(output, result);");
                sb.AppendLine("                    return;");
                break;

            case MethodReturnKind.Task:
                sb.AppendLine($"                    var __dotboxd_task = {call};");
                sb.AppendLine("                    if (!__dotboxd_task.IsCompletedSuccessfully)");
                sb.AppendLine("                    {");
                sb.AppendLine("                        await __dotboxd_task;");
                sb.AppendLine("                    }");
                sb.AppendLine("                    return;");
                break;

            case MethodReturnKind.ValueTask:
                sb.AppendLine($"                    var __dotboxd_task = {call};");
                sb.AppendLine("                    if (!__dotboxd_task.IsCompletedSuccessfully)");
                sb.AppendLine("                    {");
                sb.AppendLine("                        await __dotboxd_task;");
                sb.AppendLine("                        return;");
                sb.AppendLine("                    }");
                sb.AppendLine("                    __dotboxd_task.GetAwaiter().GetResult();");
                sb.AppendLine("                    return;");
                break;

            case MethodReturnKind.ValueTaskOf:
            case MethodReturnKind.TaskOf:
                sb.AppendLine($"                    var __dotboxd_task = {call};");
                sb.AppendLine("                    var __dotboxd_result = __dotboxd_task.IsCompletedSuccessfully");
                sb.AppendLine("                        ? __dotboxd_task.Result");
                sb.AppendLine("                        : await __dotboxd_task;");
                sb.AppendLine("                    serializer.Serialize(output, __dotboxd_result);");
                sb.AppendLine("                    return;");
                break;

            case MethodReturnKind.TaskOfSubService:
            case MethodReturnKind.ValueTaskOfSubService:
            case MethodReturnKind.SyncSubService:
            {
                // Sub-service return: don't serialize the live instance; instead register
                // it with the per-connection registry and ship back a ServiceHandle the
                // client can wrap in a sub-proxy.
                var info = method.SubService!;
                if (method.ReturnKind == MethodReturnKind.SyncSubService)
                {
                    sb.AppendLine($"                    var __sub = {call};");
                }
                else
                {
                    sb.AppendLine($"                    var __dotboxd_task = {call};");
                    sb.AppendLine("                    var __sub = __dotboxd_task.IsCompletedSuccessfully");
                    sb.AppendLine("                        ? __dotboxd_task.Result");
                    sb.AppendLine("                        : await __dotboxd_task;");
                }

                if (info.AllowsNull)
                {
                    sb.AppendLine("                    if (__sub is null)");
                    sb.AppendLine("                    {");
                    sb.AppendLine($"                        serializer.Serialize<{ServicesGeneratorTypeNames.NullableOf(ServicesGeneratorTypeNames.GlobalServiceHandle)}>(output, null);");
                    sb.AppendLine("                        return;");
                    sb.AppendLine("                    }");
                }
                sb.AppendLine("                    string __subId;");
                sb.AppendLine("                    try");
                sb.AppendLine("                    {");
                sb.AppendLine($"                        __subId = registry.Register(\"{info.ServiceName}\", __sub);");
                sb.AppendLine("                    }");
                sb.AppendLine("                    catch");
                sb.AppendLine("                    {");
                sb.AppendLine("                        try");
                sb.AppendLine("                        {");
                sb.AppendLine($"                            if (__sub is {ServicesGeneratorTypeNames.GlobalIAsyncDisposable} __ad)");
                sb.AppendLine("                            {");
                sb.AppendLine("                                await __ad.DisposeAsync().ConfigureAwait(false);");
                sb.AppendLine("                            }");
                sb.AppendLine($"                            else if (__sub is {ServicesGeneratorTypeNames.GlobalIDisposable} __d)");
                sb.AppendLine("                            {");
                sb.AppendLine("                                __d.Dispose();");
                sb.AppendLine("                            }");
                sb.AppendLine("                        }");
                sb.AppendLine("                        catch");
                sb.AppendLine("                        {");
                sb.AppendLine("                            // Best-effort cleanup of the orphaned sub-service: a faulting disposer must");
                sb.AppendLine("                            // not replace the original registration failure that is about to be rethrown.");
                sb.AppendLine("                        }");
                sb.AppendLine("                        throw;");
                sb.AppendLine("                    }");
                sb.AppendLine("                    try");
                sb.AppendLine("                    {");
                sb.AppendLine($"                        serializer.Serialize(output, new {ServicesGeneratorTypeNames.GlobalServiceHandle} {{ ServiceName = \"{info.ServiceName}\", InstanceId = __subId }});");
                sb.AppendLine("                    }");
                sb.AppendLine("                    catch");
                sb.AppendLine("                    {");
                sb.AppendLine($"                        await registry.ReleaseAsync(\"{info.ServiceName}\", __subId).ConfigureAwait(false);");
                sb.AppendLine("                        throw;");
                sb.AppendLine("                    }");
                sb.AppendLine("                    return;");
                break;
            }

            case MethodReturnKind.AsyncEnumerable:
            case MethodReturnKind.Stream:
            case MethodReturnKind.Pipe:
                sb.AppendLine($"                    var result = {call};");
                sb.AppendLine("                    streaming.SetResponse(result);");
                sb.AppendLine("                    return;");
                break;

            case MethodReturnKind.TaskOfAsyncEnumerable:
            case MethodReturnKind.ValueTaskOfAsyncEnumerable:
            case MethodReturnKind.TaskOfStream:
            case MethodReturnKind.ValueTaskOfStream:
            case MethodReturnKind.TaskOfPipe:
            case MethodReturnKind.ValueTaskOfPipe:
                sb.AppendLine($"                    var __dotboxd_task = {call};");
                sb.AppendLine("                    var __dotboxd_result = __dotboxd_task.IsCompletedSuccessfully");
                sb.AppendLine("                        ? __dotboxd_task.Result");
                sb.AppendLine("                        : await __dotboxd_task;");
                sb.AppendLine("                    streaming.SetResponse(__dotboxd_result);");
                sb.AppendLine("                    return;");
                break;
        }

        sb.AppendLine("                }");
    }

}
