using System.Text;
using System.Threading;
using DotBoxD.Services.SourceGenerator.Infrastructure;
using DotBoxD.Services.SourceGenerator.Models;

namespace DotBoxD.Services.SourceGenerator.Generation;

internal static class DispatcherGenerator
{
    public static string Generate(ServiceModel service, CancellationToken ct = default)
    {
        var sb = new StringBuilder();
        var dispatcherName = NamingHelpers.StripInterfacePrefix(service.InterfaceName) + "Dispatcher";
        var qualifiedInterface = QualifyServiceType(service, service.InterfaceName);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine($"namespace {IdentifierHelpers.EscapeNamespace(service.Namespace)}");
            sb.AppendLine("{");
        }

        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Server dispatcher for {service.InterfaceName}.");
        sb.AppendLine("    /// </summary>");
        var dispatcherInterfaces = DispatcherGeneratorHelpers.CanDispatchWithoutStreaming(service)
            ? $"{ServicesGeneratorTypeNames.GlobalServiceDispatcher}, {ServicesGeneratorTypeNames.GlobalNonStreamingServiceDispatcher}"
            : ServicesGeneratorTypeNames.GlobalServiceDispatcher;
        sb.AppendLine($"    public sealed class {dispatcherName} : {dispatcherInterfaces}");
        sb.AppendLine("    {");
        sb.AppendLine($"        private readonly {qualifiedInterface}? _service;");
        sb.AppendLine();
        sb.AppendLine($"        public {dispatcherName}()");
        sb.AppendLine("        {");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public {dispatcherName}({qualifiedInterface} service)");
        sb.AppendLine("        {");
        sb.AppendLine($"            _service = service ?? throw new {ServicesGeneratorTypeNames.GlobalArgumentNullException}(nameof(service));");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public string {ServicesGeneratorMemberNames.ServiceDispatcher.ServiceName} => \"{service.ServiceName}\";");

        EmitDispatchEndpoint(sb, service, qualifiedInterface, isInstanceScoped: false);
        EmitDispatchEndpoint(sb, service, qualifiedInterface, isInstanceScoped: true);
        EmitDispatchCore(sb, service, qualifiedInterface, ct);

        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string QualifyServiceType(ServiceModel service, string typeName) =>
        IdentifierHelpers.QualifyTypeName(service.Namespace, typeName);

    private static void EmitDispatchEndpoint(
        StringBuilder sb,
        ServiceModel service,
        string qualifiedInterface,
        bool isInstanceScoped)
    {
        sb.AppendLine();
        if (isInstanceScoped)
        {
            sb.AppendLine($"        public {ServicesGeneratorTypeNames.GlobalTask} {ServicesGeneratorMemberNames.ServiceDispatcher.DispatchOnInstanceAsync}(string instanceId, string method, {ServicesGeneratorTypeNames.Generic(ServicesGeneratorTypeNames.GlobalReadOnlyMemory, "byte")} payload, {ServicesGeneratorTypeNames.GlobalSerializer} serializer, {ServicesGeneratorTypeNames.GlobalInstanceRegistry} registry, {ServicesGeneratorTypeNames.Generic(ServicesGeneratorTypeNames.GlobalBufferWriter, "byte")} output, {ServicesGeneratorTypeNames.GlobalCancellationToken} ct = default) =>");
            sb.AppendLine($"            {ServicesGeneratorMemberNames.ServiceDispatcher.DispatchOnInstanceAsync}(instanceId, method, payload, serializer, registry, output, {ServicesGeneratorTypeNames.GlobalRpcStreamingContext}.{ServicesGeneratorMemberNames.RpcStreamingContext.Disabled}, ct);");
            sb.AppendLine();
            sb.AppendLine($"        public {ServicesGeneratorTypeNames.GlobalTask} {ServicesGeneratorMemberNames.ServiceDispatcher.DispatchOnInstanceAsync}(string instanceId, string method, {ServicesGeneratorTypeNames.Generic(ServicesGeneratorTypeNames.GlobalReadOnlyMemory, "byte")} payload, {ServicesGeneratorTypeNames.GlobalSerializer} serializer, {ServicesGeneratorTypeNames.GlobalInstanceRegistry} registry, {ServicesGeneratorTypeNames.Generic(ServicesGeneratorTypeNames.GlobalBufferWriter, "byte")} output, {ServicesGeneratorTypeNames.GlobalRpcStreamingContextInterface} streaming, {ServicesGeneratorTypeNames.GlobalCancellationToken} ct = default)");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (!registry.{ServicesGeneratorMemberNames.InstanceRegistry.TryGet}(\"{service.ServiceName}\", instanceId, out var __obj) || __obj is not {qualifiedInterface} __inst)");
            sb.AppendLine("            {");
            sb.AppendLine($"                throw new {ServicesGeneratorTypeNames.GlobalServiceNotFoundException}(\"Instance '\" + instanceId + \"' not found for service '{service.ServiceName}'.\", {ServicesGeneratorTypeNames.GlobalServiceNotFoundKind}.{ServicesGeneratorMemberNames.NotFoundKind.Instance});");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return DispatchCoreAsync(__inst, method, payload, serializer, registry, output, streaming, ct);");
            sb.AppendLine("        }");
            return;
        }

        sb.AppendLine($"        public {ServicesGeneratorTypeNames.GlobalTask} {ServicesGeneratorMemberNames.ServiceDispatcher.DispatchAsync}(string method, {ServicesGeneratorTypeNames.Generic(ServicesGeneratorTypeNames.GlobalReadOnlyMemory, "byte")} payload, {ServicesGeneratorTypeNames.GlobalSerializer} serializer, {ServicesGeneratorTypeNames.GlobalInstanceRegistry} registry, {ServicesGeneratorTypeNames.Generic(ServicesGeneratorTypeNames.GlobalBufferWriter, "byte")} output, {ServicesGeneratorTypeNames.GlobalCancellationToken} ct = default) =>");
        sb.AppendLine($"            {ServicesGeneratorMemberNames.ServiceDispatcher.DispatchAsync}(method, payload, serializer, registry, output, {ServicesGeneratorTypeNames.GlobalRpcStreamingContext}.{ServicesGeneratorMemberNames.RpcStreamingContext.Disabled}, ct);");
        sb.AppendLine();
        sb.AppendLine($"        public {ServicesGeneratorTypeNames.GlobalTask} {ServicesGeneratorMemberNames.ServiceDispatcher.DispatchAsync}(string method, {ServicesGeneratorTypeNames.Generic(ServicesGeneratorTypeNames.GlobalReadOnlyMemory, "byte")} payload, {ServicesGeneratorTypeNames.GlobalSerializer} serializer, {ServicesGeneratorTypeNames.GlobalInstanceRegistry} registry, {ServicesGeneratorTypeNames.Generic(ServicesGeneratorTypeNames.GlobalBufferWriter, "byte")} output, {ServicesGeneratorTypeNames.GlobalRpcStreamingContextInterface} streaming, {ServicesGeneratorTypeNames.GlobalCancellationToken} ct = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_service is null)");
        sb.AppendLine("            {");
        sb.AppendLine($"                throw new {ServicesGeneratorTypeNames.GlobalServiceNotFoundException}(\"Service '{service.ServiceName}' can only dispatch instance calls.\", {ServicesGeneratorTypeNames.GlobalServiceNotFoundKind}.{ServicesGeneratorMemberNames.NotFoundKind.Service});");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return DispatchCoreAsync(_service, method, payload, serializer, registry, output, streaming, ct);");
        sb.AppendLine("        }");
    }

    private static void EmitDispatchCore(
        StringBuilder sb,
        ServiceModel service,
        string qualifiedInterface,
        CancellationToken ct)
    {
        sb.AppendLine();
        sb.AppendLine("#pragma warning disable CS1998");
        sb.AppendLine($"        private async {ServicesGeneratorTypeNames.GlobalTask} DispatchCoreAsync({qualifiedInterface} receiver, string method, {ServicesGeneratorTypeNames.Generic(ServicesGeneratorTypeNames.GlobalReadOnlyMemory, "byte")} payload, {ServicesGeneratorTypeNames.GlobalSerializer} serializer, {ServicesGeneratorTypeNames.GlobalInstanceRegistry} registry, {ServicesGeneratorTypeNames.Generic(ServicesGeneratorTypeNames.GlobalBufferWriter, "byte")} output, {ServicesGeneratorTypeNames.GlobalRpcStreamingContextInterface} streaming, {ServicesGeneratorTypeNames.GlobalCancellationToken} ct)");
        sb.AppendLine("#pragma warning restore CS1998");
        sb.AppendLine("        {");

        sb.AppendLine("            switch (method)");
        sb.AppendLine("            {");

        foreach (var m in service.Methods.Array)
        {
            ct.ThrowIfCancellationRequested();
            DispatcherCaseGenerator.Generate(sb, service, m, "receiver", ct);
        }

        sb.AppendLine("                default:");
        sb.AppendLine($"                    throw new {ServicesGeneratorTypeNames.GlobalServiceNotFoundException}(\"Method '\" + method + \"' not found on service '{service.ServiceName}'.\", {ServicesGeneratorTypeNames.GlobalServiceNotFoundKind}.{ServicesGeneratorMemberNames.NotFoundKind.Method});");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

}
