using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;
using DotBoxD.Services.SourceGenerator.Infrastructure;
using DotBoxD.Services.SourceGenerator.Models;

namespace DotBoxD.Services.SourceGenerator.Generation;

internal static class ExtensionsGenerator
{
    public static string Generate(EquatableArray<ServiceIdentity> services, CancellationToken ct = default)
    {
        var sb = new StringBuilder();
        var extensionSuffixes = BuildExtensionSuffixes(services, ct);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").AppendLine(ServicesGeneratorTypeNames.GeneratedNamespace);
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Extension methods for registering generated DotBoxD services.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class DotBoxDGeneratedExtensions");
        sb.AppendLine("    {");

        foreach (var service in services)
        {
            ct.ThrowIfCancellationRequested();
            var serviceName = NamingHelpers.StripInterfacePrefix(service.InterfaceName);
            var extensionSuffix = extensionSuffixes[ServiceKey(service)];
            var proxyName = serviceName + "Proxy";
            var dispatcherName = serviceName + "Dispatcher";
            var fullInterfaceName = IdentifierHelpers.QualifyTypeName(service.Namespace, service.InterfaceName);
            var fullProxyName = IdentifierHelpers.QualifyTypeName(service.Namespace, proxyName);
            var fullDispatcherName = IdentifierHelpers.QualifyTypeName(service.Namespace, dispatcherName);

            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// Provides a {service.InterfaceName} implementation for the other peer to call.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public static {ServicesGeneratorTypeNames.GlobalRpcPeer} Provide{extensionSuffix}(this {ServicesGeneratorTypeNames.GlobalRpcPeer} peer, {fullInterfaceName} implementation)");
            sb.AppendLine($"            => peer.Provide(({ServicesGeneratorTypeNames.GlobalServiceDispatcher})new {fullDispatcherName}(implementation));");

            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// Gets a proxy to call {service.InterfaceName} on the other peer.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public static {fullInterfaceName} Get{extensionSuffix}(this {ServicesGeneratorTypeNames.GlobalRpcPeer} peer)");
            sb.AppendLine($"            => new {fullProxyName}(peer);");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static Dictionary<string, string> BuildExtensionSuffixes(
        EquatableArray<ServiceIdentity> services,
        CancellationToken ct)
    {
        var shortNameCounts = new Dictionary<string, int>(StringComparer.Ordinal);
        foreach (var service in services)
        {
            ct.ThrowIfCancellationRequested();

            var shortName = NamingHelpers.StripInterfacePrefix(service.InterfaceName);
            shortNameCounts.TryGetValue(shortName, out var count);
            shortNameCounts[shortName] = count + 1;
        }

        var suffixes = new Dictionary<string, string>(StringComparer.Ordinal);
        var used = new HashSet<string>(StringComparer.Ordinal);
        foreach (var service in services)
        {
            ct.ThrowIfCancellationRequested();

            var serviceName = NamingHelpers.StripInterfacePrefix(service.InterfaceName);
            var suffix = shortNameCounts[serviceName] > 1
                ? QualifiedSuffix(service, serviceName)
                : serviceName;
            var candidate = suffix;
            var disambiguator = 1;
            while (!used.Add(candidate))
            {
                ct.ThrowIfCancellationRequested();

                candidate = suffix + "__" + disambiguator.ToString(System.Globalization.CultureInfo.InvariantCulture);
                disambiguator++;
            }

            suffixes[ServiceKey(service)] = candidate;
        }

        return suffixes;
    }

    private static string QualifiedSuffix(ServiceIdentity service, string serviceName) =>
        string.IsNullOrEmpty(service.Namespace)
            ? serviceName
            : HintNameBuilder.NamespaceIdentifierPrefix(service.Namespace) + "_" + serviceName;

    private static string ServiceKey(ServiceIdentity service) =>
        service.Namespace + "\u001f" + service.InterfaceName + "\u001f" + service.ServiceName;
}
