using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;
using DotBoxD.Services.SourceGenerator.Infrastructure;
using DotBoxD.Services.SourceGenerator.Models;

namespace DotBoxD.Services.SourceGenerator.Generation;

internal static class ExtensionsGenerator
{
    public static string Generate(EquatableArray<ServiceExtensionModel> services, CancellationToken ct = default)
    {
        var sb = new StringBuilder();
        var extensionSuffixes = BuildExtensionSuffixes(services, ct);
        var servicesByType = BuildServicesByType(services, ct);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").AppendLine(ServicesGeneratorTypeNames.GeneratedNamespace);
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Extension methods for registering generated DotBoxD services.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class DotBoxDGeneratedExtensions");
        sb.AppendLine("    {");

        foreach (var service in services)
        {
            ct.ThrowIfCancellationRequested();
            var serviceName = NamingHelpers.StripInterfacePrefix(service.InterfaceName);
            var extensionSuffix = extensionSuffixes[ServiceKey(service)];
            var dispatcherName = serviceName + "Dispatcher";
            var fullInterfaceName = IdentifierHelpers.QualifyTypeName(service.Namespace, service.InterfaceName);
            var fullDispatcherName = IdentifierHelpers.QualifyTypeName(service.Namespace, dispatcherName);

            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// Provides a {service.InterfaceName} implementation for the other peer to call.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public static {ServicesGeneratorTypeNames.GlobalRpcPeer} Provide{extensionSuffix}(this {ServicesGeneratorTypeNames.GlobalRpcPeer} peer, {fullInterfaceName} implementation)");
            if (!HasSubServiceProperties(service, ct) && service.MethodSubServices.Array.Length == 0)
            {
                sb.AppendLine($"            => peer.Provide(({ServicesGeneratorTypeNames.GlobalServiceDispatcher})new {fullDispatcherName}(implementation));");
            }
            else
            {
                sb.AppendLine("        {");
                sb.AppendLine($"            peer.Provide(({ServicesGeneratorTypeNames.GlobalServiceDispatcher})new {fullDispatcherName}(implementation));");
                foreach (var property in service.Properties.Array)
                {
                    ct.ThrowIfCancellationRequested();
                    if (property.IsInstanceId)
                    {
                        continue;
                    }

                    var propertyAccess = PropertyAccess(property);
                    if (servicesByType.TryGetValue(property.Type, out var propertyService))
                    {
                        sb.AppendLine($"            peer.Provide{extensionSuffixes[ServiceKey(propertyService)]}({propertyAccess});");
                    }
                    else
                    {
                        var proxyType = property.ProxyType!;
                        var propertyDispatcher = proxyType.EndsWith("Proxy", StringComparison.Ordinal)
                            ? proxyType.Substring(0, proxyType.Length - "Proxy".Length) + "Dispatcher"
                            : proxyType + "Dispatcher";
                        sb.AppendLine($"            peer.Provide(({ServicesGeneratorTypeNames.GlobalServiceDispatcher})new {propertyDispatcher}({propertyAccess}));");
                    }
                }

                foreach (var subService in service.MethodSubServices.Array)
                {
                    ct.ThrowIfCancellationRequested();
                    if (!servicesByType.TryGetValue(subService.QualifiedInterfaceName, out var methodService))
                    {
                        continue;
                    }

                    var methodDispatcherName = NamingHelpers.StripInterfacePrefix(methodService.InterfaceName) + "Dispatcher";
                    var fullMethodDispatcherName = IdentifierHelpers.QualifyTypeName(methodService.Namespace, methodDispatcherName);
                    sb.AppendLine($"            peer.Provide(({ServicesGeneratorTypeNames.GlobalServiceDispatcher})new {fullMethodDispatcherName}());");
                }
                sb.AppendLine("            return peer;");
                sb.AppendLine("        }");
            }

            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// Gets a proxy to call {service.InterfaceName} on the other peer.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public static {fullInterfaceName} Get{extensionSuffix}(this {ServicesGeneratorTypeNames.GlobalRpcPeer} peer)");
            sb.AppendLine($"            => peer.Get<{fullInterfaceName}>();");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static bool HasSubServiceProperties(ServiceExtensionModel service, CancellationToken ct)
    {
        foreach (var property in service.Properties.Array)
        {
            ct.ThrowIfCancellationRequested();
            if (!property.IsInstanceId)
            {
                return true;
            }
        }

        return false;
    }

    private static string PropertyAccess(ServicePropertyModel property)
        => string.IsNullOrEmpty(property.DeclaringType)
            ? "implementation." + property.Name
            : "((" + property.DeclaringType + ")implementation)." + property.Name;

    private static Dictionary<string, string> BuildExtensionSuffixes(
        EquatableArray<ServiceExtensionModel> services,
        CancellationToken ct)
    {
        var shortNameCounts = new Dictionary<string, int>(StringComparer.Ordinal);
        foreach (var service in services)
        {
            ct.ThrowIfCancellationRequested();

            var shortName = NamingHelpers.StripInterfacePrefix(service.InterfaceName);
            shortNameCounts.TryGetValue(shortName, out var count);
            shortNameCounts[shortName] = count + 1;
        }

        var suffixes = new Dictionary<string, string>(StringComparer.Ordinal);
        var used = new HashSet<string>(StringComparer.Ordinal);
        foreach (var service in services)
        {
            ct.ThrowIfCancellationRequested();

            var serviceName = NamingHelpers.StripInterfacePrefix(service.InterfaceName);
            var suffix = shortNameCounts[serviceName] > 1
                ? QualifiedSuffix(service, serviceName)
                : serviceName;
            var candidate = suffix;
            var disambiguator = 1;
            while (!used.Add(candidate))
            {
                ct.ThrowIfCancellationRequested();

                candidate = suffix + "__" + disambiguator.ToString(System.Globalization.CultureInfo.InvariantCulture);
                disambiguator++;
            }

            suffixes[ServiceKey(service)] = candidate;
        }

        return suffixes;
    }

    private static Dictionary<string, ServiceExtensionModel> BuildServicesByType(
        EquatableArray<ServiceExtensionModel> services,
        CancellationToken ct)
    {
        var result = new Dictionary<string, ServiceExtensionModel>(StringComparer.Ordinal);
        foreach (var service in services.Array)
        {
            ct.ThrowIfCancellationRequested();
            result[IdentifierHelpers.QualifyTypeName(service.Namespace, service.InterfaceName)] = service;
        }

        return result;
    }

    private static string QualifiedSuffix(ServiceExtensionModel service, string serviceName) =>
        string.IsNullOrEmpty(service.Namespace)
            ? serviceName
            : HintNameBuilder.NamespaceIdentifierPrefix(service.Namespace) + "_" + serviceName;

    private static string ServiceKey(ServiceExtensionModel service) =>
        service.Namespace + "\u001f" + service.InterfaceName + "\u001f" + service.ServiceName;
}
