using System.Text;
using System.Threading;
using DotBoxD.Services.SourceGenerator.Infrastructure;
using DotBoxD.Services.SourceGenerator.Models;

namespace DotBoxD.Services.SourceGenerator.Generation;

internal static class GeneratedFactoryGenerator
{
    public static string Generate(EquatableArray<ServiceModel> services, CancellationToken ct = default)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").AppendLine(ServicesGeneratorTypeNames.GeneratedNamespace);
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Factory methods for DotBoxD-generated proxies and dispatchers.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class DotBoxDGenerated");
        sb.AppendLine("    {");
        GeneratedFactoryMetadataEmitter.AppendMethodArrays(sb, services, ct);
        sb.AppendLine();
        sb.AppendLine($"        private static readonly {ServicesGeneratorTypeNames.ArrayOf(ServicesGeneratorTypeNames.GlobalGeneratedService)} s_services =");
        sb.AppendLine("        {");

        for (var i = 0; i < services.Array.Length; i++)
        {
            ct.ThrowIfCancellationRequested();
            var service = services.Array[i];
            var serviceName = NamingHelpers.StripInterfacePrefix(service.InterfaceName);
            var fullInterfaceName = IdentifierHelpers.QualifyTypeName(service.Namespace, service.InterfaceName);
            var fullProxyName = IdentifierHelpers.QualifyTypeName(service.Namespace, serviceName + "Proxy");
            var fullDispatcherName = IdentifierHelpers.QualifyTypeName(service.Namespace, serviceName + "Dispatcher");

            sb.AppendLine($"            new {ServicesGeneratorTypeNames.GlobalGeneratedService}(");
            sb.AppendLine($"                typeof({fullInterfaceName}),");
            sb.AppendLine($"                typeof({fullProxyName}),");
            sb.AppendLine($"                typeof({fullDispatcherName}),");
            // service.ServiceName is already escaped at model-build time (ServiceModelFactory),
            // matching every other emission site (proxy/dispatcher). Inserting it directly avoids
            // double-escaping names that contain backslashes, quotes, or control characters.
            sb.AppendLine($"                \"{service.ServiceName}\",");
            sb.AppendLine($"                {GeneratedFactoryMetadataEmitter.MethodArrayName(i)}),");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        static DotBoxDGenerated()");
        sb.AppendLine("        {");
        sb.AppendLine($"            {ServicesGeneratorTypeNames.GlobalGeneratedServiceRegistry}.RegisterServices(");
        sb.AppendLine($"                typeof({ServicesGeneratorTypeNames.GlobalDotBoxDGenerated}).Assembly,");
        sb.AppendLine("                s_services);");

        for (var i = 0; i < services.Array.Length; i++)
        {
            ct.ThrowIfCancellationRequested();
            var service = services.Array[i];
            var serviceName = NamingHelpers.StripInterfacePrefix(service.InterfaceName);
            var fullInterfaceName = IdentifierHelpers.QualifyTypeName(service.Namespace, service.InterfaceName);
            var fullProxyName = IdentifierHelpers.QualifyTypeName(service.Namespace, serviceName + "Proxy");
            var fullDispatcherName = IdentifierHelpers.QualifyTypeName(service.Namespace, serviceName + "Dispatcher");

            sb.AppendLine($"            {ServicesGeneratorTypeNames.GlobalGeneratedServiceRegistry}.Register<{fullInterfaceName}>(");
            sb.AppendLine($"                static client => new {fullProxyName}(client),");
            sb.AppendLine($"                static implementation => new {fullDispatcherName}(({fullInterfaceName})implementation),");
            sb.AppendLine($"                s_services[{i.ToString(System.Globalization.CultureInfo.InvariantCulture)}]);");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Gets the services generated into this assembly without scanning for generated types.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static {ServicesGeneratorTypeNames.Generic(ServicesGeneratorTypeNames.GlobalReadOnlyList, ServicesGeneratorTypeNames.GlobalGeneratedService)} Services");
        sb.AppendLine("            => s_services;");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Adds generated service proxy registrations to <paramref name=\"sink\" /> without scanning generated types.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static void RegisterServices({ServicesGeneratorTypeNames.GlobalServiceRegistrationSink} sink)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (sink is null)");
        sb.AppendLine("            {");
        sb.AppendLine($"                throw new {ServicesGeneratorTypeNames.GlobalArgumentNullException}(nameof(sink));");
        sb.AppendLine("            }");
        sb.AppendLine();

        foreach (var service in services.Array)
        {
            ct.ThrowIfCancellationRequested();
            var serviceName = NamingHelpers.StripInterfacePrefix(service.InterfaceName);
            var fullInterfaceName = IdentifierHelpers.QualifyTypeName(service.Namespace, service.InterfaceName);
            var fullProxyName = IdentifierHelpers.QualifyTypeName(service.Namespace, serviceName + "Proxy");

            sb.AppendLine($"            sink.AddService<{fullInterfaceName}, {fullProxyName}>();");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Adds generated service proxy and dispatcher registrations to <paramref name=\"sink\" /> without scanning generated types.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static void RegisterGeneratedServices({ServicesGeneratorTypeNames.GlobalGeneratedServiceRegistrationSink} sink)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (sink is null)");
        sb.AppendLine("            {");
        sb.AppendLine($"                throw new {ServicesGeneratorTypeNames.GlobalArgumentNullException}(nameof(sink));");
        sb.AppendLine("            }");
        sb.AppendLine();

        foreach (var service in services.Array)
        {
            ct.ThrowIfCancellationRequested();
            var serviceName = NamingHelpers.StripInterfacePrefix(service.InterfaceName);
            var fullInterfaceName = IdentifierHelpers.QualifyTypeName(service.Namespace, service.InterfaceName);
            var fullProxyName = IdentifierHelpers.QualifyTypeName(service.Namespace, serviceName + "Proxy");
            var fullDispatcherName = IdentifierHelpers.QualifyTypeName(service.Namespace, serviceName + "Dispatcher");

            sb.AppendLine($"            sink.AddService<{fullInterfaceName}, {fullProxyName}, {fullDispatcherName}>();");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Creates the generated proxy for <typeparamref name=\"TService\" /> over an invoker.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static TService CreateProxy<TService>({ServicesGeneratorTypeNames.GlobalRpcInvoker} invoker)");
        sb.AppendLine("            where TService : class");
        sb.AppendLine($"            => {ServicesGeneratorTypeNames.GlobalGeneratedServiceRegistry}.CreateProxy<TService>(invoker);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Creates the generated proxy for <paramref name=\"serviceInterface\" /> over an invoker.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static object CreateProxy({ServicesGeneratorTypeNames.GlobalType} serviceInterface, {ServicesGeneratorTypeNames.GlobalRpcInvoker} invoker)");
        sb.AppendLine($"            => {ServicesGeneratorTypeNames.GlobalGeneratedServiceRegistry}.CreateProxy(serviceInterface, invoker);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Creates the generated server dispatcher for <paramref name=\"implementation\" />.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static {ServicesGeneratorTypeNames.GlobalServiceDispatcher} CreateDispatcher<TService>(TService implementation)");
        sb.AppendLine("            where TService : class");
        sb.AppendLine($"            => {ServicesGeneratorTypeNames.GlobalGeneratedServiceRegistry}.CreateDispatcher<TService>(implementation);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Creates the generated server dispatcher for <paramref name=\"implementation\" />.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static {ServicesGeneratorTypeNames.GlobalServiceDispatcher} CreateDispatcher({ServicesGeneratorTypeNames.GlobalType} serviceInterface, object implementation)");
        sb.AppendLine($"            => {ServicesGeneratorTypeNames.GlobalGeneratedServiceRegistry}.CreateDispatcher(serviceInterface, implementation);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
