using System.Text;
using System.Threading;
using DotBoxD.Services.SourceGenerator.Infrastructure;
using DotBoxD.Services.SourceGenerator.Models;

namespace DotBoxD.Services.SourceGenerator.Generation;

/// <summary>
/// Generates client proxy classes for DotBoxD services. The generated proxy implements
/// the user's interface exactly — same return types, same parameter list, only adding
/// a forwarding body to <c>IRpcInvoker</c>. All emitted
/// type references are fully qualified with <c>global::</c> so the generated file
/// never depends on the user's <c>using</c> set.
/// </summary>
internal static partial class ProxyGenerator
{
    public static string Generate(
        ServiceModel service,
        EquatableArray<AsyncSiblingMethod> siblingMethods,
        CancellationToken ct = default)
    {
        var sb = new StringBuilder();
        var proxyName = NamingHelpers.StripInterfacePrefix(service.InterfaceName) + "Proxy";
        var qualifiedInterface = QualifyServiceType(service, service.InterfaceName);
        var qualifiedAsyncSibling = QualifyServiceType(
            service,
            NamingHelpers.AsyncSiblingInterfaceName(service.InterfaceName));

        // The proxy class implements both the user's interface and the generated async
        // sibling so callers can pick the blocking or non-blocking view.
        var baseList = siblingMethods.IsEmpty
            ? qualifiedInterface
            : $"{qualifiedInterface}, {qualifiedAsyncSibling}";

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine($"namespace {IdentifierHelpers.EscapeNamespace(service.Namespace)}");
            sb.AppendLine("{");
        }

        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Client proxy for {service.InterfaceName}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public sealed class {proxyName} : {baseList}");
        sb.AppendLine("    {");
        sb.AppendLine($"        private readonly {ServicesGeneratorTypeNames.GlobalRpcInvoker} _invoker;");
        sb.AppendLine("        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>");
        sb.AppendLine("        private readonly string? _instanceId;");
        foreach (var property in service.Properties.Array)
        {
            ct.ThrowIfCancellationRequested();
            if (property.IsInstanceId)
            {
                continue;
            }

            sb.AppendLine($"        private readonly {property.Type} {PropertyFieldName(property)};");
        }
        sb.AppendLine();
        sb.AppendLine($"        public {proxyName}({ServicesGeneratorTypeNames.GlobalRpcInvoker} client)");
        sb.AppendLine("        {");
        sb.AppendLine($"            this._invoker = client ?? throw new {ServicesGeneratorTypeNames.GlobalArgumentNullException}(nameof(client));");
        sb.AppendLine("            this._instanceId = null;");
        foreach (var property in service.Properties.Array)
        {
            ct.ThrowIfCancellationRequested();
            if (property.IsInstanceId)
            {
                continue;
            }

            sb.AppendLine($"            this.{PropertyFieldName(property)} = new {property.ProxyType}(client);");
        }
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>");
        sb.AppendLine($"        public {proxyName}({ServicesGeneratorTypeNames.GlobalRpcInvoker} client, string instanceId)");
        sb.AppendLine("        {");
        sb.AppendLine($"            this._invoker = client ?? throw new {ServicesGeneratorTypeNames.GlobalArgumentNullException}(nameof(client));");
        sb.AppendLine($"            this._instanceId = instanceId ?? throw new {ServicesGeneratorTypeNames.GlobalArgumentNullException}(nameof(instanceId));");
        foreach (var property in service.Properties.Array)
        {
            ct.ThrowIfCancellationRequested();
            if (property.IsInstanceId)
            {
                continue;
            }

            sb.AppendLine($"            this.{PropertyFieldName(property)} = new {property.ProxyType}(client);");
        }
        sb.AppendLine("        }");

        foreach (var property in service.Properties.Array)
        {
            ct.ThrowIfCancellationRequested();
            sb.AppendLine();
            if (property.IsInstanceId)
            {
                sb.AppendLine($"        public {property.Type} {property.Name} => this._instanceId ?? string.Empty;");
            }
            else
            {
                sb.AppendLine($"        public {property.Type} {property.Name} => this.{PropertyFieldName(property)};");
            }
        }

        foreach (var method in service.Methods.Array)
        {
            ct.ThrowIfCancellationRequested();
            sb.AppendLine();
            GenerateProxyMethod(sb, service, method, proxyName, ct);
            if (ProxyGenerationHelpers.MethodNameRequiresExplicitImplementation(method.Name, proxyName))
            {
                foreach (var implementationType in method.AdditionalExplicitImplementationTypes.Array)
                {
                    ct.ThrowIfCancellationRequested();
                    sb.AppendLine();
                    GenerateProxyMethod(
                        sb,
                        service,
                        method with { ExplicitImplementationType = implementationType },
                        proxyName,
                        ct);
                }
            }
        }

        foreach (var s in siblingMethods.Array)
        {
            ct.ThrowIfCancellationRequested();
            if (!s.RequiresExtraProxyMethod &&
                !ProxyGenerationHelpers.MethodNameRequiresExplicitImplementation(s.Name, proxyName))
            {
                continue;
            }

            sb.AppendLine();
            GenerateAsyncSiblingMethod(sb, service, s, proxyName, qualifiedAsyncSibling, ct);
        }

        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
    private static string QualifyServiceType(ServiceModel service, string typeName) =>
        IdentifierHelpers.QualifyTypeName(service.Namespace, typeName);

    private static string PropertyFieldName(ServicePropertyModel property) =>
        "__dotboxd_" + IdentifierHelpers.UnescapeIdentifier(property.Name);

    private static void GenerateProxyMethod(
        StringBuilder sb,
        ServiceModel service,
        MethodModel method,
        string proxyName,
        CancellationToken ct)
    {
        var paramList = new StringBuilder();
        ProxyGenerationHelpers.AppendParameterList(paramList, method.Parameters, ct);

        var declaredReturn = method.DeclaredReturnType;
        // Stubs stay non-async so out-parameters are definitely assigned by throw.
        var asyncKeyword = method.UnsupportedReason is null && RequiresAsyncStateMachine(method.ReturnKind)
            ? "async "
            : string.Empty;
        var unsafeKeyword = method.RequiresUnsafeSignature ? "unsafe " : string.Empty;
        var ctArg = ProxyGenerationHelpers.GetCancellationTokenArgument(method.Parameters, ct);
        var explicitInterface = ProxyGenerationHelpers.MethodNameRequiresExplicitImplementation(method.Name, proxyName);
        var access = explicitInterface ? string.Empty : "public ";
        var target = explicitInterface ? method.ExplicitImplementationType + "." + method.Name : method.Name;

        AppendReturnAttributes(sb, method.ReturnAttributePrefix);
        sb.AppendLine($"        {access}{unsafeKeyword}{asyncKeyword}{method.ReturnRefKindKeyword}{declaredReturn} {target}{method.TypeParameterList}({paramList}){method.ConstraintClauses}");
        sb.AppendLine("        {");

        if (method.UnsupportedReason is not null)
        {
            sb.AppendLine($"            throw new {ServicesGeneratorTypeNames.GlobalNotSupportedException}(\"DotBoxD cannot marshal '{IdentifierHelpers.UnescapeIdentifier(method.Name)}': {LiteralHelpers.EscapeStringLiteral(method.UnsupportedReason)}\");");
        }
        else
        {
            var locals = new GeneratedLocalNames(method.Parameters, ct);
            if (method.ReturnKind == MethodReturnKind.AsyncEnumerable &&
                HasStreamedRequestParameter(method, ct))
            {
                EmitLazyAsyncEnumerableInvocation(sb, service, method, ctArg, locals, ct);
            }
            else
            {
                var invocation = BuildClientInvocation(sb, service, method, ctArg, locals, ct);
                ProxyInvocationCleanupEmitter.EmitProxyInvocation(
                    sb,
                    method,
                    invocation.Invocation,
                    invocation.Reservations,
                    locals,
                    ct);
            }
        }

        sb.AppendLine("        }");
    }

    /// <summary>
    /// Emits a non-blocking proxy method that satisfies the async sibling interface.
    /// Reuses the underlying RPC call site of the original method (same service, same
    /// wire method name) but returns a Task / Task&lt;T&gt; so the caller never blocks.
    /// </summary>
    private static void GenerateAsyncSiblingMethod(
        StringBuilder sb,
        ServiceModel service,
        AsyncSiblingMethod s,
        string proxyName,
        string qualifiedAsyncSibling,
        CancellationToken ct)
    {
        var paramList = new StringBuilder();
        ProxyGenerationHelpers.AppendParameterList(paramList, s.Parameters, ct);

        var declaredReturn = NamingHelpers.GetDeclaredReturnTypeText(
            s.SiblingReturnKind, s.Source.UnwrappedReturnType);
        var explicitInterface = ProxyGenerationHelpers.MethodNameRequiresExplicitImplementation(s.Name, proxyName);
        var access = explicitInterface ? string.Empty : "public ";
        var target = explicitInterface ? qualifiedAsyncSibling + "." + s.Name : s.Name;

        var asyncKeyword = RequiresAsyncStateMachine(s.SiblingReturnKind) ? "async " : string.Empty;
        sb.AppendLine($"        {access}{asyncKeyword}{declaredReturn} {target}({paramList})");
        sb.AppendLine("        {");

        // For the wire call, treat the sibling as having a CancellationToken AND the
        // sibling's return kind (so the invocation picks the right overload).
        var virtualSource = s.Source with
        {
            HasCancellationToken = true,
            ReturnKind = s.SiblingReturnKind,
            Parameters = s.Parameters,
        };
        var locals = new GeneratedLocalNames(s.Parameters, ct);
        var ctArg = ProxyGenerationHelpers.GetCancellationTokenArgument(s.Parameters, ct);
        if (virtualSource.ReturnKind == MethodReturnKind.AsyncEnumerable &&
            HasStreamedRequestParameter(virtualSource, ct))
        {
            EmitLazyAsyncEnumerableInvocation(sb, service, virtualSource, ctArg, locals, ct);
        }
        else
        {
            var invocation = BuildClientInvocation(sb, service, virtualSource, ctArg, locals, ct);
            ProxyInvocationCleanupEmitter.EmitProxyInvocation(
                sb,
                virtualSource,
                invocation.Invocation,
                invocation.Reservations,
                locals,
                ct);
        }

        sb.AppendLine("        }");
    }

    private static bool RequiresAsyncStateMachine(MethodReturnKind returnKind) =>
        returnKind is MethodReturnKind.TaskOfSubService or MethodReturnKind.ValueTaskOfSubService;

    private static void AppendReturnAttributes(StringBuilder sb, string attributes)
    {
        if (attributes.Length == 0)
        {
            return;
        }

        var lines = attributes.Split(['\n'], System.StringSplitOptions.RemoveEmptyEntries);
        foreach (var line in lines)
        {
            sb.Append("        ").AppendLine(line.TrimEnd('\r'));
        }
    }
}
