using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using DotBoxD.Plugins.Analyzer.Analysis.Lowering;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using TypeNames = DotBoxD.Plugins.Analyzer.Analysis.Lowering.DotBoxDGenerationNames.TypeNames;

namespace DotBoxD.Plugins.Analyzer.Analysis.HookChains;

internal static class HookChainStageIrEmitter
{
    public static void EmitSteps(SourceProductionContext context, ImmutableArray<HookChainStageIrModel> models)
    {
        foreach (var model in DistinctModels(models))
        {
            context.AddSource(model.HintName, SourceText.From(BuildStep(model), Encoding.UTF8));
        }
    }

    public static void EmitInterceptors(
        SourceProductionContext context,
        ImmutableArray<HookChainStageIrInterception> interceptions)
    {
        var distinct = DistinctInterceptions(interceptions);
        if (distinct.Count == 0)
        {
            return;
        }

        context.AddSource("DotBoxDHookChainStageIrInterceptors.g.cs", BuildInterceptors(distinct));
    }

    private static string BuildStep(HookChainStageIrModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        if (!string.IsNullOrWhiteSpace(model.Namespace))
        {
            builder.Append("namespace ").Append(model.Namespace).AppendLine(";");
            builder.AppendLine();
        }

        builder.Append("public static class ").Append(model.ClassName).AppendLine();
        builder.AppendLine("{");
        builder.Append("    private static readonly ").Append(TypeNames.GlobalSourceSpan).Append(" Span = new(")
            .Append(DotBoxDGenerationNames.GeneratedSpanLine)
            .Append(", ")
            .Append(DotBoxDGenerationNames.GeneratedSpanColumn)
            .AppendLine(");");
        builder.AppendLine();
        builder.Append("    public static global::DotBoxD.Abstractions.LoweredPipelineStep").AppendLine(" Create()");
        builder.AppendLine("        => new(");
        builder.Append("            global::DotBoxD.Abstractions.LoweredPipelineStepKind.")
            .Append(model.Kind).AppendLine(",");
        builder.AppendLine($"            {LiteralReader.StringLiteral(model.InputType)},");
        builder.AppendLine($"            {LiteralReader.StringLiteral(model.OutputType)},");
        builder.Append("            new ").Append(TypeNames.GlobalParameter).Append("[] { ")
            .Append(model.ParameterSource).AppendLine(" },");
        builder.Append("            ").Append(TypeNames.GlobalArray).Append(".Empty<")
            .Append(TypeNames.GlobalStatement).AppendLine(">(),");
        builder.Append("            ").Append(model.ValueSource).AppendLine(",");
        builder.Append("            ").Append(StringArray(model.RequiredCapabilities)).AppendLine(",");
        builder.Append("            ").Append(StringArray(model.Effects)).AppendLine(");");
        builder.AppendLine();
        AppendGeneratedAttributes(builder, model.GeneratedAttributeSource, "    ");
        builder.Append("    public static ").Append(model.IRFuncType).Append(" CreateIRFunc");
        if (model.IRFuncTypeParameters is { Length: > 0 } typeParameters)
        {
            builder.Append('<').Append(typeParameters).Append('>');
        }

        builder.AppendLine("()");
        builder.Append("        => ").Append(model.IRFuncType).AppendLine(".FromStep(Create());");
        builder.AppendLine();
        DotBoxD.Plugins.Analyzer.Analysis.MergeableIr.MergeableIrExpressionHelperEmitter.Emit(builder);
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string BuildInterceptors(IReadOnlyList<HookChainStageIrInterception> interceptions)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        InterceptsLocationAttributeEmitter.Append(builder);
        builder.Append("namespace ").AppendLine(DotBoxDGenerationNames.TypeNames.GeneratedInterceptorsNamespace);
        builder.AppendLine("{");
        builder.AppendLine("    internal static class HookChainStageIrInterceptors");
        builder.AppendLine("    {");
        for (var i = 0; i < interceptions.Count; i++)
        {
            AppendInterceptor(builder, interceptions[i], i);
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendInterceptor(
        StringBuilder builder,
        HookChainStageIrInterception interception,
        int index)
    {
        builder.Append("        ").AppendLine(interception.AttributeSyntax);
        AppendGeneratedAttributes(builder, interception.GeneratedAttributeSource, "        ");
        builder.Append("        public static ").Append(interception.ReturnType).Append(" Intercept_")
            .Append(index.ToString(CultureInfo.InvariantCulture));
        if (interception.InterceptorTypeParameters is { Length: > 0 } typeParameters)
        {
            builder.Append('<').Append(typeParameters).Append('>');
        }

        builder.AppendLine("(");
        builder.Append("            this ").Append(interception.ReceiverType).AppendLine(" receiver,");
        builder.Append("            ").Append(interception.DelegateType).Append(' ')
            .Append(Identifier(interception.SourceParameterName)).AppendLine(",");
        builder.Append("            ").Append(interception.IRFuncType).Append("? ")
            .Append(Identifier(interception.IRParameterName)).AppendLine(" = null)");
        builder.Append("            => receiver.").Append(interception.MethodName)
            .Append(interception.MethodTypeArguments)
            .Append('(')
            .Append(ArgumentName(interception.SourceParameterName))
            .Append(": ")
            .Append(Identifier(interception.SourceParameterName))
            .Append(", ")
            .Append(ArgumentName(interception.IRParameterName))
            .Append(": ")
            .Append(Identifier(interception.IRParameterName))
            .Append(" ?? ")
            .Append(interception.StepFullName)
            .Append(".CreateIRFunc")
            .Append(interception.CreateIRFuncTypeArguments)
            .AppendLine("());");
    }

    private static IReadOnlyList<HookChainStageIrModel> DistinctModels(ImmutableArray<HookChainStageIrModel> models)
    {
        if (models.IsDefaultOrEmpty)
        {
            return [];
        }

        var seen = new HashSet<string>(StringComparer.Ordinal);
        var distinct = new List<HookChainStageIrModel>();
        foreach (var model in models)
        {
            if (seen.Add(model.HintName))
            {
                distinct.Add(model);
            }
        }

        return distinct;
    }

    private static IReadOnlyList<HookChainStageIrInterception> DistinctInterceptions(
        ImmutableArray<HookChainStageIrInterception> interceptions)
    {
        if (interceptions.IsDefaultOrEmpty)
        {
            return [];
        }

        var seen = new HashSet<string>(StringComparer.Ordinal);
        var distinct = new List<HookChainStageIrInterception>();
        foreach (var interception in interceptions)
        {
            if (seen.Add(interception.AttributeSyntax))
            {
                distinct.Add(interception);
            }
        }

        return distinct;
    }

    private static string StringArray(EquatableArray<string> values)
    {
        if (values.Count == 0)
        {
            return TypeNames.GlobalArray + ".Empty<string>()";
        }

        var builder = new StringBuilder();
        builder.Append("new string[] { ");
        for (var i = 0; i < values.Count; i++)
        {
            if (i > 0)
            {
                builder.Append(", ");
            }

            builder.Append(LiteralReader.StringLiteral(values[i]));
        }

        builder.Append(" }");
        return builder.ToString();
    }

    private static void AppendGeneratedAttributes(StringBuilder builder, string attributeSource, string indent)
    {
        if (attributeSource.Length == 0)
        {
            return;
        }

        foreach (var line in attributeSource.Split('\n'))
        {
            if (line.Length > 0)
            {
                builder.Append(indent).AppendLine(line);
            }
        }
    }

    private static string ArgumentName(string parameterName) => "@" + parameterName;

    private static string Identifier(string parameterName) => "@" + parameterName;
}
