using static DotBoxD.Kernels.Verifier.Diagnostics.VerifierDiagnosticCodes;

namespace DotBoxD.Kernels.Verifier.Diagnostics;

internal static class VerifierDiagnosticReferenceCatalog
{
    public static readonly IReadOnlyList<VerifierDiagnosticReference> All =
    [
        new(ManifestHash, VerifierDiagnosticCategory.ArtifactIntegrity,
            "Assembly hash is missing from the manifest or does not match the artifact bytes.",
            "The artifact was altered after the manifest was produced, or the wrong manifest is paired with the artifact.",
            "Treat as a tampering/cache-poisoning signal. Re-fetch the artifact and manifest from a trusted source and re-verify.",
            false),
        new(ManifestIdentity, VerifierDiagnosticCategory.HostVersionMismatch,
            "Manifest identity does not match the expected verification context, or no expected identity was supplied.",
            "Compiler/type-system/runtime/verifier versions differ from the host, or the artifact came from a different release.",
            "Confirm the artifact was produced by a compatible toolchain version, then re-verify with the matching expected manifest identity.",
            false),
        new(PeFormat, VerifierDiagnosticCategory.MalformedArtifact,
            "Portable Executable container is malformed or is not a valid DotBoxD.Kernels DLL.",
            "Corrupt, truncated, or tampered bytes, or output from a non-DotBoxD.Kernels producer.",
            "Re-produce the artifact from source and re-verify; reject the current bytes.",
            false),
        new(PeMetadata, VerifierDiagnosticCategory.MalformedArtifact,
            "Assembly has no CLR metadata or CLR header.",
            "The bytes are not a managed assembly, or metadata was stripped/corrupted.",
            "Reject the artifact and re-produce it from a trusted compiler.",
            false),
        new(PeMixed, VerifierDiagnosticCategory.MalformedArtifact,
            "Assembly is mixed-mode or contains native code.",
            "A non-DotBoxD.Kernels or tampered producer emitted native code.",
            "Reject the artifact; only IL-only managed assemblies are accepted.",
            false),
        new(PeEntrypoint, VerifierDiagnosticCategory.MalformedArtifact,
            "Generated artifact defines an entrypoint, which is not allowed.",
            "A non-DotBoxD.Kernels or tampered producer marked an entrypoint.",
            "Reject the artifact; generated modules must not declare an entrypoint.",
            false),
        new(PeNative, VerifierDiagnosticCategory.MalformedArtifact,
            "Assembly contains native PE or CLR header directories.",
            "Native export/import/TLS or native CLR header directories were present.",
            "Reject the artifact; native directories are never emitted by the canonical compiler.",
            false),
        new(PeSection, VerifierDiagnosticCategory.MalformedArtifact,
            "Assembly contains a disallowed PE section or unsafe section permissions.",
            "Sections beyond .text/.rsrc/.reloc, or writable+executable sections, were present.",
            "Reject the artifact; only the canonical read-only/executable section layout is allowed.",
            false),
        new(IlFormat, VerifierDiagnosticCategory.MalformedArtifact,
            "A method body contained malformed or unreadable IL.",
            "Corrupt or tampered method-body bytes.",
            "Reject the artifact and re-produce it from source.",
            false),
        new(AssemblyReference, VerifierDiagnosticCategory.ForbiddenCapability,
            "An assembly reference is not on the policy allow-list.",
            "The generated code referenced an assembly the sandbox policy does not permit.",
            "Remove the disallowed dependency from the source program, or widen the policy only if intentionally trusted.",
            false),
        new(TypeForbidden, VerifierDiagnosticCategory.ForbiddenCapability,
            "A type reference matches a policy-forbidden prefix.",
            "The source program used a type family explicitly denied by policy (for example IO or reflection types).",
            "Remove the forbidden type usage from the source program.",
            false),
        new(TypeReference, VerifierDiagnosticCategory.ForbiddenCapability,
            "A type reference is not on the policy allow-list.",
            "The source program referenced a type outside the allowed surface.",
            "Restrict the source program to allowed types, or extend the policy only for trusted types.",
            false),
        new(Member, VerifierDiagnosticCategory.ForbiddenCapability,
            "A member reference or local call target is not allowed by policy.",
            "The source program called a method/field outside the allowed surface, or a non-static local target.",
            "Restrict the source program to allowed members; local calls must target static helpers.",
            false),
        new(CustomAttribute, VerifierDiagnosticCategory.ForbiddenCapability,
            "The generated assembly carries a custom attribute, which is not allowed.",
            "A non-DotBoxD.Kernels producer or source program attached attributes the verifier rejects.",
            "Remove custom attributes from the generated surface.",
            false),
        new(Resource, VerifierDiagnosticCategory.ForbiddenCapability,
            "The assembly embeds resources, which are not allowed.",
            "Embedded manifest resources were present in the artifact.",
            "Reject the artifact; generated modules must not embed resources.",
            false),
        new(PInvoke, VerifierDiagnosticCategory.ForbiddenCapability,
            "The assembly carries P/Invoke metadata, which is not allowed.",
            "ImplMap (P/Invoke) metadata was present.",
            "Reject the artifact; native interop is never allowed.",
            false),
        new(OpCode, VerifierDiagnosticCategory.ForbiddenCapability,
            "An IL opcode used in a method body is not on the allow-list or is explicitly forbidden.",
            "The source program or a tampered body used a disallowed opcode (for example calli, ldftn, ldtoken).",
            "Restrict the source program to the supported instruction set.",
            false),
        new(ControlFlow, VerifierDiagnosticCategory.MalformedArtifact,
            "A branch targets an offset that is not a valid instruction boundary.",
            "Corrupt or tampered control flow in a method body.",
            "Reject the artifact and re-produce it from source.",
            false),
        new(VerifierDiagnosticCodes.Exception, VerifierDiagnosticCategory.UnsupportedGeneratedShape,
            "A method body declares exception handlers, which are not allowed.",
            "The generated body used try/catch/finally regions.",
            "Reject the artifact; the canonical compiler does not emit exception regions.",
            false),
        new(VerifierDiagnosticCodes.Array, VerifierDiagnosticCategory.ForbiddenCapability,
            "An array allocation uses an element type other than the allowed DotBoxD.Kernels value type.",
            "The source program allocated arrays of a disallowed element type.",
            "Only allocate arrays of the supported DotBoxD.Kernels value type.",
            false),
        new(CompiledShape, VerifierDiagnosticCategory.UnsupportedGeneratedShape,
            "The compiled Execute/function shape does not match the required DotBoxD.Kernels dispatch shape.",
            "The generated method does not validate input and dispatch in the canonical metered shape.",
            "Re-produce with the canonical compiler; do not hand-edit generated dispatch bodies.",
            false),
        new(PublicSurface, VerifierDiagnosticCategory.UnsupportedGeneratedShape,
            "The public surface is wrong: extra types/methods, a missing Execute, or bad visibility/name.",
            "The generated assembly exposes more than the single canonical type with one public static Execute.",
            "Re-produce with the canonical compiler so the public surface matches exactly.",
            false),
        new(ModuleSurface, VerifierDiagnosticCategory.UnsupportedGeneratedShape,
            "Module-level (<Module>) methods or fields are present, which is not allowed.",
            "A non-canonical producer added global members.",
            "Reject the artifact; the canonical compiler emits no module-level members.",
            false),
        new(TypeShape, VerifierDiagnosticCategory.UnsupportedGeneratedShape,
            "The generated type is not a static (abstract+sealed) non-interface type.",
            "The generated type was declared as an instance type or interface.",
            "Re-produce with the canonical compiler so the generated type is static and sealed.",
            false),
        new(Field, VerifierDiagnosticCategory.UnsupportedGeneratedShape,
            "The generated type declares fields, which is not allowed.",
            "A non-canonical producer added fields to the generated type.",
            "Reject the artifact; generated types must be stateless.",
            false),
        new(FieldStatic, VerifierDiagnosticCategory.UnsupportedGeneratedShape,
            "The generated type declares a mutable static field, which is not allowed.",
            "A non-canonical producer added shared mutable state.",
            "Reject the artifact; static fields must be init-only or literal if present at all.",
            false),
        new(MethodSpecial, VerifierDiagnosticCategory.UnsupportedGeneratedShape,
            "A disallowed special method (such as .cctor or Finalize) is present.",
            "A non-canonical producer added a static constructor or finalizer.",
            "Reject the artifact; special methods are never emitted by the canonical compiler.",
            false),
        new(MethodPInvoke, VerifierDiagnosticCategory.ForbiddenCapability,
            "A method carries P/Invoke attributes.",
            "A method was marked for native interop.",
            "Reject the artifact; native interop is not allowed.",
            false),
        new(MethodBody, VerifierDiagnosticCategory.MalformedArtifact,
            "A generated executable method is missing its method body.",
            "An Execute or Fn_* method has no IL body.",
            "Reject the artifact and re-produce it from source.",
            false),
        new(MethodName, VerifierDiagnosticCategory.UnsupportedGeneratedShape,
            "A method name is not an expected generated method name.",
            "A non-canonical producer added unexpected methods.",
            "Re-produce with the canonical compiler so only expected method names are present.",
            false),
        new(MethodAttribute, VerifierDiagnosticCategory.UnsupportedGeneratedShape,
            "A method uses unsupported attributes (virtual/abstract/synchronized/native/internal-call/non-static).",
            "A non-canonical producer emitted methods with disallowed implementation or method attributes.",
            "Re-produce with the canonical compiler so methods are concrete, static, and managed.",
            false),
        new(ExecuteSignature, VerifierDiagnosticCategory.UnsupportedGeneratedShape,
            "The Execute method signature does not match the required DotBoxD.Kernels entrypoint signature.",
            "Execute does not match SandboxValue Execute(SandboxContext, SandboxValue).",
            "Re-produce with the canonical compiler so Execute matches the required signature.",
            false),
        new(FunctionSignature, VerifierDiagnosticCategory.UnsupportedGeneratedShape,
            "A generated Fn_* helper does not match the required DotBoxD.Kernels function signature.",
            "A Fn_* helper does not match SandboxValue Fn_*(SandboxContext, SandboxValue...).",
            "Re-produce with the canonical compiler so helper signatures match.",
            false),
        new(Generic, VerifierDiagnosticCategory.UnsupportedGeneratedShape,
            "The generated type or a method declares generic parameters, which are not allowed.",
            "A non-canonical producer emitted generic parameters.",
            "Reject the artifact; the canonical compiler emits no generics.",
            false),
        new(Stack, VerifierDiagnosticCategory.MalformedArtifact,
            "The operand stack underflowed, mismatched the signature, or branch heights are inconsistent.",
            "Corrupt, tampered, or non-canonical IL with an inconsistent operand stack.",
            "Reject the artifact and re-produce it from source.",
            false),
        new(StackType, VerifierDiagnosticCategory.MalformedArtifact,
            "A value on the operand stack has a type that is not allowed at that position.",
            "Non-canonical or tampered IL placed a disallowed type on the stack.",
            "Reject the artifact and re-produce it from source.",
            false),
        new(Operand, VerifierDiagnosticCategory.MalformedArtifact,
            "An argument or local operand index is out of range for the method.",
            "Tampered or non-canonical IL referenced an argument/local that does not exist.",
            "Reject the artifact and re-produce it from source.",
            false),
        new(MetadataShape, VerifierDiagnosticCategory.UnsupportedGeneratedShape,
            "A disallowed metadata table is present (interfaces, properties, events, nested types, layout, and similar).",
            "A non-canonical producer emitted metadata the generated shape never contains.",
            "Reject the artifact; re-produce it with the canonical compiler so only the supported metadata tables are present.",
            false),
        new(Security, VerifierDiagnosticCategory.ForbiddenCapability,
            "The assembly carries declarative security metadata, which is not allowed.",
            "DeclSecurity metadata was present in the artifact.",
            "Reject the artifact; declarative security is never emitted by the canonical compiler.",
            false),
    ];
}
