param(
    [int] $WarnAt = 300,
    [int] $FailAt = 350,
    [int] $MaxFilesPerFolder = 15,
    [int] $MaxFilesInProjectFolder = 5,
    # Ratcheting budget for soft-limit (CE0002, > $WarnAt lines) files. -1 reads
    # `maxSoftLimitViolations` from .config/code-enforcer/code-enforcer.json.
    [int] $MaxSoftLimitViolations = -1
)

$ErrorActionPreference = "Stop"

$root = [System.IO.Path]::GetFullPath([System.IO.Path]::Combine($PSScriptRoot, "../.."))
$justificationPath = [System.IO.Path]::Combine($root, ".config/code-enforcer/justifications.json")
$violations = [System.Collections.Generic.List[string]]::new()
$warnings = [System.Collections.Generic.List[string]]::new()

function Normalize-PathText([string] $path) {
    return $path.Replace("\", "/").Trim("/")
}

function Add-JsonJustifications(
    [System.Collections.Generic.HashSet[string]] $set,
    [System.Text.Json.JsonElement] $rootElement,
    [string] $arrayName,
    [string[]] $propertyNames) {
    $entries = [System.Text.Json.JsonElement]::new()
    if (-not $rootElement.TryGetProperty($arrayName, [ref] $entries) -or
        $entries.ValueKind -ne [System.Text.Json.JsonValueKind]::Array) {
        return
    }

    foreach ($entry in $entries.EnumerateArray()) {
        if ($entry.ValueKind -eq [System.Text.Json.JsonValueKind]::String) {
            $value = $entry.GetString()
            if (-not [string]::IsNullOrWhiteSpace($value)) {
                [void] $set.Add((Normalize-PathText $value))
            }

            continue
        }

        if ($entry.ValueKind -ne [System.Text.Json.JsonValueKind]::Object) {
            continue
        }

        foreach ($propertyName in $propertyNames) {
            $property = [System.Text.Json.JsonElement]::new()
            if ($entry.TryGetProperty($propertyName, [ref] $property) -and
                $property.ValueKind -eq [System.Text.Json.JsonValueKind]::String) {
                $value = $property.GetString()
                if (-not [string]::IsNullOrWhiteSpace($value)) {
                    [void] $set.Add((Normalize-PathText $value))
                    break
                }
            }
        }
    }
}

function Get-RepositoryCSharpFiles {
    $startInfo = [System.Diagnostics.ProcessStartInfo]::new()
    $startInfo.FileName = "git"
    $startInfo.UseShellExecute = $false
    $startInfo.RedirectStandardOutput = $true
    $startInfo.RedirectStandardError = $true
    [void] $startInfo.ArgumentList.Add("-C")
    [void] $startInfo.ArgumentList.Add($root)
    [void] $startInfo.ArgumentList.Add("ls-files")
    [void] $startInfo.ArgumentList.Add("--cached")
    [void] $startInfo.ArgumentList.Add("--others")
    [void] $startInfo.ArgumentList.Add("--exclude-standard")
    [void] $startInfo.ArgumentList.Add("--")
    [void] $startInfo.ArgumentList.Add("*.cs")

    $process = [System.Diagnostics.Process]::Start($startInfo)
    $gitOutput = $process.StandardOutput.ReadToEnd()
    $null = $process.StandardError.ReadToEnd()
    $process.WaitForExit()
    if ($process.ExitCode -eq 0 -and -not [string]::IsNullOrWhiteSpace($gitOutput)) {
        $result = [System.Collections.Generic.List[string]]::new()
        foreach ($file in ($gitOutput -split "\r?\n")) {
            if (-not [string]::IsNullOrWhiteSpace($file)) {
                $result.Add((Normalize-PathText $file))
            }
        }

        return $result.ToArray()
    }

    $fallback = [System.Collections.Generic.List[string]]::new()
    foreach ($file in [System.IO.Directory]::EnumerateFiles($root, "*.cs", [System.IO.SearchOption]::AllDirectories)) {
        if ($file -match "[\\/](bin|obj|\.git)[\\/]") {
            continue
        }

        $fallback.Add((Normalize-PathText ([System.IO.Path]::GetRelativePath($root, $file))))
    }

    return $fallback.ToArray()
}

function Test-GeneratedFile([string] $relativePath) {
    $name = [System.IO.Path]::GetFileName($relativePath)
    if ($name -match "\.(g|generated|designer)\.cs$") {
        return $true
    }

    $fullPath = [System.IO.Path]::Combine($root, $relativePath)
    if (-not [System.IO.File]::Exists($fullPath)) {
        return $true
    }

    $lineCount = 0
    foreach ($line in [System.IO.File]::ReadLines($fullPath)) {
        if ($line -match "<auto-generated") {
            return $true
        }

        $lineCount++
        if ($lineCount -ge 20) {
            break
        }
    }

    return $false
}

function Get-LineCount([string] $relativePath) {
    $count = 0
    foreach ($line in [System.IO.File]::ReadLines([System.IO.Path]::Combine($root, $relativePath))) {
        $count++
    }

    return $count
}

function Get-Folder([string] $relativePath) {
    $folder = [System.IO.Path]::GetDirectoryName($relativePath)
    if ([string]::IsNullOrWhiteSpace($folder)) {
        return "."
    }

    return Normalize-PathText $folder
}

$justifiedFiles = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
$justifiedFolders = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
$justifiedRootFolders = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)

if ([System.IO.File]::Exists($justificationPath)) {
    $justificationDocument = [System.Text.Json.JsonDocument]::Parse([System.IO.File]::ReadAllText($justificationPath))
    try {
        Add-JsonJustifications $justifiedFiles $justificationDocument.RootElement "files" @("path", "file")
        Add-JsonJustifications $justifiedFolders $justificationDocument.RootElement "folders" @("path", "folder")
        Add-JsonJustifications $justifiedRootFolders $justificationDocument.RootElement "rootFolders" @("path", "folder", "rootFolder")
    }
    finally {
        $justificationDocument.Dispose()
    }
}

$csharpFiles = @(Get-RepositoryCSharpFiles | Where-Object { -not (Test-GeneratedFile $_) })
$filesByFolder = @{}
foreach ($file in $csharpFiles) {
    $lineCount = Get-LineCount $file
    $hasJustification = $justifiedFiles.Contains($file)

    if ($lineCount -gt 500 -and -not $hasJustification) {
        $violations.Add("CE0003 $file has $lineCount lines and exceeds 500 lines without a justification.")
    }
    elseif ($lineCount -gt $FailAt -and -not $hasJustification) {
        $violations.Add("CE0001 $file has $lineCount lines, exceeding the hard limit of $FailAt.")
    }
    elseif ($lineCount -gt $WarnAt) {
        $warnings.Add("CE0002 $file has $lineCount lines, exceeding the soft limit of $WarnAt.")
    }

    $folder = Get-Folder $file
    if (-not $filesByFolder.ContainsKey($folder)) {
        $filesByFolder[$folder] = [System.Collections.Generic.List[string]]::new()
    }

    $filesByFolder[$folder].Add($file)
}

foreach ($folder in $filesByFolder.Keys) {
    $count = $filesByFolder[$folder].Count
    if ($count -gt $MaxFilesPerFolder -and -not $justifiedFolders.Contains($folder)) {
        $violations.Add("CE0004 $folder contains $count C# files, exceeding the folder limit of $MaxFilesPerFolder.")
    }
}

$projectFoldersSet = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
foreach ($projectFile in [System.IO.Directory]::EnumerateFiles($root, "*.csproj", [System.IO.SearchOption]::AllDirectories)) {
    if ($projectFile -match "[\\/](bin|obj|\.git)[\\/]") {
        continue
    }

    [void] $projectFoldersSet.Add((Normalize-PathText ([System.IO.Path]::GetRelativePath($root, [System.IO.Path]::GetDirectoryName($projectFile)))))
}

$projectFolders = [string[]]::new($projectFoldersSet.Count)
$projectFoldersSet.CopyTo($projectFolders)

foreach ($projectFolder in $projectFolders) {
    $count = if ($filesByFolder.ContainsKey($projectFolder)) { $filesByFolder[$projectFolder].Count } else { 0 }
    if ($count -gt $MaxFilesInProjectFolder -and -not $justifiedRootFolders.Contains($projectFolder)) {
        $violations.Add("CE0005 $projectFolder contains a .csproj and $count C# files, exceeding the project-folder limit of $MaxFilesInProjectFolder.")
    }
}

foreach ($warning in $warnings) {
    [System.Console]::Error.WriteLine("WARNING: $warning")
}

# Soft-limit budget: the count of files over the soft cap (CE0002) is a ratcheting
# budget. It may shrink but never grow, so a new oversized file forces a split or a
# deliberate budget bump instead of silently accumulating soft-limit debt.
$softLimitCount = $warnings.Count
$budget = $MaxSoftLimitViolations
if ($budget -lt 0) {
    $configPath = [System.IO.Path]::Combine($root, ".config/code-enforcer/code-enforcer.json")
    if ([System.IO.File]::Exists($configPath)) {
        $configDocument = [System.Text.Json.JsonDocument]::Parse([System.IO.File]::ReadAllText($configPath))
        try {
            $field = [System.Text.Json.JsonElement]::new()
            if ($configDocument.RootElement.TryGetProperty("maxSoftLimitViolations", [ref] $field) -and
                $field.ValueKind -eq [System.Text.Json.JsonValueKind]::Number) {
                $budget = $field.GetInt32()
            }
        }
        finally {
            $configDocument.Dispose()
        }
    }
}

if ($budget -ge 0) {
    if ($softLimitCount -gt $budget) {
        $violations.Add("CE0006 soft-limit budget exceeded: $softLimitCount file(s) over $WarnAt lines, budget is $budget. Split a file under $WarnAt lines, or deliberately raise maxSoftLimitViolations in .config/code-enforcer/code-enforcer.json.")
    }
    elseif ($softLimitCount -lt $budget) {
        [System.Console]::Out.WriteLine("CodeEnforcer: soft-limit count ($softLimitCount) is below the budget ($budget). Lower maxSoftLimitViolations in .config/code-enforcer/code-enforcer.json to lock in the improvement.")
    }
}

if ($violations.Count -gt 0) {
    foreach ($violation in $violations) {
        [System.Console]::Error.WriteLine($violation)
    }

    throw "CodeEnforcer found $($violations.Count) violation(s)."
}

[System.Console]::Out.WriteLine("CodeEnforcer passed.")
