param(
    [string] $Path = ".",
    [int] $MaxFilesInProjectRoot = 5,
    [int] $MaxFilesPerFolder = 15
)

$ErrorActionPreference = "Stop"

function Normalize-PathText([string] $path) {
    return $path.Replace("\", "/").Trim("/")
}

function Add-Justifications($set, $entries, [string[]] $propertyNames) {
    foreach ($entry in @($entries)) {
        if ($null -eq $entry) {
            continue
        }

        if ($entry -is [string]) {
            [void] $set.Add((Normalize-PathText $entry))
            continue
        }

        foreach ($propertyName in $propertyNames) {
            $property = $entry.PSObject.Properties[$propertyName]
            if ($null -ne $property -and -not [string]::IsNullOrWhiteSpace($property.Value)) {
                [void] $set.Add((Normalize-PathText ([string] $property.Value)))
                break
            }
        }
    }
}

function Test-GeneratedFile([string] $fullPath) {
    $name = [System.IO.Path]::GetFileName($fullPath)
    if ($name -match "\.(g|generated|designer)\.cs$") {
        return $true
    }

    $head = Get-Content -LiteralPath $fullPath -TotalCount 20
    return ($head -match "<auto-generated").Count -gt 0
}

function Get-Folder([string] $relativePath) {
    $folder = [System.IO.Path]::GetDirectoryName($relativePath)
    if ([string]::IsNullOrWhiteSpace($folder)) {
        return "."
    }

    return Normalize-PathText $folder
}

$scriptDirectory = Split-Path -Parent $PSCommandPath
$root = $scriptDirectory
while (-not (Test-Path -LiteralPath (Join-Path $root "DotBoxD.slnx"))) {
    $parent = Split-Path -Parent $root
    if ($parent -eq $root) {
        throw "Unable to locate repository root from $scriptDirectory."
    }

    $root = $parent
}

$justificationPath = Join-Path $root ".config/code-enforcer/justifications.json"
$justifiedFolders = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
$justifiedRootFolders = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
if (Test-Path -LiteralPath $justificationPath) {
    $justifications = Get-Content -Raw -LiteralPath $justificationPath | ConvertFrom-Json
    Add-Justifications $justifiedFolders $justifications.folders @("path", "folder")
    Add-Justifications $justifiedRootFolders $justifications.rootFolders @("path", "folder", "rootFolder")
}

if ([string]::IsNullOrWhiteSpace($Path) -or $Path -eq ".") {
    $scopePath = $root
    $relativeScope = "."
}
else {
    $scopePath = (Resolve-Path (Join-Path $root $Path)).Path
    $relativeScope = Normalize-PathText ([System.IO.Path]::GetRelativePath($root, $scopePath))
}
$violations = [System.Collections.Generic.List[string]]::new()

if ($relativeScope -eq ".") {
    $gitFiles = & git -C $root ls-files --cached --others --exclude-standard -- "*.cs"
}
else {
    $gitFiles = & git -C $root ls-files --cached --others --exclude-standard -- $relativeScope
}

if ($LASTEXITCODE -ne 0) {
    throw "Unable to enumerate repository files under $relativeScope."
}

$filesByFolder = @{}
foreach ($file in @($gitFiles)) {
    if (-not $file.EndsWith(".cs", [System.StringComparison]::OrdinalIgnoreCase)) {
        continue
    }

    $fullPath = Join-Path $root $file
    if (-not (Test-Path -LiteralPath $fullPath) -or (Test-GeneratedFile $fullPath)) {
        continue
    }

    $relativePath = Normalize-PathText $file
    $folder = Get-Folder $relativePath

    if (-not $filesByFolder.ContainsKey($folder)) {
        $filesByFolder[$folder] = [System.Collections.Generic.List[string]]::new()
    }

    $filesByFolder[$folder].Add($relativePath)
}

foreach ($folder in $filesByFolder.Keys) {
    $count = $filesByFolder[$folder].Count
    if ($count -gt $MaxFilesPerFolder -and -not $justifiedFolders.Contains($folder)) {
        $violations.Add("$folder contains $count C# files, exceeding the folder limit of $MaxFilesPerFolder.")
    }
}

$projectFolders = @(Get-ChildItem -LiteralPath $scopePath -Recurse -Filter "*.csproj" -File |
    Where-Object { $_.FullName -notmatch "\\(bin|obj|\.git)\\" } |
    ForEach-Object { Normalize-PathText ([System.IO.Path]::GetRelativePath($root, $_.DirectoryName)) } |
    Select-Object -Unique)

if ((Test-Path -LiteralPath $scopePath -PathType Container) -and
    (Get-ChildItem -LiteralPath $scopePath -Filter "*.csproj" -File | Select-Object -First 1)) {
    $projectFolders += $relativeScope
    $projectFolders = @($projectFolders | Select-Object -Unique)
}

foreach ($projectFolder in $projectFolders) {
    $count = if ($filesByFolder.ContainsKey($projectFolder)) { $filesByFolder[$projectFolder].Count } else { 0 }
    if ($count -gt $MaxFilesInProjectRoot -and -not $justifiedRootFolders.Contains($projectFolder)) {
        $violations.Add(
            "$projectFolder contains a .csproj and $count C# files, exceeding the project-root limit of $MaxFilesInProjectRoot.")
    }
}

if ($violations.Count -gt 0) {
    foreach ($violation in $violations) {
        Write-Error $violation -ErrorAction Continue
    }

    throw "C# folder layout check found $($violations.Count) violation(s)."
}

Write-Host "C# folder layout check passed for '$relativeScope'."
