param(
    [int] $WarnAt = 300,
    [int] $FailAt = 350,
    [int] $MaxFilesPerFolder = 15,
    [int] $MaxFilesInProjectFolder = 5,
    # Ratcheting budget for soft-limit (CE0002, > $WarnAt lines) files. -1 reads
    # `maxSoftLimitViolations` from .config/code-enforcer/code-enforcer.json.
    [int] $MaxSoftLimitViolations = -1,
    # Ratcheting budget for mechanical split files named *.Part*.cs. -1 reads
    # `maxPartFileCount` from .config/code-enforcer/code-enforcer.json.
    [int] $MaxPartFileCount = -1,
    # Ratcheting budget for non-generated source partial types that span multiple files.
    # -1 reads `maxSourceMultiFilePartialTypeCount` from .config/code-enforcer/code-enforcer.json.
    [int] $MaxSourceMultiFilePartialTypeCount = -1
)

$ErrorActionPreference = "Stop"

$root = [System.IO.Path]::GetFullPath([System.IO.Path]::Combine($PSScriptRoot, "../.."))
$justificationPath = [System.IO.Path]::Combine($root, ".config/code-enforcer/justifications.json")
$violations = [System.Collections.Generic.List[string]]::new()
$warnings = [System.Collections.Generic.List[string]]::new()

. ([System.IO.Path]::Combine($PSScriptRoot, "code-enforcer-csharp-scan.ps1"))

function Normalize-PathText([string] $path) {
    return $path.Replace("\", "/").Trim("/")
}

function Add-JsonJustifications(
    [System.Collections.Generic.HashSet[string]] $set,
    [System.Text.Json.JsonElement] $rootElement,
    [string] $arrayName,
    [string[]] $propertyNames) {
    $entries = [System.Text.Json.JsonElement]::new()
    if (-not $rootElement.TryGetProperty($arrayName, [ref] $entries) -or
        $entries.ValueKind -ne [System.Text.Json.JsonValueKind]::Array) {
        return
    }

    foreach ($entry in $entries.EnumerateArray()) {
        if ($entry.ValueKind -eq [System.Text.Json.JsonValueKind]::String) {
            $value = $entry.GetString()
            if (-not [string]::IsNullOrWhiteSpace($value)) {
                [void] $set.Add((Normalize-PathText $value))
            }

            continue
        }

        if ($entry.ValueKind -ne [System.Text.Json.JsonValueKind]::Object) {
            continue
        }

        foreach ($propertyName in $propertyNames) {
            $property = [System.Text.Json.JsonElement]::new()
            if ($entry.TryGetProperty($propertyName, [ref] $property) -and
                $property.ValueKind -eq [System.Text.Json.JsonValueKind]::String) {
                $value = $property.GetString()
                if (-not [string]::IsNullOrWhiteSpace($value)) {
                    [void] $set.Add((Normalize-PathText $value))
                    break
                }
            }
        }
    }
}

function Get-RepositoryCSharpFiles {
    $startInfo = [System.Diagnostics.ProcessStartInfo]::new()
    $startInfo.FileName = "git"
    $startInfo.UseShellExecute = $false
    $startInfo.RedirectStandardOutput = $true
    $startInfo.RedirectStandardError = $true
    [void] $startInfo.ArgumentList.Add("-C")
    [void] $startInfo.ArgumentList.Add($root)
    [void] $startInfo.ArgumentList.Add("ls-files")
    [void] $startInfo.ArgumentList.Add("--cached")
    [void] $startInfo.ArgumentList.Add("--others")
    [void] $startInfo.ArgumentList.Add("--exclude-standard")
    [void] $startInfo.ArgumentList.Add("--")
    [void] $startInfo.ArgumentList.Add("*.cs")

    $process = [System.Diagnostics.Process]::Start($startInfo)
    $gitOutput = $process.StandardOutput.ReadToEnd()
    $null = $process.StandardError.ReadToEnd()
    $process.WaitForExit()
    if ($process.ExitCode -eq 0 -and -not [string]::IsNullOrWhiteSpace($gitOutput)) {
        $result = [System.Collections.Generic.List[string]]::new()
        foreach ($file in ($gitOutput -split "\r?\n")) {
            if (-not [string]::IsNullOrWhiteSpace($file)) {
                $result.Add((Normalize-PathText $file))
            }
        }

        return $result.ToArray()
    }

    $fallback = [System.Collections.Generic.List[string]]::new()
    foreach ($file in [System.IO.Directory]::EnumerateFiles($root, "*.cs", [System.IO.SearchOption]::AllDirectories)) {
        if ($file -match "[\\/](bin|obj|\.git)[\\/]") {
            continue
        }

        $fallback.Add((Normalize-PathText ([System.IO.Path]::GetRelativePath($root, $file))))
    }

    return $fallback.ToArray()
}

function Test-GeneratedFile([string] $relativePath) {
    $name = [System.IO.Path]::GetFileName($relativePath)
    if ($name -match "\.(g|generated|designer)\.cs$") {
        return $true
    }

    $fullPath = [System.IO.Path]::Combine($root, $relativePath)
    if (-not [System.IO.File]::Exists($fullPath)) {
        return $true
    }

    $lineCount = 0
    foreach ($line in [System.IO.File]::ReadLines($fullPath)) {
        if ($line -match "<auto-generated") {
            return $true
        }

        $lineCount++
        if ($lineCount -ge 20) {
            break
        }
    }

    return $false
}

function Get-PartialTypeDeclarations([string] $relativePath) {
    $declarations = @{}
    $namespacePattern = '^\s*namespace\s+([A-Za-z_][A-Za-z0-9_.]*)\s*(;|\{)?'
    $typePattern = '^\s*(?:(?:public|internal|private|protected|sealed|static|abstract|readonly|ref|unsafe|partial)\s+)*partial\s+(?:class|interface|struct|record(?:\s+(?:class|struct))?)\s+([A-Za-z_][A-Za-z0-9_]*)(?:\s*<([^>{}]*)>)?\b'
    $fullPath = [System.IO.Path]::Combine($root, $relativePath)

    $containsPartial = $false
    foreach ($rawLine in [System.IO.File]::ReadLines($fullPath)) {
        if ($rawLine.Contains("partial", [StringComparison]::Ordinal)) {
            $containsPartial = $true
            break
        }
    }

    if (-not $containsPartial) {
        return [System.Collections.Generic.List[object]]::new()
    }

    $namespaceRegex = [System.Text.RegularExpressions.Regex]::new($namespacePattern)
    $typeRegex = [System.Text.RegularExpressions.Regex]::new($typePattern)
    $fileScopedNamespace = ""
    $namespaceScopes = [System.Collections.Generic.List[object]]::new()
    $pendingNamespace = $null
    $braceDepth = 0
    $inBlockComment = $false
    $inVerbatimString = $false
    $rawStringQuoteCount = 0

    foreach ($rawLine in [System.IO.File]::ReadLines($fullPath)) {
        $line = Get-CSharpLineForDeclarationScan `
            $rawLine `
            ([ref] $inBlockComment) `
            ([ref] $inVerbatimString) `
            ([ref] $rawStringQuoteCount)
        Pop-ClosedNamespaces $namespaceScopes $braceDepth

        $namespaceMatch = $namespaceRegex.Match($line)
        if ($namespaceMatch.Success) {
            $declaredNamespace = $namespaceMatch.Groups[1].Value
            $namespaceDelimiter = $namespaceMatch.Groups[2].Value

            if ($namespaceDelimiter -eq ";") {
                $fileScopedNamespace = $declaredNamespace
                $namespaceScopes.Clear()
                $pendingNamespace = $null
            }
            elseif ($line.Contains("{")) {
                $parentNamespace = Get-ActiveNamespace $namespaceScopes $fileScopedNamespace
                $namespaceScopes.Add([pscustomobject]@{
                        Name = Join-NamespaceName $parentNamespace $declaredNamespace
                        Depth = $braceDepth + 1
                    })
                $pendingNamespace = $null
            }
            else {
                $pendingNamespace = $declaredNamespace
            }
        }
        elseif ($null -ne $pendingNamespace -and $line.Contains("{")) {
            $parentNamespace = Get-ActiveNamespace $namespaceScopes $fileScopedNamespace
            $namespaceScopes.Add([pscustomobject]@{
                    Name = Join-NamespaceName $parentNamespace $pendingNamespace
                    Depth = $braceDepth + 1
                })
            $pendingNamespace = $null
        }

        $currentNamespace = Get-ActiveNamespace $namespaceScopes $fileScopedNamespace
        $match = $typeRegex.Match($line)
        if ($match.Success) {
            $typeName = $match.Groups[1].Value
            $genericParameters = $match.Groups[2].Value
            $arity = 0
            if (-not [string]::IsNullOrWhiteSpace($genericParameters)) {
                $arity = @($genericParameters -split "," | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }).Count
            }

            $key = if ([string]::IsNullOrWhiteSpace($currentNamespace)) {
                '{0}`{1}' -f $typeName, $arity
            }
            else {
                '{0}.{1}`{2}' -f $currentNamespace, $typeName, $arity
            }

            $displayName = if ([string]::IsNullOrWhiteSpace($currentNamespace)) { $typeName } else { "$currentNamespace.$typeName" }
            if ($arity -gt 0) {
                $displayName += "<" + (($genericParameters -split "," | ForEach-Object { $_.Trim() }) -join ", ") + ">"
            }

            $declarations[$key] = $displayName
        }

        $openBraces = $line.Length - $line.Replace("{", "").Length
        $closeBraces = $line.Length - $line.Replace("}", "").Length
        $braceDepth += $openBraces - $closeBraces
        if ($braceDepth -lt 0) {
            $braceDepth = 0
        }

        Pop-ClosedNamespaces $namespaceScopes $braceDepth
    }

    $result = [System.Collections.Generic.List[object]]::new()
    foreach ($key in $declarations.Keys) {
        $result.Add([pscustomobject]@{
                Key = $key
                DisplayName = $declarations[$key]
            })
    }

    return $result
}

function Get-LineCount([string] $relativePath) {
    $count = 0
    foreach ($line in [System.IO.File]::ReadLines([System.IO.Path]::Combine($root, $relativePath))) {
        $count++
    }

    return $count
}

function Get-Folder([string] $relativePath) {
    $folder = [System.IO.Path]::GetDirectoryName($relativePath)
    if ([string]::IsNullOrWhiteSpace($folder)) {
        return "."
    }

    return Normalize-PathText $folder
}

function Get-CodeEnforcerConfigInt([string] $propertyName, [int] $fallback) {
    $configPath = [System.IO.Path]::Combine($root, ".config/code-enforcer/code-enforcer.json")
    if (-not [System.IO.File]::Exists($configPath)) {
        return $fallback
    }

    $configDocument = [System.Text.Json.JsonDocument]::Parse([System.IO.File]::ReadAllText($configPath))
    try {
        $field = [System.Text.Json.JsonElement]::new()
        if ($configDocument.RootElement.TryGetProperty($propertyName, [ref] $field) -and
            $field.ValueKind -eq [System.Text.Json.JsonValueKind]::Number) {
            return $field.GetInt32()
        }
    }
    finally {
        $configDocument.Dispose()
    }

    return $fallback
}

$justifiedFiles = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
$justifiedFolders = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
$justifiedRootFolders = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)

if ([System.IO.File]::Exists($justificationPath)) {
    $justificationDocument = [System.Text.Json.JsonDocument]::Parse([System.IO.File]::ReadAllText($justificationPath))
    try {
        Add-JsonJustifications $justifiedFiles $justificationDocument.RootElement "files" @("path", "file")
        Add-JsonJustifications $justifiedFolders $justificationDocument.RootElement "folders" @("path", "folder")
        Add-JsonJustifications $justifiedRootFolders $justificationDocument.RootElement "rootFolders" @("path", "folder", "rootFolder")
    }
    finally {
        $justificationDocument.Dispose()
    }
}

$csharpFiles = @(Get-RepositoryCSharpFiles | Where-Object { -not (Test-GeneratedFile $_) })
$partFileBudget = $MaxPartFileCount
if ($partFileBudget -lt 0) {
    $partFileBudget = Get-CodeEnforcerConfigInt "maxPartFileCount" 0
}

$partFiles = @($csharpFiles | Where-Object { [System.IO.Path]::GetFileName($_) -match '(?i)\.Part\d+\.cs$' })
if ($partFiles.Count -gt $partFileBudget) {
    $sample = ($partFiles | Sort-Object | Select-Object -First 10) -join ", "
    $violations.Add("CE0007 mechanical partial split budget exceeded: $($partFiles.Count) file(s) named *.Part*.cs, budget is $partFileBudget. Rename/refactor split files around behavior or support types instead of Class.PartN.cs. Sample: $sample")
}
elseif ($partFiles.Count -lt $partFileBudget) {
    [System.Console]::Out.WriteLine("CodeEnforcer: *.Part*.cs count ($($partFiles.Count)) is below the budget ($partFileBudget). Lower maxPartFileCount in .config/code-enforcer/code-enforcer.json to lock in the improvement.")
}

$sourcePartialTypeBudget = $MaxSourceMultiFilePartialTypeCount
if ($sourcePartialTypeBudget -lt 0) {
    $sourcePartialTypeBudget = Get-CodeEnforcerConfigInt "maxSourceMultiFilePartialTypeCount" 0
}

$sourcePartialTypeFiles = @{}
foreach ($file in ($csharpFiles | Where-Object { $_ -like "src/*" })) {
    foreach ($declaration in (Get-PartialTypeDeclarations $file)) {
        if (-not $sourcePartialTypeFiles.ContainsKey($declaration.Key)) {
            $sourcePartialTypeFiles[$declaration.Key] = [pscustomobject]@{
                DisplayName = $declaration.DisplayName
                Files = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
            }
        }

        [void] $sourcePartialTypeFiles[$declaration.Key].Files.Add($file)
    }
}

$sourceMultiFilePartialTypes = [System.Collections.Generic.List[object]]::new()
foreach ($typeKey in $sourcePartialTypeFiles.Keys) {
    $entry = $sourcePartialTypeFiles[$typeKey]
    $fileCount = $entry.Files.Count
    if ($fileCount -gt 1) {
        $sourceMultiFilePartialTypes.Add([pscustomobject]@{
                TypeName = $entry.DisplayName
                FileCount = $fileCount
            })
    }
}

if ($sourceMultiFilePartialTypes.Count -gt $sourcePartialTypeBudget) {
    $sample = ($sourceMultiFilePartialTypes |
        Sort-Object -Property @{ Expression = "FileCount"; Descending = $true }, TypeName |
        Select-Object -First 10 |
        ForEach-Object { "$($_.TypeName) ($($_.FileCount) files)" }) -join ", "
    $violations.Add("CE0008 source multi-file partial type budget exceeded: $($sourceMultiFilePartialTypes.Count) type(s), budget is $sourcePartialTypeBudget. Extract collaborators or document and intentionally ratchet the budget. Sample: $sample")
}
elseif ($sourceMultiFilePartialTypes.Count -lt $sourcePartialTypeBudget) {
    [System.Console]::Out.WriteLine("CodeEnforcer: source multi-file partial type count ($($sourceMultiFilePartialTypes.Count)) is below the budget ($sourcePartialTypeBudget). Lower maxSourceMultiFilePartialTypeCount in .config/code-enforcer/code-enforcer.json to lock in the improvement.")
}

$filesByFolder = @{}
foreach ($file in $csharpFiles) {
    $lineCount = Get-LineCount $file
    $hasJustification = $justifiedFiles.Contains($file)

    if ($lineCount -gt 500 -and -not $hasJustification) {
        $violations.Add("CE0003 $file has $lineCount lines and exceeds 500 lines without a justification.")
    }
    elseif ($lineCount -gt $FailAt -and -not $hasJustification) {
        $violations.Add("CE0001 $file has $lineCount lines, exceeding the hard limit of $FailAt.")
    }
    elseif ($lineCount -gt $WarnAt) {
        $warnings.Add("CE0002 $file has $lineCount lines, exceeding the soft limit of $WarnAt.")
    }

    $folder = Get-Folder $file
    if (-not $filesByFolder.ContainsKey($folder)) {
        $filesByFolder[$folder] = [System.Collections.Generic.List[string]]::new()
    }

    $filesByFolder[$folder].Add($file)
}

foreach ($folder in $filesByFolder.Keys) {
    $count = $filesByFolder[$folder].Count
    if ($count -gt $MaxFilesPerFolder -and -not $justifiedFolders.Contains($folder)) {
        $violations.Add("CE0004 $folder contains $count C# files, exceeding the folder limit of $MaxFilesPerFolder.")
    }
}

$projectFoldersSet = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
foreach ($projectFile in [System.IO.Directory]::EnumerateFiles($root, "*.csproj", [System.IO.SearchOption]::AllDirectories)) {
    if ($projectFile -match "[\\/](bin|obj|\.git)[\\/]") {
        continue
    }

    [void] $projectFoldersSet.Add((Normalize-PathText ([System.IO.Path]::GetRelativePath($root, [System.IO.Path]::GetDirectoryName($projectFile)))))
}

$projectFolders = [string[]]::new($projectFoldersSet.Count)
$projectFoldersSet.CopyTo($projectFolders)

foreach ($projectFolder in $projectFolders) {
    $count = if ($filesByFolder.ContainsKey($projectFolder)) { $filesByFolder[$projectFolder].Count } else { 0 }
    if ($count -gt $MaxFilesInProjectFolder -and -not $justifiedRootFolders.Contains($projectFolder)) {
        $violations.Add("CE0005 $projectFolder contains a .csproj and $count C# files, exceeding the project-folder limit of $MaxFilesInProjectFolder.")
    }
}

foreach ($warning in $warnings) {
    [System.Console]::Error.WriteLine("WARNING: $warning")
}

# Soft-limit budget: the count of files over the soft cap (CE0002) is a ratcheting
# budget. It may shrink but never grow, so a new oversized file forces a split or a
# deliberate budget bump instead of silently accumulating soft-limit debt.
$softLimitCount = $warnings.Count
$budget = $MaxSoftLimitViolations
if ($budget -lt 0) {
    $budget = Get-CodeEnforcerConfigInt "maxSoftLimitViolations" $budget
}

if ($budget -ge 0) {
    if ($softLimitCount -gt $budget) {
        $violations.Add("CE0006 soft-limit budget exceeded: $softLimitCount file(s) over $WarnAt lines, budget is $budget. Split a file under $WarnAt lines, or deliberately raise maxSoftLimitViolations in .config/code-enforcer/code-enforcer.json.")
    }
    elseif ($softLimitCount -lt $budget) {
        [System.Console]::Out.WriteLine("CodeEnforcer: soft-limit count ($softLimitCount) is below the budget ($budget). Lower maxSoftLimitViolations in .config/code-enforcer/code-enforcer.json to lock in the improvement.")
    }
}

if ($violations.Count -gt 0) {
    foreach ($violation in $violations) {
        [System.Console]::Error.WriteLine($violation)
    }

    throw "CodeEnforcer found $($violations.Count) violation(s)."
}

[System.Console]::Out.WriteLine("CodeEnforcer passed.")
