//HintName: DotBoxdRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace DotBoxd.Services.Generated
{
    /// <summary>
    /// Extension methods for registering generated DotBoxd services.
    /// </summary>
    public static class DotBoxdGeneratedExtensions
    {

        /// <summary>
        /// Provides a IMix implementation for the other peer to call.
        /// </summary>
        public static global::DotBoxd.Services.RpcPeer ProvideMix(this global::DotBoxd.Services.RpcPeer peer, global::Snap.Mixed.IMix implementation)
            => peer.Provide((global::DotBoxd.Services.Server.IServiceDispatcher)new global::Snap.Mixed.MixDispatcher(implementation));

        /// <summary>
        /// Gets a proxy to call IMix on the other peer.
        /// </summary>
        public static global::Snap.Mixed.IMix GetMix(this global::DotBoxd.Services.RpcPeer peer)
            => new global::Snap.Mixed.MixProxy(peer);
    }
}
