//HintName: DotBoxDRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace DotBoxD.Services.Generated
{
    /// <summary>
    /// Extension methods for registering generated DotBoxD services.
    /// </summary>
    public static class DotBoxDGeneratedExtensions
    {

        /// <summary>
        /// Provides a IHello implementation for the other peer to call.
        /// </summary>
        public static global::DotBoxD.Services.Peer.RpcPeer ProvideHello(this global::DotBoxD.Services.Peer.RpcPeer peer, global::Snap.Renamed.IHello implementation)
        {
            if (peer is null)
            {
                throw new global::System.ArgumentNullException(nameof(peer));
            }

            if (implementation is null)
            {
                throw new global::System.ArgumentNullException(nameof(implementation));
            }

            peer.Provide((global::DotBoxD.Services.Server.IServiceDispatcher)new global::Snap.Renamed.HelloDispatcher(implementation));
            return peer;
        }

        /// <summary>
        /// Gets a proxy to call IHello on the other peer.
        /// </summary>
        public static global::Snap.Renamed.IHello GetHello(this global::DotBoxD.Services.Peer.RpcPeer peer)
        {
            if (peer is null)
            {
                throw new global::System.ArgumentNullException(nameof(peer));
            }

            return peer.Get<global::Snap.Renamed.IHello>();
        }
    }
}
