//HintName: Snap_Nested_IRootSnap.DotBoxdRpcAsync.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Nested
{
    /// <summary>
    /// Auto-generated async sibling of <see cref="IRootSnap"/>. Use this
    /// interface from callers that must not block on RPC calls.
    /// </summary>
    public interface IRootSnapAsync
    {
        global::System.Threading.Tasks.Task<global::Snap.Nested.ISubSnap> GetSubAsync(string label, global::System.Threading.CancellationToken ct = default);
    }
}
