//HintName: DotBoxDGenerated.g.cs
// <auto-generated />
#nullable enable

namespace DotBoxD.Services.Generated
{
    /// <summary>
    /// Factory methods for DotBoxD-generated proxies and dispatchers.
    /// </summary>
    internal static class DotBoxDGenerated
    {
        private static readonly global::DotBoxD.Services.Generated.GeneratedMethod[] s_service0Methods =
        {
            new global::DotBoxD.Services.Generated.GeneratedMethod(
                "GoodAsync",
                "GoodAsync",
                typeof(global::System.Threading.Tasks.Task<int>),
                typeof(int),
                global::DotBoxD.Services.Generated.GeneratedReturnKind.TaskOfT,
                false,
                new global::DotBoxD.Services.Generated.GeneratedParameter[]
                {
                    new global::DotBoxD.Services.Generated.GeneratedParameter(
                        "a",
                        typeof(int),
                        0,
                        false,
                        false,
                        null),
                }),
        };

        private static readonly global::DotBoxD.Services.Generated.GeneratedService[] s_services =
        {
            new global::DotBoxD.Services.Generated.GeneratedService(
                typeof(global::Snap.RefOut.IRefOutSnap),
                typeof(global::Snap.RefOut.RefOutSnapProxy),
                typeof(global::Snap.RefOut.RefOutSnapDispatcher),
                "IRefOutSnap",
                s_service0Methods),
        };

        static DotBoxDGenerated()
        {
            global::DotBoxD.Services.Generated.GeneratedServiceRegistry.RegisterServices(
                typeof(global::DotBoxD.Services.Generated.DotBoxDGenerated).Assembly,
                s_services);
            global::DotBoxD.Services.Generated.GeneratedServiceRegistry.Register<global::Snap.RefOut.IRefOutSnap>(
                static client => new global::Snap.RefOut.RefOutSnapProxy(client),
                static implementation => new global::Snap.RefOut.RefOutSnapDispatcher((global::Snap.RefOut.IRefOutSnap)implementation),
                s_services[0]);
        }

        /// <summary>
        /// Gets the services generated into this assembly without scanning for generated types.
        /// </summary>
        public static global::System.Collections.Generic.IReadOnlyList<global::DotBoxD.Services.Generated.GeneratedService> Services
            => s_services;

        /// <summary>
        /// Adds generated service proxy registrations to <paramref name="sink" /> without scanning generated types.
        /// </summary>
        public static void RegisterServices(global::DotBoxD.Services.Generated.IDotBoxDServiceRegistrationSink sink)
        {
            if (sink is null)
            {
                throw new global::System.ArgumentNullException(nameof(sink));
            }

            sink.AddService<global::Snap.RefOut.IRefOutSnap, global::Snap.RefOut.RefOutSnapProxy>();
        }

        /// <summary>
        /// Adds generated service proxy and dispatcher registrations to <paramref name="sink" /> without scanning generated types.
        /// </summary>
        public static void RegisterGeneratedServices(global::DotBoxD.Services.Generated.IDotBoxDGeneratedServiceRegistrationSink sink)
        {
            if (sink is null)
            {
                throw new global::System.ArgumentNullException(nameof(sink));
            }

            sink.AddService<global::Snap.RefOut.IRefOutSnap, global::Snap.RefOut.RefOutSnapProxy, global::Snap.RefOut.RefOutSnapDispatcher>();
        }

        /// <summary>
        /// Creates the generated proxy for <typeparamref name="TService" /> over an invoker.
        /// </summary>
        public static TService CreateProxy<TService>(global::DotBoxD.Services.Server.IRpcInvoker invoker)
            where TService : class
            => global::DotBoxD.Services.Generated.GeneratedServiceRegistry.CreateProxy<TService>(invoker);

        /// <summary>
        /// Creates the generated proxy for <paramref name="serviceInterface" /> over an invoker.
        /// </summary>
        public static object CreateProxy(global::System.Type serviceInterface, global::DotBoxD.Services.Server.IRpcInvoker invoker)
            => global::DotBoxD.Services.Generated.GeneratedServiceRegistry.CreateProxy(serviceInterface, invoker);

        /// <summary>
        /// Creates the generated server dispatcher for <paramref name="implementation" />.
        /// </summary>
        public static global::DotBoxD.Services.Server.IServiceDispatcher CreateDispatcher<TService>(TService implementation)
            where TService : class
            => global::DotBoxD.Services.Generated.GeneratedServiceRegistry.CreateDispatcher<TService>(implementation);

        /// <summary>
        /// Creates the generated server dispatcher for <paramref name="implementation" />.
        /// </summary>
        public static global::DotBoxD.Services.Server.IServiceDispatcher CreateDispatcher(global::System.Type serviceInterface, object implementation)
            => global::DotBoxD.Services.Generated.GeneratedServiceRegistry.CreateDispatcher(serviceInterface, implementation);
    }
}
