//HintName: DotBoxDRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace DotBoxD.Services.Generated
{
    /// <summary>
    /// Extension methods for registering generated DotBoxD services.
    /// </summary>
    public static class DotBoxDGeneratedExtensions
    {

        /// <summary>
        /// Provides a IRefOutSnap implementation for the other peer to call.
        /// </summary>
        public static global::DotBoxD.Services.Peer.RpcPeer ProvideRefOutSnap(this global::DotBoxD.Services.Peer.RpcPeer peer, global::Snap.RefOut.IRefOutSnap implementation)
        {
            if (peer is null)
            {
                throw new global::System.ArgumentNullException(nameof(peer));
            }

            if (implementation is null)
            {
                throw new global::System.ArgumentNullException(nameof(implementation));
            }

            peer.Provide((global::DotBoxD.Services.Server.IServiceDispatcher)new global::Snap.RefOut.RefOutSnapDispatcher(implementation));
            return peer;
        }

        /// <summary>
        /// Gets a proxy to call IRefOutSnap on the other peer.
        /// </summary>
        public static global::Snap.RefOut.IRefOutSnap GetRefOutSnap(this global::DotBoxD.Services.Peer.RpcPeer peer)
        {
            if (peer is null)
            {
                throw new global::System.ArgumentNullException(nameof(peer));
            }

            return peer.Get<global::Snap.RefOut.IRefOutSnap>();
        }
    }
}
