//HintName: DotBoxdRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace DotBoxd.Services.Generated
{
    /// <summary>
    /// Extension methods for registering generated DotBoxd services.
    /// </summary>
    public static class DotBoxdGeneratedExtensions
    {

        /// <summary>
        /// Provides a IHello implementation for the other peer to call.
        /// </summary>
        public static global::DotBoxd.Services.RpcPeer ProvideHello(this global::DotBoxd.Services.RpcPeer peer, global::Snap.Renamed.IHello implementation)
            => peer.Provide((global::DotBoxd.Services.Server.IServiceDispatcher)new global::Snap.Renamed.HelloDispatcher(implementation));

        /// <summary>
        /// Gets a proxy to call IHello on the other peer.
        /// </summary>
        public static global::Snap.Renamed.IHello GetHello(this global::DotBoxd.Services.RpcPeer peer)
            => new global::Snap.Renamed.HelloProxy(peer);
    }
}
