//HintName: Snap_Two_IOne.DotBoxdRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Two
{
    /// <summary>
    /// Client proxy for IOne.
    /// </summary>
    public sealed class OneProxy : global::Snap.Two.IOne, global::Snap.Two.IOneAsync
    {
        private readonly global::DotBoxd.Services.IRpcInvoker _invoker;
        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>
        private readonly string? _instanceId;

        public OneProxy(global::DotBoxd.Services.IRpcInvoker client)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = null;
        }

        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>
        public OneProxy(global::DotBoxd.Services.IRpcInvoker client, string instanceId)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = instanceId ?? throw new global::System.ArgumentNullException(nameof(instanceId));
        }

        public global::System.Threading.Tasks.Task<int> AAsync(int x)
        {
            try
            {
                return (this._instanceId is null ? this._invoker.InvokeAsync<int, int>("IOne", "AAsync", x, default) : this._invoker.InvokeOnInstanceAsync<int, int>("IOne", this._instanceId!, "AAsync", x, default));
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled<int>(__dotboxd_canceled.CancellationToken);
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return global::System.Threading.Tasks.Task.FromException<int>(__dotboxd_ex);
            }
        }

        public global::System.Threading.Tasks.Task<int> AAsync(int x, global::System.Threading.CancellationToken ct = default)
        {
            try
            {
                return (this._instanceId is null ? this._invoker.InvokeAsync<int, int>("IOne", "AAsync", x, ct) : this._invoker.InvokeOnInstanceAsync<int, int>("IOne", this._instanceId!, "AAsync", x, ct));
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled<int>(__dotboxd_canceled.CancellationToken);
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return global::System.Threading.Tasks.Task.FromException<int>(__dotboxd_ex);
            }
        }
    }
}
