//HintName: DotBoxdRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace DotBoxd.Services.Generated
{
    /// <summary>
    /// Extension methods for registering generated DotBoxd services.
    /// </summary>
    public static class DotBoxdGeneratedExtensions
    {

        /// <summary>
        /// Provides a IOne implementation for the other peer to call.
        /// </summary>
        public static global::DotBoxd.Services.RpcPeer ProvideOne(this global::DotBoxd.Services.RpcPeer peer, global::Snap.Two.IOne implementation)
            => peer.Provide((global::DotBoxd.Services.Server.IServiceDispatcher)new global::Snap.Two.OneDispatcher(implementation));

        /// <summary>
        /// Gets a proxy to call IOne on the other peer.
        /// </summary>
        public static global::Snap.Two.IOne GetOne(this global::DotBoxd.Services.RpcPeer peer)
            => new global::Snap.Two.OneProxy(peer);

        /// <summary>
        /// Provides a ITwo implementation for the other peer to call.
        /// </summary>
        public static global::DotBoxd.Services.RpcPeer ProvideTwo(this global::DotBoxd.Services.RpcPeer peer, global::Snap.Two.ITwo implementation)
            => peer.Provide((global::DotBoxd.Services.Server.IServiceDispatcher)new global::Snap.Two.TwoDispatcher(implementation));

        /// <summary>
        /// Gets a proxy to call ITwo on the other peer.
        /// </summary>
        public static global::Snap.Two.ITwo GetTwo(this global::DotBoxd.Services.RpcPeer peer)
            => new global::Snap.Two.TwoProxy(peer);
    }
}
