//HintName: DotBoxdGenerated.g.cs
// <auto-generated />
#nullable enable

namespace DotBoxd.Services.Generated
{
    /// <summary>
    /// Factory methods for DotBoxd-generated proxies and dispatchers.
    /// </summary>
    public static class DotBoxdGenerated
    {
        private static readonly global::DotBoxd.Services.Generated.DotBoxdGeneratedMethod[] s_service0Methods =
        {
            new global::DotBoxd.Services.Generated.DotBoxdGeneratedMethod(
                "AddAsync",
                "AddAsync",
                typeof(global::System.Threading.Tasks.ValueTask<int>),
                typeof(int),
                global::DotBoxd.Services.Generated.DotBoxdGeneratedReturnKind.ValueTaskOfT,
                false,
                new global::DotBoxd.Services.Generated.DotBoxdGeneratedParameter[]
                {
                    new global::DotBoxd.Services.Generated.DotBoxdGeneratedParameter(
                        "a",
                        typeof(int),
                        0,
                        false,
                        false,
                        null),
                    new global::DotBoxd.Services.Generated.DotBoxdGeneratedParameter(
                        "b",
                        typeof(int),
                        1,
                        false,
                        false,
                        null),
                }),
            new global::DotBoxd.Services.Generated.DotBoxdGeneratedMethod(
                "PingAsync",
                "PingAsync",
                typeof(global::System.Threading.Tasks.ValueTask),
                null,
                global::DotBoxd.Services.Generated.DotBoxdGeneratedReturnKind.ValueTask,
                false,
                new global::DotBoxd.Services.Generated.DotBoxdGeneratedParameter[]
                {
                }),
        };

        private static readonly global::DotBoxd.Services.Generated.DotBoxdGeneratedService[] s_services =
        {
            new global::DotBoxd.Services.Generated.DotBoxdGeneratedService(
                typeof(global::Snap.Vt.IVtSnap),
                typeof(global::Snap.Vt.VtSnapProxy),
                typeof(global::Snap.Vt.VtSnapDispatcher),
                "IVtSnap",
                s_service0Methods),
        };

        static DotBoxdGenerated()
        {
            global::DotBoxd.Services.Generated.DotBoxdServiceRegistry.RegisterServices(
                typeof(global::DotBoxd.Services.Generated.DotBoxdGenerated).Assembly,
                s_services);
            global::DotBoxd.Services.Generated.DotBoxdServiceRegistry.Register<global::Snap.Vt.IVtSnap>(
                static client => new global::Snap.Vt.VtSnapProxy(client),
                static implementation => new global::Snap.Vt.VtSnapDispatcher((global::Snap.Vt.IVtSnap)implementation),
                s_services[0]);
        }

        /// <summary>
        /// Gets the services generated into this assembly without scanning for generated types.
        /// </summary>
        public static global::System.Collections.Generic.IReadOnlyList<global::DotBoxd.Services.Generated.DotBoxdGeneratedService> Services
            => s_services;

        /// <summary>
        /// Adds generated service proxy registrations to <paramref name="sink" /> without scanning generated types.
        /// </summary>
        public static void RegisterServices(global::DotBoxd.Services.Generated.IDotBoxdServiceRegistrationSink sink)
        {
            if (sink is null)
            {
                throw new global::System.ArgumentNullException(nameof(sink));
            }

            sink.AddService<global::Snap.Vt.IVtSnap, global::Snap.Vt.VtSnapProxy>();
        }

        /// <summary>
        /// Adds generated service proxy and dispatcher registrations to <paramref name="sink" /> without scanning generated types.
        /// </summary>
        public static void RegisterGeneratedServices(global::DotBoxd.Services.Generated.IDotBoxdGeneratedServiceRegistrationSink sink)
        {
            if (sink is null)
            {
                throw new global::System.ArgumentNullException(nameof(sink));
            }

            sink.AddService<global::Snap.Vt.IVtSnap, global::Snap.Vt.VtSnapProxy, global::Snap.Vt.VtSnapDispatcher>();
        }

        /// <summary>
        /// Creates the generated proxy for <typeparamref name="TService" /> over an invoker.
        /// </summary>
        public static TService CreateProxy<TService>(global::DotBoxd.Services.IRpcInvoker invoker)
            where TService : class
            => global::DotBoxd.Services.Generated.DotBoxdServiceRegistry.CreateProxy<TService>(invoker);

        /// <summary>
        /// Creates the generated proxy for <paramref name="serviceInterface" /> over an invoker.
        /// </summary>
        public static object CreateProxy(global::System.Type serviceInterface, global::DotBoxd.Services.IRpcInvoker invoker)
            => global::DotBoxd.Services.Generated.DotBoxdServiceRegistry.CreateProxy(serviceInterface, invoker);

        /// <summary>
        /// Creates the generated server dispatcher for <paramref name="implementation" />.
        /// </summary>
        public static global::DotBoxd.Services.Server.IServiceDispatcher CreateDispatcher<TService>(TService implementation)
            where TService : class
            => global::DotBoxd.Services.Generated.DotBoxdServiceRegistry.CreateDispatcher<TService>(implementation);

        /// <summary>
        /// Creates the generated server dispatcher for <paramref name="implementation" />.
        /// </summary>
        public static global::DotBoxd.Services.Server.IServiceDispatcher CreateDispatcher(global::System.Type serviceInterface, object implementation)
            => global::DotBoxd.Services.Generated.DotBoxdServiceRegistry.CreateDispatcher(serviceInterface, implementation);
    }
}
