//HintName: Snap_Nested_ISubSnap.DotBoxdRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Nested
{
    /// <summary>
    /// Client proxy for ISubSnap.
    /// </summary>
    public sealed class SubSnapProxy : global::Snap.Nested.ISubSnap, global::Snap.Nested.ISubSnapAsync
    {
        private readonly global::DotBoxd.Services.IRpcInvoker _invoker;
        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>
        private readonly string? _instanceId;

        public SubSnapProxy(global::DotBoxd.Services.IRpcInvoker client)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = null;
        }

        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>
        public SubSnapProxy(global::DotBoxd.Services.IRpcInvoker client, string instanceId)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = instanceId ?? throw new global::System.ArgumentNullException(nameof(instanceId));
        }

        public global::System.Threading.Tasks.Task<int> CountAsync()
        {
            try
            {
                return (this._instanceId is null ? this._invoker.InvokeAsync<int>("ISubSnap", "CountAsync", default) : this._invoker.InvokeOnInstanceAsync<int>("ISubSnap", this._instanceId!, "CountAsync", default));
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled<int>(__dotboxd_canceled.CancellationToken);
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return global::System.Threading.Tasks.Task.FromException<int>(__dotboxd_ex);
            }
        }

        public global::System.Threading.Tasks.Task<int> CountAsync(global::System.Threading.CancellationToken ct = default)
        {
            try
            {
                return (this._instanceId is null ? this._invoker.InvokeAsync<int>("ISubSnap", "CountAsync", ct) : this._invoker.InvokeOnInstanceAsync<int>("ISubSnap", this._instanceId!, "CountAsync", ct));
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled<int>(__dotboxd_canceled.CancellationToken);
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return global::System.Threading.Tasks.Task.FromException<int>(__dotboxd_ex);
            }
        }
    }
}
