//HintName: DotBoxDRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace DotBoxD.Services.Generated
{
    /// <summary>
    /// Extension methods for registering generated DotBoxD services.
    /// </summary>
    public static class DotBoxDGeneratedExtensions
    {

        /// <summary>
        /// Provides a IMix implementation for the other peer to call.
        /// </summary>
        public static global::DotBoxD.Services.Peer.RpcPeer ProvideMix(this global::DotBoxD.Services.Peer.RpcPeer peer, global::Snap.Mixed.IMix implementation)
            => peer.Provide((global::DotBoxD.Services.Server.IServiceDispatcher)new global::Snap.Mixed.MixDispatcher(implementation));

        /// <summary>
        /// Gets a proxy to call IMix on the other peer.
        /// </summary>
        public static global::Snap.Mixed.IMix GetMix(this global::DotBoxD.Services.Peer.RpcPeer peer)
            => peer.Get<global::Snap.Mixed.IMix>();
    }
}
