//HintName: DotBoxdRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace DotBoxd.Services.Generated
{
    /// <summary>
    /// Extension methods for registering generated DotBoxd services.
    /// </summary>
    public static class DotBoxdGeneratedExtensions
    {

        /// <summary>
        /// Provides a ICalculator implementation for the other peer to call.
        /// </summary>
        public static global::DotBoxd.Services.RpcPeer ProvideCalculator(this global::DotBoxd.Services.RpcPeer peer, global::Snap.One.ICalculator implementation)
            => peer.Provide((global::DotBoxd.Services.Server.IServiceDispatcher)new global::Snap.One.CalculatorDispatcher(implementation));

        /// <summary>
        /// Gets a proxy to call ICalculator on the other peer.
        /// </summary>
        public static global::Snap.One.ICalculator GetCalculator(this global::DotBoxd.Services.RpcPeer peer)
            => new global::Snap.One.CalculatorProxy(peer);
    }
}
