//HintName: Snap_Inherit_IDerived.DotBoxDRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Inherit
{
    /// <summary>
    /// Client proxy for IDerived.
    /// </summary>
    public sealed class DerivedProxy : global::Snap.Inherit.IDerived, global::Snap.Inherit.IDerivedAsync
    {
        private readonly global::DotBoxD.Services.Server.IRpcInvoker _invoker;
        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>
        private readonly string? _instanceId;

        public DerivedProxy(global::DotBoxD.Services.Server.IRpcInvoker client)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = null;
        }

        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>
        public DerivedProxy(global::DotBoxD.Services.Server.IRpcInvoker client, string instanceId)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = instanceId ?? throw new global::System.ArgumentNullException(nameof(instanceId));
        }

        public global::System.Threading.Tasks.Task<string> DerivedAsync()
        {
            try
            {
                return (this._instanceId is null ? this._invoker.InvokeAsync<string>("IDerived", "DerivedAsync", default) : this._invoker.InvokeOnInstanceAsync<string>("IDerived", this._instanceId!, "DerivedAsync", default));
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled<string>(__dotboxd_canceled.CancellationToken);
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return global::System.Threading.Tasks.Task.FromException<string>(__dotboxd_ex);
            }
        }

        public global::System.Threading.Tasks.Task<int> BaseAsync(int x)
        {
            try
            {
                return (this._instanceId is null ? this._invoker.InvokeAsync<int, int>("IDerived", "BaseAsync", x, default) : this._invoker.InvokeOnInstanceAsync<int, int>("IDerived", this._instanceId!, "BaseAsync", x, default));
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled<int>(__dotboxd_canceled.CancellationToken);
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return global::System.Threading.Tasks.Task.FromException<int>(__dotboxd_ex);
            }
        }

        public global::System.Threading.Tasks.Task<string> DerivedAsync(global::System.Threading.CancellationToken ct = default)
        {
            try
            {
                return __dotboxd_observeCallerCancellationAsync((this._instanceId is null ? this._invoker.InvokeAsync<string>("IDerived", "DerivedAsync", ct) : this._invoker.InvokeOnInstanceAsync<string>("IDerived", this._instanceId!, "DerivedAsync", ct)), ct);
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested || ct.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled<string>(__dotboxd_canceled.CancellationToken.IsCancellationRequested ? __dotboxd_canceled.CancellationToken : ct);
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return global::System.Threading.Tasks.Task.FromException<string>(__dotboxd_ex);
            }
        }

        public global::System.Threading.Tasks.Task<int> BaseAsync(int x, global::System.Threading.CancellationToken ct = default)
        {
            try
            {
                return __dotboxd_observeCallerCancellationAsync((this._instanceId is null ? this._invoker.InvokeAsync<int, int>("IDerived", "BaseAsync", x, ct) : this._invoker.InvokeOnInstanceAsync<int, int>("IDerived", this._instanceId!, "BaseAsync", x, ct)), ct);
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested || ct.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled<int>(__dotboxd_canceled.CancellationToken.IsCancellationRequested ? __dotboxd_canceled.CancellationToken : ct);
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return global::System.Threading.Tasks.Task.FromException<int>(__dotboxd_ex);
            }
        }

        private static async global::System.Threading.Tasks.Task __dotboxd_observeCallerCancellationAsync(global::System.Threading.Tasks.Task task, global::System.Threading.CancellationToken ct)
        {
            await task.ConfigureAwait(false);
            ct.ThrowIfCancellationRequested();
        }

        private static async global::System.Threading.Tasks.Task<T> __dotboxd_observeCallerCancellationAsync<T>(global::System.Threading.Tasks.Task<T> task, global::System.Threading.CancellationToken ct)
        {
            var result = await task.ConfigureAwait(false);
            ct.ThrowIfCancellationRequested();
            return result;
        }

        private static async global::System.Threading.Tasks.ValueTask __dotboxd_observeCallerCancellationAsync(global::System.Threading.Tasks.ValueTask task, global::System.Threading.CancellationToken ct)
        {
            await task.ConfigureAwait(false);
            ct.ThrowIfCancellationRequested();
        }

        private static async global::System.Threading.Tasks.ValueTask<T> __dotboxd_observeCallerCancellationAsync<T>(global::System.Threading.Tasks.ValueTask<T> task, global::System.Threading.CancellationToken ct)
        {
            var result = await task.ConfigureAwait(false);
            ct.ThrowIfCancellationRequested();
            return result;
        }
    }
}
