//HintName: DotBoxDRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace DotBoxD.Services.Generated
{
    /// <summary>
    /// Extension methods for registering generated DotBoxD services.
    /// </summary>
    public static class DotBoxDGeneratedExtensions
    {

        /// <summary>
        /// Provides a IKwSnap implementation for the other peer to call.
        /// </summary>
        public static global::DotBoxD.Services.Peer.RpcPeer ProvideKwSnap(this global::DotBoxD.Services.Peer.RpcPeer peer, global::Snap.Kw.IKwSnap implementation)
            => peer.Provide((global::DotBoxD.Services.Server.IServiceDispatcher)new global::Snap.Kw.KwSnapDispatcher(implementation));

        /// <summary>
        /// Gets a proxy to call IKwSnap on the other peer.
        /// </summary>
        public static global::Snap.Kw.IKwSnap GetKwSnap(this global::DotBoxD.Services.Peer.RpcPeer peer)
            => peer.Get<global::Snap.Kw.IKwSnap>();
    }
}
