//HintName: Snap_Kw_IKwSnap.DotBoxDRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Kw
{
    /// <summary>
    /// Client proxy for IKwSnap.
    /// </summary>
    public sealed class KwSnapProxy : global::Snap.Kw.IKwSnap, global::Snap.Kw.IKwSnapAsync
    {
        private readonly global::DotBoxD.Services.Server.IRpcInvoker _invoker;
        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>
        private readonly string? _instanceId;

        public KwSnapProxy(global::DotBoxD.Services.Server.IRpcInvoker client)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = null;
        }

        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>
        public KwSnapProxy(global::DotBoxD.Services.Server.IRpcInvoker client, string instanceId)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = instanceId ?? throw new global::System.ArgumentNullException(nameof(instanceId));
        }

        public global::System.Threading.Tasks.Task<int> DoAsync(int @class, int @default)
        {
            try
            {
                return (this._instanceId is null ? this._invoker.InvokeAsync<(int, int), int>("IKwSnap", "DoAsync", (@class, @default), default) : this._invoker.InvokeOnInstanceAsync<(int, int), int>("IKwSnap", this._instanceId!, "DoAsync", (@class, @default), default));
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled<int>(__dotboxd_canceled.CancellationToken);
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return global::System.Threading.Tasks.Task.FromException<int>(__dotboxd_ex);
            }
        }

        public global::System.Threading.Tasks.Task<int> DoAsync(int @class, int @default, global::System.Threading.CancellationToken ct = default)
        {
            try
            {
                return __dotboxd_observeCallerCancellationAsync((this._instanceId is null ? this._invoker.InvokeAsync<(int, int), int>("IKwSnap", "DoAsync", (@class, @default), ct) : this._invoker.InvokeOnInstanceAsync<(int, int), int>("IKwSnap", this._instanceId!, "DoAsync", (@class, @default), ct)), ct);
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested || ct.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled<int>(__dotboxd_canceled.CancellationToken.IsCancellationRequested ? __dotboxd_canceled.CancellationToken : ct);
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return global::System.Threading.Tasks.Task.FromException<int>(__dotboxd_ex);
            }
        }

        private static async global::System.Threading.Tasks.Task __dotboxd_observeCallerCancellationAsync(global::System.Threading.Tasks.Task task, global::System.Threading.CancellationToken ct)
        {
            await task.ConfigureAwait(false);
            ct.ThrowIfCancellationRequested();
        }

        private static async global::System.Threading.Tasks.Task<T> __dotboxd_observeCallerCancellationAsync<T>(global::System.Threading.Tasks.Task<T> task, global::System.Threading.CancellationToken ct)
        {
            var result = await task.ConfigureAwait(false);
            ct.ThrowIfCancellationRequested();
            return result;
        }

        private static async global::System.Threading.Tasks.ValueTask __dotboxd_observeCallerCancellationAsync(global::System.Threading.Tasks.ValueTask task, global::System.Threading.CancellationToken ct)
        {
            await task.ConfigureAwait(false);
            ct.ThrowIfCancellationRequested();
        }

        private static async global::System.Threading.Tasks.ValueTask<T> __dotboxd_observeCallerCancellationAsync<T>(global::System.Threading.Tasks.ValueTask<T> task, global::System.Threading.CancellationToken ct)
        {
            var result = await task.ConfigureAwait(false);
            ct.ThrowIfCancellationRequested();
            return result;
        }
    }
}
