//HintName: Snap_Mixed_IMix.DotBoxDRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Mixed
{
    /// <summary>
    /// Client proxy for IMix.
    /// </summary>
    public sealed class MixProxy : global::Snap.Mixed.IMix, global::Snap.Mixed.IMixAsync
    {
        private readonly global::DotBoxD.Services.Server.IRpcInvoker _invoker;
        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>
        private readonly string? _instanceId;

        public MixProxy(global::DotBoxD.Services.Server.IRpcInvoker client)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = null;
        }

        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>
        public MixProxy(global::DotBoxD.Services.Server.IRpcInvoker client, string instanceId)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = instanceId ?? throw new global::System.ArgumentNullException(nameof(instanceId));
        }

        public global::System.Threading.Tasks.Task<string> GetNameAsync()
        {
            try
            {
                return (this._instanceId is null ? this._invoker.InvokeAsync<string>("IMix", "GetNameAsync", default) : this._invoker.InvokeOnInstanceAsync<string>("IMix", this._instanceId!, "GetNameAsync", default));
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled<string>(__dotboxd_canceled.CancellationToken);
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return global::System.Threading.Tasks.Task.FromException<string>(__dotboxd_ex);
            }
        }

        public global::System.Threading.Tasks.Task SaveAsync(string value)
        {
            try
            {
                return (this._instanceId is null ? this._invoker.InvokeAsync<string>("IMix", "SaveAsync", value, default) : this._invoker.InvokeOnInstanceAsync<string>("IMix", this._instanceId!, "SaveAsync", value, default));
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled(__dotboxd_canceled.CancellationToken);
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return global::System.Threading.Tasks.Task.FromException(__dotboxd_ex);
            }
        }

        public int SyncAdd(int a, int b)
        {
            return (this._instanceId is null ? this._invoker.InvokeAsync<(int, int), int>("IMix", "SyncAdd", (a, b), default) : this._invoker.InvokeOnInstanceAsync<(int, int), int>("IMix", this._instanceId!, "SyncAdd", (a, b), default)).GetAwaiter().GetResult();
        }

        public void SyncPing()
        {
            (this._instanceId is null ? this._invoker.InvokeAsync("IMix", "SyncPing", default) : this._invoker.InvokeOnInstanceAsync("IMix", this._instanceId!, "SyncPing", default)).GetAwaiter().GetResult();
        }

        public global::System.Threading.Tasks.Task<string> GetNameAsync(global::System.Threading.CancellationToken ct = default)
        {
            try
            {
                return __dotboxd_observeCallerCancellationAsync((this._instanceId is null ? this._invoker.InvokeAsync<string>("IMix", "GetNameAsync", ct) : this._invoker.InvokeOnInstanceAsync<string>("IMix", this._instanceId!, "GetNameAsync", ct)), ct);
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested || ct.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled<string>(__dotboxd_canceled.CancellationToken.IsCancellationRequested ? __dotboxd_canceled.CancellationToken : ct);
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return global::System.Threading.Tasks.Task.FromException<string>(__dotboxd_ex);
            }
        }

        public global::System.Threading.Tasks.Task SaveAsync(string value, global::System.Threading.CancellationToken ct = default)
        {
            try
            {
                return __dotboxd_observeCallerCancellationAsync((this._instanceId is null ? this._invoker.InvokeAsync<string>("IMix", "SaveAsync", value, ct) : this._invoker.InvokeOnInstanceAsync<string>("IMix", this._instanceId!, "SaveAsync", value, ct)), ct);
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested || ct.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled(__dotboxd_canceled.CancellationToken.IsCancellationRequested ? __dotboxd_canceled.CancellationToken : ct);
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return global::System.Threading.Tasks.Task.FromException(__dotboxd_ex);
            }
        }

        public global::System.Threading.Tasks.Task<int> SyncAddAsync(int a, int b, global::System.Threading.CancellationToken ct = default)
        {
            try
            {
                return __dotboxd_observeCallerCancellationAsync((this._instanceId is null ? this._invoker.InvokeAsync<(int, int), int>("IMix", "SyncAdd", (a, b), ct) : this._invoker.InvokeOnInstanceAsync<(int, int), int>("IMix", this._instanceId!, "SyncAdd", (a, b), ct)), ct);
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested || ct.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled<int>(__dotboxd_canceled.CancellationToken.IsCancellationRequested ? __dotboxd_canceled.CancellationToken : ct);
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return global::System.Threading.Tasks.Task.FromException<int>(__dotboxd_ex);
            }
        }

        public global::System.Threading.Tasks.Task SyncPingAsync(global::System.Threading.CancellationToken ct = default)
        {
            try
            {
                return __dotboxd_observeCallerCancellationAsync((this._instanceId is null ? this._invoker.InvokeAsync("IMix", "SyncPing", ct) : this._invoker.InvokeOnInstanceAsync("IMix", this._instanceId!, "SyncPing", ct)), ct);
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested || ct.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled(__dotboxd_canceled.CancellationToken.IsCancellationRequested ? __dotboxd_canceled.CancellationToken : ct);
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return global::System.Threading.Tasks.Task.FromException(__dotboxd_ex);
            }
        }

        private static global::System.Threading.Tasks.Task __dotboxd_observeCallerCancellationAsync(global::System.Threading.Tasks.Task task, global::System.Threading.CancellationToken ct)
        {
            return !ct.CanBeCanceled ? task : __dotboxd_observeCallerCancellationCoreAsync(task, ct);
        }

        private static async global::System.Threading.Tasks.Task __dotboxd_observeCallerCancellationCoreAsync(global::System.Threading.Tasks.Task task, global::System.Threading.CancellationToken ct)
        {
            await task.ConfigureAwait(false);
            ct.ThrowIfCancellationRequested();
        }

        private static global::System.Threading.Tasks.Task<T> __dotboxd_observeCallerCancellationAsync<T>(global::System.Threading.Tasks.Task<T> task, global::System.Threading.CancellationToken ct)
        {
            return !ct.CanBeCanceled ? task : __dotboxd_observeCallerCancellationCoreAsync(task, ct);
        }

        private static async global::System.Threading.Tasks.Task<T> __dotboxd_observeCallerCancellationCoreAsync<T>(global::System.Threading.Tasks.Task<T> task, global::System.Threading.CancellationToken ct)
        {
            var result = await task.ConfigureAwait(false);
            ct.ThrowIfCancellationRequested();
            return result;
        }

        private static global::System.Threading.Tasks.ValueTask __dotboxd_observeCallerCancellationAsync(global::System.Threading.Tasks.ValueTask task, global::System.Threading.CancellationToken ct)
        {
            return !ct.CanBeCanceled ? task : __dotboxd_observeCallerCancellationCoreAsync(task, ct);
        }

        private static async global::System.Threading.Tasks.ValueTask __dotboxd_observeCallerCancellationCoreAsync(global::System.Threading.Tasks.ValueTask task, global::System.Threading.CancellationToken ct)
        {
            await task.ConfigureAwait(false);
            ct.ThrowIfCancellationRequested();
        }

        private static global::System.Threading.Tasks.ValueTask<T> __dotboxd_observeCallerCancellationAsync<T>(global::System.Threading.Tasks.ValueTask<T> task, global::System.Threading.CancellationToken ct)
        {
            return !ct.CanBeCanceled ? task : __dotboxd_observeCallerCancellationCoreAsync(task, ct);
        }

        private static async global::System.Threading.Tasks.ValueTask<T> __dotboxd_observeCallerCancellationCoreAsync<T>(global::System.Threading.Tasks.ValueTask<T> task, global::System.Threading.CancellationToken ct)
        {
            var result = await task.ConfigureAwait(false);
            ct.ThrowIfCancellationRequested();
            return result;
        }
    }
}
