//HintName: Snap_Vt_IVtSnap.DotBoxdRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Vt
{
    /// <summary>
    /// Client proxy for IVtSnap.
    /// </summary>
    public sealed class VtSnapProxy : global::Snap.Vt.IVtSnap, global::Snap.Vt.IVtSnapAsync
    {
        private readonly global::DotBoxd.Services.IRpcInvoker _invoker;
        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>
        private readonly string? _instanceId;

        public VtSnapProxy(global::DotBoxd.Services.IRpcInvoker client)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = null;
        }

        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>
        public VtSnapProxy(global::DotBoxd.Services.IRpcInvoker client, string instanceId)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = instanceId ?? throw new global::System.ArgumentNullException(nameof(instanceId));
        }

        public global::System.Threading.Tasks.ValueTask<int> AddAsync(int a, int b)
        {
            try
            {
                return (this._instanceId is null ? this._invoker.InvokeValueAsync<(int, int), int>("IVtSnap", "AddAsync", (a, b), default) : this._invoker.InvokeValueOnInstanceAsync<(int, int), int>("IVtSnap", this._instanceId!, "AddAsync", (a, b), default));
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested)
            {
                return new global::System.Threading.Tasks.ValueTask<int>(global::System.Threading.Tasks.Task.FromCanceled<int>(__dotboxd_canceled.CancellationToken));
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return new global::System.Threading.Tasks.ValueTask<int>(global::System.Threading.Tasks.Task.FromException<int>(__dotboxd_ex));
            }
        }

        public global::System.Threading.Tasks.ValueTask PingAsync()
        {
            try
            {
                return new global::System.Threading.Tasks.ValueTask((this._instanceId is null ? this._invoker.InvokeAsync("IVtSnap", "PingAsync", default) : this._invoker.InvokeOnInstanceAsync("IVtSnap", this._instanceId!, "PingAsync", default)));
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested)
            {
                return new global::System.Threading.Tasks.ValueTask(global::System.Threading.Tasks.Task.FromCanceled(__dotboxd_canceled.CancellationToken));
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return new global::System.Threading.Tasks.ValueTask(global::System.Threading.Tasks.Task.FromException(__dotboxd_ex));
            }
        }

        public global::System.Threading.Tasks.ValueTask<int> AddAsync(int a, int b, global::System.Threading.CancellationToken ct = default)
        {
            try
            {
                return (this._instanceId is null ? this._invoker.InvokeValueAsync<(int, int), int>("IVtSnap", "AddAsync", (a, b), ct) : this._invoker.InvokeValueOnInstanceAsync<(int, int), int>("IVtSnap", this._instanceId!, "AddAsync", (a, b), ct));
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested)
            {
                return new global::System.Threading.Tasks.ValueTask<int>(global::System.Threading.Tasks.Task.FromCanceled<int>(__dotboxd_canceled.CancellationToken));
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return new global::System.Threading.Tasks.ValueTask<int>(global::System.Threading.Tasks.Task.FromException<int>(__dotboxd_ex));
            }
        }

        public global::System.Threading.Tasks.ValueTask PingAsync(global::System.Threading.CancellationToken ct = default)
        {
            try
            {
                return new global::System.Threading.Tasks.ValueTask((this._instanceId is null ? this._invoker.InvokeAsync("IVtSnap", "PingAsync", ct) : this._invoker.InvokeOnInstanceAsync("IVtSnap", this._instanceId!, "PingAsync", ct)));
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested)
            {
                return new global::System.Threading.Tasks.ValueTask(global::System.Threading.Tasks.Task.FromCanceled(__dotboxd_canceled.CancellationToken));
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return new global::System.Threading.Tasks.ValueTask(global::System.Threading.Tasks.Task.FromException(__dotboxd_ex));
            }
        }
    }
}
