//HintName: Snap_Mixed_IMix.DotBoxDRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Mixed
{
    /// <summary>
    /// Server dispatcher for IMix.
    /// </summary>
    public sealed class MixDispatcher : global::DotBoxD.Services.Server.IServiceDispatcher, global::DotBoxD.Services.Server.INonStreamingServiceDispatcher
    {
        private readonly global::Snap.Mixed.IMix? _service;

        public MixDispatcher()
        {
        }

        public MixDispatcher(global::Snap.Mixed.IMix service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "IMix";

        public global::System.Threading.Tasks.Task DispatchAsync(string method, global::System.ReadOnlyMemory<byte> payload, global::DotBoxD.Services.Serialization.ISerializer serializer, global::DotBoxD.Services.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default) =>
            DispatchAsync(method, payload, serializer, registry, output, global::DotBoxD.Services.Streaming.Remote.RpcStreamingContext.Disabled, ct);

        public global::System.Threading.Tasks.Task DispatchAsync(string method, global::System.ReadOnlyMemory<byte> payload, global::DotBoxD.Services.Serialization.ISerializer serializer, global::DotBoxD.Services.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::DotBoxD.Services.Streaming.Remote.IRpcStreamingContext streaming, global::System.Threading.CancellationToken ct = default)
        {
            if (_service is null)
            {
                throw new global::DotBoxD.Services.Exceptions.ServiceNotFoundException("Service 'IMix' can only dispatch instance calls.", global::DotBoxD.Services.Exceptions.ServiceNotFoundException.NotFoundKind.Service);
            }

            return DispatchCoreAsync(_service, method, payload, serializer, registry, output, streaming, ct);
        }

        public global::System.Threading.Tasks.Task DispatchOnInstanceAsync(string instanceId, string method, global::System.ReadOnlyMemory<byte> payload, global::DotBoxD.Services.Serialization.ISerializer serializer, global::DotBoxD.Services.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default) =>
            DispatchOnInstanceAsync(instanceId, method, payload, serializer, registry, output, global::DotBoxD.Services.Streaming.Remote.RpcStreamingContext.Disabled, ct);

        public global::System.Threading.Tasks.Task DispatchOnInstanceAsync(string instanceId, string method, global::System.ReadOnlyMemory<byte> payload, global::DotBoxD.Services.Serialization.ISerializer serializer, global::DotBoxD.Services.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::DotBoxD.Services.Streaming.Remote.IRpcStreamingContext streaming, global::System.Threading.CancellationToken ct = default)
        {
            if (!registry.TryGet("IMix", instanceId, out var __obj) || __obj is not global::Snap.Mixed.IMix __inst)
            {
                throw new global::DotBoxD.Services.Exceptions.ServiceNotFoundException("Instance '" + instanceId + "' not found for service 'IMix'.", global::DotBoxD.Services.Exceptions.ServiceNotFoundException.NotFoundKind.Instance);
            }

            return DispatchCoreAsync(__inst, method, payload, serializer, registry, output, streaming, ct);
        }

#pragma warning disable CS1998
        private async global::System.Threading.Tasks.Task DispatchCoreAsync(global::Snap.Mixed.IMix receiver, string method, global::System.ReadOnlyMemory<byte> payload, global::DotBoxD.Services.Serialization.ISerializer serializer, global::DotBoxD.Services.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::DotBoxD.Services.Streaming.Remote.IRpcStreamingContext streaming, global::System.Threading.CancellationToken ct)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "GetNameAsync":
                {
                    if (payload.Length != 0)
                    {
                        throw new global::DotBoxD.Services.Exceptions.ServiceProtocolException("Request payload is not allowed for a parameterless RPC method.");
                    }
                    var __dotboxd_task = receiver.GetNameAsync();
                    var __dotboxd_result = __dotboxd_task.IsCompletedSuccessfully
                        ? __dotboxd_task.Result
                        : await __dotboxd_task;
                    serializer.Serialize(output, __dotboxd_result);
                    return;
                }
                case "SaveAsync":
                {
                    var arg = serializer.Deserialize<string>(payload);
                    var __dotboxd_task = receiver.SaveAsync(arg);
                    if (!__dotboxd_task.IsCompletedSuccessfully)
                    {
                        await __dotboxd_task;
                    }
                    return;
                }
                case "SyncAdd":
                {
                    var args = serializer.Deserialize<(int, int)>(payload);
                    var result = receiver.SyncAdd(args.Item1, args.Item2);
                    serializer.Serialize(output, result);
                    return;
                }
                case "SyncPing":
                {
                    if (payload.Length != 0)
                    {
                        throw new global::DotBoxD.Services.Exceptions.ServiceProtocolException("Request payload is not allowed for a parameterless RPC method.");
                    }
                    receiver.SyncPing();
                    return;
                }
                default:
                    throw new global::DotBoxD.Services.Exceptions.ServiceNotFoundException("Method '" + method + "' not found on service 'IMix'.", global::DotBoxD.Services.Exceptions.ServiceNotFoundException.NotFoundKind.Method);
            }
        }
    }
}
