//HintName: Snap_One_ICalculator.DotBoxDRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.One
{
    /// <summary>
    /// Server dispatcher for ICalculator.
    /// </summary>
    public sealed class CalculatorDispatcher : global::DotBoxD.Services.Server.IServiceDispatcher, global::DotBoxD.Services.Server.INonStreamingServiceDispatcher
    {
        private readonly global::Snap.One.ICalculator? _service;

        public CalculatorDispatcher()
        {
        }

        public CalculatorDispatcher(global::Snap.One.ICalculator service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "ICalculator";

        public global::System.Threading.Tasks.Task DispatchAsync(string method, global::System.ReadOnlyMemory<byte> payload, global::DotBoxD.Services.Serialization.ISerializer serializer, global::DotBoxD.Services.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default) =>
            DispatchAsync(method, payload, serializer, registry, output, global::DotBoxD.Services.Streaming.Remote.RpcStreamingContext.Disabled, ct);

        public global::System.Threading.Tasks.Task DispatchAsync(string method, global::System.ReadOnlyMemory<byte> payload, global::DotBoxD.Services.Serialization.ISerializer serializer, global::DotBoxD.Services.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::DotBoxD.Services.Streaming.Remote.IRpcStreamingContext streaming, global::System.Threading.CancellationToken ct = default)
        {
            if (_service is null)
            {
                throw new global::DotBoxD.Services.Exceptions.ServiceNotFoundException("Service 'ICalculator' can only dispatch instance calls.", global::DotBoxD.Services.Exceptions.ServiceNotFoundException.NotFoundKind.Service);
            }

            return DispatchCoreAsync(_service, method, payload, serializer, registry, output, streaming, ct);
        }

        public global::System.Threading.Tasks.Task DispatchOnInstanceAsync(string instanceId, string method, global::System.ReadOnlyMemory<byte> payload, global::DotBoxD.Services.Serialization.ISerializer serializer, global::DotBoxD.Services.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default) =>
            DispatchOnInstanceAsync(instanceId, method, payload, serializer, registry, output, global::DotBoxD.Services.Streaming.Remote.RpcStreamingContext.Disabled, ct);

        public global::System.Threading.Tasks.Task DispatchOnInstanceAsync(string instanceId, string method, global::System.ReadOnlyMemory<byte> payload, global::DotBoxD.Services.Serialization.ISerializer serializer, global::DotBoxD.Services.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::DotBoxD.Services.Streaming.Remote.IRpcStreamingContext streaming, global::System.Threading.CancellationToken ct = default)
        {
            if (!registry.TryGet("ICalculator", instanceId, out var __obj) || __obj is not global::Snap.One.ICalculator __inst)
            {
                throw new global::DotBoxD.Services.Exceptions.ServiceNotFoundException("Instance '" + instanceId + "' not found for service 'ICalculator'.", global::DotBoxD.Services.Exceptions.ServiceNotFoundException.NotFoundKind.Instance);
            }

            return DispatchCoreAsync(__inst, method, payload, serializer, registry, output, streaming, ct);
        }

#pragma warning disable CS1998
        private async global::System.Threading.Tasks.Task DispatchCoreAsync(global::Snap.One.ICalculator receiver, string method, global::System.ReadOnlyMemory<byte> payload, global::DotBoxD.Services.Serialization.ISerializer serializer, global::DotBoxD.Services.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::DotBoxD.Services.Streaming.Remote.IRpcStreamingContext streaming, global::System.Threading.CancellationToken ct)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "AddAsync":
                {
                    var args = serializer.Deserialize<(int, int)>(payload);
                    var __dotboxd_task = receiver.AddAsync(args.Item1, args.Item2);
                    var __dotboxd_result = __dotboxd_task.IsCompletedSuccessfully
                        ? __dotboxd_task.Result
                        : await __dotboxd_task;
                    serializer.Serialize(output, __dotboxd_result);
                    return;
                }
                default:
                    throw new global::DotBoxD.Services.Exceptions.ServiceNotFoundException("Method '" + method + "' not found on service 'ICalculator'.", global::DotBoxD.Services.Exceptions.ServiceNotFoundException.NotFoundKind.Method);
            }
        }
    }
}
