//HintName: DotBoxDGenerated.g.cs
// <auto-generated />
#nullable enable

namespace DotBoxD.Services.Generated
{
    /// <summary>
    /// Factory methods for DotBoxD-generated proxies and dispatchers.
    /// </summary>
    public static class DotBoxDGenerated
    {
        private static readonly global::DotBoxD.Services.Generated.DotBoxDGeneratedMethod[] s_service0Methods =
        {
            new global::DotBoxD.Services.Generated.DotBoxDGeneratedMethod(
                "AAsync",
                "AAsync",
                typeof(global::System.Threading.Tasks.Task<int>),
                typeof(int),
                global::DotBoxD.Services.Generated.DotBoxDGeneratedReturnKind.TaskOfT,
                false,
                new global::DotBoxD.Services.Generated.DotBoxDGeneratedParameter[]
                {
                    new global::DotBoxD.Services.Generated.DotBoxDGeneratedParameter(
                        "x",
                        typeof(int),
                        0,
                        false,
                        false,
                        null),
                }),
        };

        private static readonly global::DotBoxD.Services.Generated.DotBoxDGeneratedMethod[] s_service1Methods =
        {
            new global::DotBoxD.Services.Generated.DotBoxDGeneratedMethod(
                "BAsync",
                "BAsync",
                typeof(global::System.Threading.Tasks.Task<string>),
                typeof(string),
                global::DotBoxD.Services.Generated.DotBoxDGeneratedReturnKind.TaskOfT,
                false,
                new global::DotBoxD.Services.Generated.DotBoxDGeneratedParameter[]
                {
                }),
        };

        private static readonly global::DotBoxD.Services.Generated.DotBoxDGeneratedService[] s_services =
        {
            new global::DotBoxD.Services.Generated.DotBoxDGeneratedService(
                typeof(global::Snap.Two.IOne),
                typeof(global::Snap.Two.OneProxy),
                typeof(global::Snap.Two.OneDispatcher),
                "IOne",
                s_service0Methods),
            new global::DotBoxD.Services.Generated.DotBoxDGeneratedService(
                typeof(global::Snap.Two.ITwo),
                typeof(global::Snap.Two.TwoProxy),
                typeof(global::Snap.Two.TwoDispatcher),
                "ITwo",
                s_service1Methods),
        };

        static DotBoxDGenerated()
        {
            global::DotBoxD.Services.Generated.DotBoxDServiceRegistry.RegisterServices(
                typeof(global::DotBoxD.Services.Generated.DotBoxDGenerated).Assembly,
                s_services);
            global::DotBoxD.Services.Generated.DotBoxDServiceRegistry.Register<global::Snap.Two.IOne>(
                static client => new global::Snap.Two.OneProxy(client),
                static implementation => new global::Snap.Two.OneDispatcher((global::Snap.Two.IOne)implementation),
                s_services[0]);
            global::DotBoxD.Services.Generated.DotBoxDServiceRegistry.Register<global::Snap.Two.ITwo>(
                static client => new global::Snap.Two.TwoProxy(client),
                static implementation => new global::Snap.Two.TwoDispatcher((global::Snap.Two.ITwo)implementation),
                s_services[1]);
        }

        /// <summary>
        /// Gets the services generated into this assembly without scanning for generated types.
        /// </summary>
        public static global::System.Collections.Generic.IReadOnlyList<global::DotBoxD.Services.Generated.DotBoxDGeneratedService> Services
            => s_services;

        /// <summary>
        /// Adds generated service proxy registrations to <paramref name="sink" /> without scanning generated types.
        /// </summary>
        public static void RegisterServices(global::DotBoxD.Services.Generated.IDotBoxDServiceRegistrationSink sink)
        {
            if (sink is null)
            {
                throw new global::System.ArgumentNullException(nameof(sink));
            }

            sink.AddService<global::Snap.Two.IOne, global::Snap.Two.OneProxy>();
            sink.AddService<global::Snap.Two.ITwo, global::Snap.Two.TwoProxy>();
        }

        /// <summary>
        /// Adds generated service proxy and dispatcher registrations to <paramref name="sink" /> without scanning generated types.
        /// </summary>
        public static void RegisterGeneratedServices(global::DotBoxD.Services.Generated.IDotBoxDGeneratedServiceRegistrationSink sink)
        {
            if (sink is null)
            {
                throw new global::System.ArgumentNullException(nameof(sink));
            }

            sink.AddService<global::Snap.Two.IOne, global::Snap.Two.OneProxy, global::Snap.Two.OneDispatcher>();
            sink.AddService<global::Snap.Two.ITwo, global::Snap.Two.TwoProxy, global::Snap.Two.TwoDispatcher>();
        }

        /// <summary>
        /// Creates the generated proxy for <typeparamref name="TService" /> over an invoker.
        /// </summary>
        public static TService CreateProxy<TService>(global::DotBoxD.Services.IRpcInvoker invoker)
            where TService : class
            => global::DotBoxD.Services.Generated.DotBoxDServiceRegistry.CreateProxy<TService>(invoker);

        /// <summary>
        /// Creates the generated proxy for <paramref name="serviceInterface" /> over an invoker.
        /// </summary>
        public static object CreateProxy(global::System.Type serviceInterface, global::DotBoxD.Services.IRpcInvoker invoker)
            => global::DotBoxD.Services.Generated.DotBoxDServiceRegistry.CreateProxy(serviceInterface, invoker);

        /// <summary>
        /// Creates the generated server dispatcher for <paramref name="implementation" />.
        /// </summary>
        public static global::DotBoxD.Services.Server.IServiceDispatcher CreateDispatcher<TService>(TService implementation)
            where TService : class
            => global::DotBoxD.Services.Generated.DotBoxDServiceRegistry.CreateDispatcher<TService>(implementation);

        /// <summary>
        /// Creates the generated server dispatcher for <paramref name="implementation" />.
        /// </summary>
        public static global::DotBoxD.Services.Server.IServiceDispatcher CreateDispatcher(global::System.Type serviceInterface, object implementation)
            => global::DotBoxD.Services.Generated.DotBoxDServiceRegistry.CreateDispatcher(serviceInterface, implementation);
    }
}
