//HintName: DotBoxdGenerated.g.cs
// <auto-generated />
#nullable enable

namespace DotBoxd.Services.Generated
{
    /// <summary>
    /// Factory methods for DotBoxd-generated proxies and dispatchers.
    /// </summary>
    public static class DotBoxdGenerated
    {
        private static readonly global::DotBoxd.Services.Generated.DotBoxdGeneratedMethod[] s_service0Methods =
        {
            new global::DotBoxd.Services.Generated.DotBoxdGeneratedMethod(
                "AAsync",
                "AAsync",
                typeof(global::System.Threading.Tasks.Task<int>),
                typeof(int),
                global::DotBoxd.Services.Generated.DotBoxdGeneratedReturnKind.TaskOfT,
                false,
                new global::DotBoxd.Services.Generated.DotBoxdGeneratedParameter[]
                {
                    new global::DotBoxd.Services.Generated.DotBoxdGeneratedParameter(
                        "x",
                        typeof(int),
                        0,
                        false,
                        false,
                        null),
                }),
        };

        private static readonly global::DotBoxd.Services.Generated.DotBoxdGeneratedMethod[] s_service1Methods =
        {
            new global::DotBoxd.Services.Generated.DotBoxdGeneratedMethod(
                "BAsync",
                "BAsync",
                typeof(global::System.Threading.Tasks.Task<string>),
                typeof(string),
                global::DotBoxd.Services.Generated.DotBoxdGeneratedReturnKind.TaskOfT,
                false,
                new global::DotBoxd.Services.Generated.DotBoxdGeneratedParameter[]
                {
                }),
        };

        private static readonly global::DotBoxd.Services.Generated.DotBoxdGeneratedService[] s_services =
        {
            new global::DotBoxd.Services.Generated.DotBoxdGeneratedService(
                typeof(global::Snap.Two.IOne),
                typeof(global::Snap.Two.OneProxy),
                typeof(global::Snap.Two.OneDispatcher),
                "IOne",
                s_service0Methods),
            new global::DotBoxd.Services.Generated.DotBoxdGeneratedService(
                typeof(global::Snap.Two.ITwo),
                typeof(global::Snap.Two.TwoProxy),
                typeof(global::Snap.Two.TwoDispatcher),
                "ITwo",
                s_service1Methods),
        };

        static DotBoxdGenerated()
        {
            global::DotBoxd.Services.Generated.DotBoxdServiceRegistry.RegisterServices(
                typeof(global::DotBoxd.Services.Generated.DotBoxdGenerated).Assembly,
                s_services);
            global::DotBoxd.Services.Generated.DotBoxdServiceRegistry.Register<global::Snap.Two.IOne>(
                static client => new global::Snap.Two.OneProxy(client),
                static implementation => new global::Snap.Two.OneDispatcher((global::Snap.Two.IOne)implementation),
                s_services[0]);
            global::DotBoxd.Services.Generated.DotBoxdServiceRegistry.Register<global::Snap.Two.ITwo>(
                static client => new global::Snap.Two.TwoProxy(client),
                static implementation => new global::Snap.Two.TwoDispatcher((global::Snap.Two.ITwo)implementation),
                s_services[1]);
        }

        /// <summary>
        /// Gets the services generated into this assembly without scanning for generated types.
        /// </summary>
        public static global::System.Collections.Generic.IReadOnlyList<global::DotBoxd.Services.Generated.DotBoxdGeneratedService> Services
            => s_services;

        /// <summary>
        /// Adds generated service proxy registrations to <paramref name="sink" /> without scanning generated types.
        /// </summary>
        public static void RegisterServices(global::DotBoxd.Services.Generated.IDotBoxdServiceRegistrationSink sink)
        {
            if (sink is null)
            {
                throw new global::System.ArgumentNullException(nameof(sink));
            }

            sink.AddService<global::Snap.Two.IOne, global::Snap.Two.OneProxy>();
            sink.AddService<global::Snap.Two.ITwo, global::Snap.Two.TwoProxy>();
        }

        /// <summary>
        /// Adds generated service proxy and dispatcher registrations to <paramref name="sink" /> without scanning generated types.
        /// </summary>
        public static void RegisterGeneratedServices(global::DotBoxd.Services.Generated.IDotBoxdGeneratedServiceRegistrationSink sink)
        {
            if (sink is null)
            {
                throw new global::System.ArgumentNullException(nameof(sink));
            }

            sink.AddService<global::Snap.Two.IOne, global::Snap.Two.OneProxy, global::Snap.Two.OneDispatcher>();
            sink.AddService<global::Snap.Two.ITwo, global::Snap.Two.TwoProxy, global::Snap.Two.TwoDispatcher>();
        }

        /// <summary>
        /// Creates the generated proxy for <typeparamref name="TService" /> over an invoker.
        /// </summary>
        public static TService CreateProxy<TService>(global::DotBoxd.Services.IRpcInvoker invoker)
            where TService : class
            => global::DotBoxd.Services.Generated.DotBoxdServiceRegistry.CreateProxy<TService>(invoker);

        /// <summary>
        /// Creates the generated proxy for <paramref name="serviceInterface" /> over an invoker.
        /// </summary>
        public static object CreateProxy(global::System.Type serviceInterface, global::DotBoxd.Services.IRpcInvoker invoker)
            => global::DotBoxd.Services.Generated.DotBoxdServiceRegistry.CreateProxy(serviceInterface, invoker);

        /// <summary>
        /// Creates the generated server dispatcher for <paramref name="implementation" />.
        /// </summary>
        public static global::DotBoxd.Services.Server.IServiceDispatcher CreateDispatcher<TService>(TService implementation)
            where TService : class
            => global::DotBoxd.Services.Generated.DotBoxdServiceRegistry.CreateDispatcher<TService>(implementation);

        /// <summary>
        /// Creates the generated server dispatcher for <paramref name="implementation" />.
        /// </summary>
        public static global::DotBoxd.Services.Server.IServiceDispatcher CreateDispatcher(global::System.Type serviceInterface, object implementation)
            => global::DotBoxd.Services.Generated.DotBoxdServiceRegistry.CreateDispatcher(serviceInterface, implementation);
    }
}
