//HintName: Snap_Vt_IVtSnap.DotBoxdRpcAsync.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Vt
{
    /// <summary>
    /// Auto-generated async sibling of <see cref="IVtSnap"/>. Use this
    /// interface from callers that must not block on RPC calls.
    /// </summary>
    public interface IVtSnapAsync
    {
        global::System.Threading.Tasks.ValueTask<int> AddAsync(int a, int b, global::System.Threading.CancellationToken ct = default);

        global::System.Threading.Tasks.ValueTask PingAsync(global::System.Threading.CancellationToken ct = default);
    }
}
