//HintName: Snap_Renamed_IHello.DotBoxDRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Renamed
{
    /// <summary>
    /// Server dispatcher for IHello.
    /// </summary>
    public sealed class HelloDispatcher : global::DotBoxD.Services.Server.IServiceDispatcher, global::DotBoxD.Services.Server.INonStreamingServiceDispatcher
    {
        private readonly global::Snap.Renamed.IHello? _service;

        internal HelloDispatcher()
        {
        }

        public HelloDispatcher(global::Snap.Renamed.IHello service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "Greeter";

        public global::System.Threading.Tasks.Task DispatchAsync(string method, global::System.ReadOnlyMemory<byte> payload, global::DotBoxD.Services.Serialization.ISerializer serializer, global::DotBoxD.Services.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default) =>
            DispatchAsync(method, payload, serializer, registry, output, global::DotBoxD.Services.Streaming.Remote.RpcStreamingContext.Disabled, ct);

        public global::System.Threading.Tasks.Task DispatchAsync(string method, global::System.ReadOnlyMemory<byte> payload, global::DotBoxD.Services.Serialization.ISerializer serializer, global::DotBoxD.Services.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::DotBoxD.Services.Streaming.Remote.IRpcStreamingContext streaming, global::System.Threading.CancellationToken ct = default)
        {
            if (_service is null)
            {
                throw new global::DotBoxD.Services.Exceptions.ServiceNotFoundException("Service 'Greeter' can only dispatch instance calls.", global::DotBoxD.Services.Exceptions.ServiceNotFoundException.NotFoundKind.Service);
            }

            return DispatchCoreAsync(_service, method, payload, serializer, registry, output, streaming, ct);
        }

        public global::System.Threading.Tasks.Task DispatchOnInstanceAsync(string instanceId, string method, global::System.ReadOnlyMemory<byte> payload, global::DotBoxD.Services.Serialization.ISerializer serializer, global::DotBoxD.Services.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default) =>
            DispatchOnInstanceAsync(instanceId, method, payload, serializer, registry, output, global::DotBoxD.Services.Streaming.Remote.RpcStreamingContext.Disabled, ct);

        public global::System.Threading.Tasks.Task DispatchOnInstanceAsync(string instanceId, string method, global::System.ReadOnlyMemory<byte> payload, global::DotBoxD.Services.Serialization.ISerializer serializer, global::DotBoxD.Services.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::DotBoxD.Services.Streaming.Remote.IRpcStreamingContext streaming, global::System.Threading.CancellationToken ct = default)
        {
            if (!registry.TryGet("Greeter", instanceId, out var __obj) || __obj is not global::Snap.Renamed.IHello __inst)
            {
                throw new global::DotBoxD.Services.Exceptions.ServiceNotFoundException("Instance '" + instanceId + "' not found for service 'Greeter'.", global::DotBoxD.Services.Exceptions.ServiceNotFoundException.NotFoundKind.Instance);
            }

            return DispatchCoreAsync(__inst, method, payload, serializer, registry, output, streaming, ct);
        }

#pragma warning disable CS1998
        private async global::System.Threading.Tasks.Task DispatchCoreAsync(global::Snap.Renamed.IHello receiver, string method, global::System.ReadOnlyMemory<byte> payload, global::DotBoxD.Services.Serialization.ISerializer serializer, global::DotBoxD.Services.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::DotBoxD.Services.Streaming.Remote.IRpcStreamingContext streaming, global::System.Threading.CancellationToken ct)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "Greet":
                {
                    var arg = serializer.Deserialize<string>(payload);
                    var __dotboxd_task = receiver.HelloAsync(arg);
                    var __dotboxd_result = __dotboxd_task.IsCompletedSuccessfully
                        ? __dotboxd_task.Result
                        : await __dotboxd_task;
                    serializer.Serialize(output, __dotboxd_result);
                    return;
                }
                default:
                    throw new global::DotBoxD.Services.Exceptions.ServiceNotFoundException("Method '" + method + "' not found on service 'Greeter'.", global::DotBoxD.Services.Exceptions.ServiceNotFoundException.NotFoundKind.Method);
            }
        }
    }
}
