//HintName: Snap_Nested_ISubSnap.DotBoxdRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Nested
{
    /// <summary>
    /// Server dispatcher for ISubSnap.
    /// </summary>
    public sealed class SubSnapDispatcher : global::DotBoxd.Services.Server.IServiceDispatcher, global::DotBoxd.Services.Server.INonStreamingServiceDispatcher
    {
        private readonly global::Snap.Nested.ISubSnap _service;

        public SubSnapDispatcher(global::Snap.Nested.ISubSnap service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "ISubSnap";

        public global::System.Threading.Tasks.Task DispatchAsync(string method, global::System.ReadOnlyMemory<byte> payload, global::DotBoxd.Services.Serialization.ISerializer serializer, global::DotBoxd.Services.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default) =>
            DispatchAsync(method, payload, serializer, registry, output, global::DotBoxd.Services.Streaming.RpcStreamingContext.Disabled, ct);

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task DispatchAsync(string method, global::System.ReadOnlyMemory<byte> payload, global::DotBoxd.Services.Serialization.ISerializer serializer, global::DotBoxd.Services.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::DotBoxd.Services.Streaming.IRpcStreamingContext streaming, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "CountAsync":
                {
                    var __dotboxd_task = _service.CountAsync();
                    var __dotboxd_result = __dotboxd_task.IsCompletedSuccessfully
                        ? __dotboxd_task.Result
                        : await __dotboxd_task;
                    serializer.Serialize(output, __dotboxd_result);
                    return;
                }
                default:
                    throw new global::DotBoxd.Services.Exceptions.DotBoxdRpcNotFoundException("Method '" + method + "' not found on service 'ISubSnap'.", global::DotBoxd.Services.Exceptions.DotBoxdRpcNotFoundException.NotFoundKind.Method);
            }
        }

        public global::System.Threading.Tasks.Task DispatchOnInstanceAsync(string instanceId, string method, global::System.ReadOnlyMemory<byte> payload, global::DotBoxd.Services.Serialization.ISerializer serializer, global::DotBoxd.Services.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default) =>
            DispatchOnInstanceAsync(instanceId, method, payload, serializer, registry, output, global::DotBoxd.Services.Streaming.RpcStreamingContext.Disabled, ct);

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task DispatchOnInstanceAsync(string instanceId, string method, global::System.ReadOnlyMemory<byte> payload, global::DotBoxd.Services.Serialization.ISerializer serializer, global::DotBoxd.Services.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::DotBoxd.Services.Streaming.IRpcStreamingContext streaming, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            if (!registry.TryGet("ISubSnap", instanceId, out var __obj) || __obj is not global::Snap.Nested.ISubSnap __inst)
            {
                throw new global::DotBoxd.Services.Exceptions.DotBoxdRpcNotFoundException("Instance '" + instanceId + "' not found for service 'ISubSnap'.", global::DotBoxd.Services.Exceptions.DotBoxdRpcNotFoundException.NotFoundKind.Instance);
            }
            switch (method)
            {
                case "CountAsync":
                {
                    var __dotboxd_task = __inst.CountAsync();
                    var __dotboxd_result = __dotboxd_task.IsCompletedSuccessfully
                        ? __dotboxd_task.Result
                        : await __dotboxd_task;
                    serializer.Serialize(output, __dotboxd_result);
                    return;
                }
                default:
                    throw new global::DotBoxd.Services.Exceptions.DotBoxdRpcNotFoundException("Method '" + method + "' not found on service 'ISubSnap'.", global::DotBoxd.Services.Exceptions.DotBoxdRpcNotFoundException.NotFoundKind.Method);
            }
        }
    }
}
