//HintName: DotBoxdRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace DotBoxd.Services.Generated
{
    /// <summary>
    /// Extension methods for registering generated DotBoxd services.
    /// </summary>
    public static class DotBoxdGeneratedExtensions
    {

        /// <summary>
        /// Provides a IRootSnap implementation for the other peer to call.
        /// </summary>
        public static global::DotBoxd.Services.RpcPeer ProvideRootSnap(this global::DotBoxd.Services.RpcPeer peer, global::Snap.Nested.IRootSnap implementation)
            => peer.Provide((global::DotBoxd.Services.Server.IServiceDispatcher)new global::Snap.Nested.RootSnapDispatcher(implementation));

        /// <summary>
        /// Gets a proxy to call IRootSnap on the other peer.
        /// </summary>
        public static global::Snap.Nested.IRootSnap GetRootSnap(this global::DotBoxd.Services.RpcPeer peer)
            => new global::Snap.Nested.RootSnapProxy(peer);

        /// <summary>
        /// Provides a ISubSnap implementation for the other peer to call.
        /// </summary>
        public static global::DotBoxd.Services.RpcPeer ProvideSubSnap(this global::DotBoxd.Services.RpcPeer peer, global::Snap.Nested.ISubSnap implementation)
            => peer.Provide((global::DotBoxd.Services.Server.IServiceDispatcher)new global::Snap.Nested.SubSnapDispatcher(implementation));

        /// <summary>
        /// Gets a proxy to call ISubSnap on the other peer.
        /// </summary>
        public static global::Snap.Nested.ISubSnap GetSubSnap(this global::DotBoxd.Services.RpcPeer peer)
            => new global::Snap.Nested.SubSnapProxy(peer);
    }
}
