//HintName: Snap_Nested_IRootSnap.DotBoxDRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Nested
{
    /// <summary>
    /// Client proxy for IRootSnap.
    /// </summary>
    public sealed class RootSnapProxy : global::Snap.Nested.IRootSnap, global::Snap.Nested.IRootSnapAsync
    {
        private readonly global::DotBoxD.Services.Server.IRpcInvoker _invoker;
        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>
        private readonly string? _instanceId;

        public RootSnapProxy(global::DotBoxD.Services.Server.IRpcInvoker client)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = null;
        }

        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>
        public RootSnapProxy(global::DotBoxD.Services.Server.IRpcInvoker client, string instanceId)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = instanceId ?? throw new global::System.ArgumentNullException(nameof(instanceId));
        }

        public async global::System.Threading.Tasks.Task<global::Snap.Nested.ISubSnap> GetSubAsync(string label)
        {
            var __dotboxd_handle = await (this._instanceId is null ? this._invoker.InvokeAsync<string, global::DotBoxD.Services.Protocol.ServiceHandle>("IRootSnap", "GetSubAsync", label, default) : this._invoker.InvokeOnInstanceAsync<string, global::DotBoxD.Services.Protocol.ServiceHandle>("IRootSnap", this._instanceId!, "GetSubAsync", label, default));
            if (!global::System.String.Equals(__dotboxd_handle.ServiceName, "ISubSnap", global::System.StringComparison.Ordinal))
            {
                throw new global::DotBoxD.Services.Exceptions.ServiceProtocolException("ServiceHandle.ServiceName did not match expected sub-service 'ISubSnap'.");
            }
            return new global::Snap.Nested.SubSnapProxy(this._invoker, __dotboxd_handle.InstanceId);
        }

        public async global::System.Threading.Tasks.Task<global::Snap.Nested.ISubSnap> GetSubAsync(string label, global::System.Threading.CancellationToken ct = default)
        {
            var __dotboxd_handle = await (this._instanceId is null ? this._invoker.InvokeAsync<string, global::DotBoxD.Services.Protocol.ServiceHandle>("IRootSnap", "GetSubAsync", label, ct) : this._invoker.InvokeOnInstanceAsync<string, global::DotBoxD.Services.Protocol.ServiceHandle>("IRootSnap", this._instanceId!, "GetSubAsync", label, ct));
            if (!global::System.String.Equals(__dotboxd_handle.ServiceName, "ISubSnap", global::System.StringComparison.Ordinal))
            {
                throw new global::DotBoxD.Services.Exceptions.ServiceProtocolException("ServiceHandle.ServiceName did not match expected sub-service 'ISubSnap'.");
            }
            return new global::Snap.Nested.SubSnapProxy(this._invoker, __dotboxd_handle.InstanceId);
        }
    }
}
