//HintName: Snap_Renamed_IHello.DotBoxdRpcAsync.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Renamed
{
    /// <summary>
    /// Auto-generated async sibling of <see cref="IHello"/>. Use this
    /// interface from callers that must not block on RPC calls.
    /// </summary>
    public interface IHelloAsync
    {
        global::System.Threading.Tasks.Task<string> HelloAsync(string who, global::System.Threading.CancellationToken ct = default);
    }
}
