//HintName: DotBoxDRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace DotBoxD.Services.Generated
{
    /// <summary>
    /// Extension methods for registering generated DotBoxD services.
    /// </summary>
    public static class DotBoxDGeneratedExtensions
    {

        /// <summary>
        /// Provides a IDerived implementation for the other peer to call.
        /// </summary>
        public static global::DotBoxD.Services.Peer.RpcPeer ProvideDerived(this global::DotBoxD.Services.Peer.RpcPeer peer, global::Snap.Inherit.IDerived implementation)
            => peer.Provide((global::DotBoxD.Services.Server.IServiceDispatcher)new global::Snap.Inherit.DerivedDispatcher(implementation));

        /// <summary>
        /// Gets a proxy to call IDerived on the other peer.
        /// </summary>
        public static global::Snap.Inherit.IDerived GetDerived(this global::DotBoxD.Services.Peer.RpcPeer peer)
            => peer.Get<global::Snap.Inherit.IDerived>();
    }
}
