//HintName: Snap_RefOut_IRefOutSnap.DotBoxDRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.RefOut
{
    /// <summary>
    /// Client proxy for IRefOutSnap.
    /// </summary>
    public sealed class RefOutSnapProxy : global::Snap.RefOut.IRefOutSnap, global::Snap.RefOut.IRefOutSnapAsync
    {
        private readonly global::DotBoxD.Services.Server.IRpcInvoker _invoker;
        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>
        private readonly string? _instanceId;

        public RefOutSnapProxy(global::DotBoxD.Services.Server.IRpcInvoker client)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = null;
        }

        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>
        public RefOutSnapProxy(global::DotBoxD.Services.Server.IRpcInvoker client, string instanceId)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = instanceId ?? throw new global::System.ArgumentNullException(nameof(instanceId));
        }

        public void BadOut(out int x)
        {
            throw new global::System.NotSupportedException("DotBoxD cannot marshal 'BadOut': parameter 'x' uses an unsupported pass-by-reference kind 'out'");
        }

        public global::System.Threading.Tasks.Task<int> GoodAsync(int a)
        {
            try
            {
                return (this._instanceId is null ? this._invoker.InvokeAsync<int, int>("IRefOutSnap", "GoodAsync", a, default) : this._invoker.InvokeOnInstanceAsync<int, int>("IRefOutSnap", this._instanceId!, "GoodAsync", a, default));
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled<int>(__dotboxd_canceled.CancellationToken);
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return global::System.Threading.Tasks.Task.FromException<int>(__dotboxd_ex);
            }
        }

        public global::System.Threading.Tasks.Task<int> GoodAsync(int a, global::System.Threading.CancellationToken ct = default)
        {
            try
            {
                return __dotboxd_observeCallerCancellationAsync((this._instanceId is null ? this._invoker.InvokeAsync<int, int>("IRefOutSnap", "GoodAsync", a, ct) : this._invoker.InvokeOnInstanceAsync<int, int>("IRefOutSnap", this._instanceId!, "GoodAsync", a, ct)), ct);
            }
            catch (global::System.OperationCanceledException __dotboxd_canceled) when (__dotboxd_canceled.CancellationToken.IsCancellationRequested || ct.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled<int>(__dotboxd_canceled.CancellationToken.IsCancellationRequested ? __dotboxd_canceled.CancellationToken : ct);
            }
            catch (global::System.Exception __dotboxd_ex)
            {
                return global::System.Threading.Tasks.Task.FromException<int>(__dotboxd_ex);
            }
        }

        private static async global::System.Threading.Tasks.Task __dotboxd_observeCallerCancellationAsync(global::System.Threading.Tasks.Task task, global::System.Threading.CancellationToken ct)
        {
            await task.ConfigureAwait(false);
            ct.ThrowIfCancellationRequested();
        }

        private static async global::System.Threading.Tasks.Task<T> __dotboxd_observeCallerCancellationAsync<T>(global::System.Threading.Tasks.Task<T> task, global::System.Threading.CancellationToken ct)
        {
            var result = await task.ConfigureAwait(false);
            ct.ThrowIfCancellationRequested();
            return result;
        }

        private static async global::System.Threading.Tasks.ValueTask __dotboxd_observeCallerCancellationAsync(global::System.Threading.Tasks.ValueTask task, global::System.Threading.CancellationToken ct)
        {
            await task.ConfigureAwait(false);
            ct.ThrowIfCancellationRequested();
        }

        private static async global::System.Threading.Tasks.ValueTask<T> __dotboxd_observeCallerCancellationAsync<T>(global::System.Threading.Tasks.ValueTask<T> task, global::System.Threading.CancellationToken ct)
        {
            var result = await task.ConfigureAwait(false);
            ct.ThrowIfCancellationRequested();
            return result;
        }
    }
}
