using DotBoxD.Plugins.Analyzer.Analysis.Rpc;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DotBoxD.Plugins.Analyzer.Analysis.UI;

internal static class UiHandlerModelFactory
{
    public static UiHandlerModel Create(GeneratorAttributeSyntaxContext context, bool remote, CancellationToken token)
    {
        var method = (IMethodSymbol)context.TargetSymbol;
        var syntax = (MethodDeclarationSyntax)context.TargetNode;
        var location = syntax.Identifier.GetLocation();
        var hint = method.ContainingType.ToDisplayString() + "." + method.Name + ".Ui.g.cs";
        try
        {
            var attribute = context.Attributes[0];
            var facet = remote ? "GenerateEndpoint" : "GenerateKernel";
            if (attribute.NamedArguments.Any(a => a.Key == facet && a.Value.Value is false))
            { return Model(null, null); }
            RequireSourceContainer(syntax);
            RequireContainer(method);
            if (method.ContainingType.GetMembers(method.Name).OfType<IMethodSymbol>().Count() != 1)
            { throw new NotSupportedException("UI handler names must be unique; overloads require distinct route names"); }
            var name = method.Name + (remote ? "UiEndpoint" : "UiKernel");
            if (method.ContainingType.GetMembers(name).Length != 0)
            { return Model(null, null); }
            var member = remote ? RemoteMember(method, attribute, name) : LocalMember(method, syntax, context.SemanticModel, token, name);
            var ns = method.ContainingNamespace.IsGlobalNamespace ? "" : "namespace " + method.ContainingNamespace.ToDisplayString() + ";";
            var container = (TypeDeclarationSyntax)syntax.Parent!;
            var source = "// <auto-generated/>\n#nullable enable\n" + ns + "\n" +
                string.Join(" ", container.Modifiers.Select(m => m.Text)) + " " + container.Keyword.Text + " " +
                container.Identifier.Text + "\n{\n" + member + "\n}\n";
            return Model(source, null);
        }
        catch (NotSupportedException error)
        { return Fail(error.Message); }

        UiHandlerModel Fail(string error) => Model(null, error);

        UiHandlerModel Model(string? source, string? error) => new(method.Name, hint, source, error,
            location.SourceTree!.FilePath, location.SourceSpan, location.GetLineSpan().Span);
    }

    private static void RequireSourceContainer(MethodDeclarationSyntax syntax)
    {
        if (syntax.Parent is not ClassDeclarationSyntax and not StructDeclarationSyntax)
        { throw new NotSupportedException("UI handlers require a partial class or struct"); }
    }

    private static void RequireContainer(IMethodSymbol method)
    {
        if (method.ContainingType.IsFileLocal)
        { throw new NotSupportedException("file-local types cannot receive generated members in a separate source file; use a non-file-local partial type"); }
        if (method.ContainingType.ContainingType is not null || method.ContainingType.IsGenericType ||
            method.ContainingType.DeclaringSyntaxReferences.Any(r =>
                r.GetSyntax() is not TypeDeclarationSyntax type || !type.Modifiers.Any(SyntaxKind.PartialKeyword)))
        { throw new NotSupportedException("declare the handler on a top-level non-generic partial class or struct"); }
        if (method.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "DotBoxD.UI.Authoring.UiLocalHandlerAttribute") &&
            method.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "DotBoxD.UI.Authoring.UiRemoteHandlerAttribute"))
        { throw new NotSupportedException("choose exactly one local or remote execution boundary"); }
    }

    private static string RemoteMember(IMethodSymbol method, AttributeData attribute, string name)
    {
        if (attribute.ConstructorArguments[0].Value is not int id || id <= 0 || method.IsGenericMethod)
        { throw new NotSupportedException("remote endpoints require a positive stable ID and non-generic method"); }
        return "public const int " + name + " = " + id.ToString(System.Globalization.CultureInfo.InvariantCulture) + ";";
    }

    private static string LocalMember(IMethodSymbol method, MethodDeclarationSyntax syntax, SemanticModel model,
        CancellationToken token, string name)
    {
        RequireLocalSignature(method);
        var output = ScalarTag(method.ReturnType);
        var input = method.Parameters.Length == 0 ? null : ScalarTag(method.Parameters[0].Type);
        var capabilities = new SortedSet<string>(StringComparer.Ordinal);
        var effects = new SortedSet<string>(StringComparer.Ordinal);
        var prelude = new List<string>();
        var lowerer = new DotBoxDRpcJsonLowerer(model, capabilities, effects, token, expressionPrelude: prelude);
        var body = syntax.Body is { } block ? lowerer.LowerBody(block, method.ReturnType)
            : ExpressionBody(lowerer, syntax, prelude);
        if (lowerer.Allocates)
        { effects.Add("Alloc"); }
        var parameters = method.Parameters.Length == 0 ? "[]" : "[{\"name\":" + Json(method.Parameters[0].Name) + ",\"type\":" + Json(input!) + "}]";
        var json = "{\"id\":" + Json(method.ContainingType.ToDisplayString() + "." + method.Name) +
            ",\"version\":\"1.0.0\",\"targetSandboxVersion\":\"1.0.0\",\"capabilityRequests\":[" +
            string.Join(",", capabilities.Select(c => "{\"id\":" + Json(c) + "}")) + "],\"functions\":[{\"id\":\"main\",\"visibility\":\"entrypoint\",\"parameters\":" +
            parameters + ",\"returnType\":" + Json(output) + ",\"body\":" + body + "}]}";
        var inputType = method.Parameters.Length == 0 ? "global::DotBoxD.UI.Authoring.UiUnit" : TypeName(method.Parameters[0].Type);
        return "public static global::DotBoxD.UI.Authoring.UiKernelDefinition<" + inputType + ", " + TypeName(method.ReturnType) + "> " + name +
            "() => new(" + SymbolDisplay.FormatLiteral(json, quote: true) + ", \"main\");";
    }

    private static void RequireLocalSignature(IMethodSymbol method)
    {
        if (!method.IsStatic || method.IsGenericMethod || method.IsAsync || method.Parameters.Length > 1 ||
            method.Parameters.Any(p => p.RefKind != RefKind.None))
        { throw new NotSupportedException("local methods must be static, synchronous, non-generic, with zero or one scalar value parameter"); }
    }

    private static string ExpressionBody(DotBoxDRpcJsonLowerer lowerer, MethodDeclarationSyntax syntax, List<string> prelude)
    {
        var expression = syntax.ExpressionBody?.Expression ?? throw new NotSupportedException("a local method body is required");
        var value = lowerer.LowerExpression(expression);
        prelude.Add("{\"op\":\"return\",\"value\":" + value + "}");
        return "[" + string.Join(",", prelude) + "]";
    }

    private static string ScalarTag(ITypeSymbol type) => type.SpecialType switch
    {
        SpecialType.System_Int32 => "I32",
        SpecialType.System_Boolean => "Bool",
        SpecialType.System_Double => "F64",
        SpecialType.System_String => "String",
        _ => throw new NotSupportedException("state/kernel values must be int, bool, double or string")
    };
    private static string TypeName(ITypeSymbol type) => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    private static string Json(string value) => DotBoxDRpcJsonLowerer.Str(value);
}
