//HintName: Snap_Kw_IKwSnap.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Kw
{
    /// <summary>
    /// Client proxy for IKwSnap.
    /// </summary>
    public sealed class KwSnapProxy : global::Snap.Kw.IKwSnap, global::Snap.Kw.IKwSnapAsync
    {
        private readonly global::ShaRPC.Core.IRpcInvoker _invoker;
        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>
        private readonly string? _instanceId;

        public KwSnapProxy(global::ShaRPC.Core.IRpcInvoker client)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = null;
        }

        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>
        public KwSnapProxy(global::ShaRPC.Core.IRpcInvoker client, string instanceId)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = instanceId ?? throw new global::System.ArgumentNullException(nameof(instanceId));
        }

        public global::System.Threading.Tasks.Task<int> DoAsync(int @class, int @default)
        {
            try
            {
                return (this._instanceId is null ? this._invoker.InvokeAsync<(int, int), int>("IKwSnap", "DoAsync", (@class, @default), default) : this._invoker.InvokeOnInstanceAsync<(int, int), int>("IKwSnap", this._instanceId!, "DoAsync", (@class, @default), default));
            }
            catch (global::System.OperationCanceledException __sharpc_canceled) when (__sharpc_canceled.CancellationToken.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled<int>(__sharpc_canceled.CancellationToken);
            }
            catch (global::System.Exception __sharpc_ex)
            {
                return global::System.Threading.Tasks.Task.FromException<int>(__sharpc_ex);
            }
        }

        public global::System.Threading.Tasks.Task<int> DoAsync(int @class, int @default, global::System.Threading.CancellationToken ct = default)
        {
            try
            {
                return (this._instanceId is null ? this._invoker.InvokeAsync<(int, int), int>("IKwSnap", "DoAsync", (@class, @default), ct) : this._invoker.InvokeOnInstanceAsync<(int, int), int>("IKwSnap", this._instanceId!, "DoAsync", (@class, @default), ct));
            }
            catch (global::System.OperationCanceledException __sharpc_canceled) when (__sharpc_canceled.CancellationToken.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled<int>(__sharpc_canceled.CancellationToken);
            }
            catch (global::System.Exception __sharpc_ex)
            {
                return global::System.Threading.Tasks.Task.FromException<int>(__sharpc_ex);
            }
        }
    }
}
