//HintName: Snap_One_ICalculator.ShaRpcAsync.g.cs
// <auto-generated />
#nullable enable

namespace Snap.One
{
    /// <summary>
    /// Auto-generated async sibling of <see cref="ICalculator"/>. Use this
    /// interface from callers that must not block on RPC calls.
    /// </summary>
    public interface ICalculatorAsync
    {
        global::System.Threading.Tasks.Task<int> AddAsync(int a, int b, global::System.Threading.CancellationToken ct = default);
    }
}
