//HintName: Snap_Mixed_IMix.ShaRpcAsync.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Mixed
{
    /// <summary>
    /// Auto-generated async sibling of <see cref="IMix"/>. Use this
    /// interface from callers that must not block on RPC calls.
    /// </summary>
    public interface IMixAsync
    {
        global::System.Threading.Tasks.Task<string> GetNameAsync(global::System.Threading.CancellationToken ct = default);

        global::System.Threading.Tasks.Task SaveAsync(string value, global::System.Threading.CancellationToken ct = default);

        global::System.Threading.Tasks.Task<int> SyncAddAsync(int a, int b, global::System.Threading.CancellationToken ct = default);

        global::System.Threading.Tasks.Task SyncPingAsync(global::System.Threading.CancellationToken ct = default);
    }
}
