//HintName: Snap_Kw_IKwSnap.ShaRpcAsync.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Kw
{
    /// <summary>
    /// Auto-generated async sibling of <see cref="IKwSnap"/>. Use this
    /// interface from callers that must not block on RPC calls.
    /// </summary>
    public interface IKwSnapAsync
    {
        global::System.Threading.Tasks.Task<int> DoAsync(int @class, int @default, global::System.Threading.CancellationToken ct = default);
    }
}
