//HintName: Snap_Inherit_IDerived.ShaRpcAsync.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Inherit
{
    /// <summary>
    /// Auto-generated async sibling of <see cref="IDerived"/>. Use this
    /// interface from callers that must not block on RPC calls.
    /// </summary>
    public interface IDerivedAsync
    {
        global::System.Threading.Tasks.Task<string> DerivedAsync(global::System.Threading.CancellationToken ct = default);

        global::System.Threading.Tasks.Task<int> BaseAsync(int x, global::System.Threading.CancellationToken ct = default);
    }
}
