//HintName: Snap_One_ICalculator.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.One
{
    /// <summary>
    /// Client proxy for ICalculator.
    /// </summary>
    public sealed class CalculatorProxy : global::Snap.One.ICalculator, global::Snap.One.ICalculatorAsync
    {
        private readonly global::ShaRPC.Core.IRpcInvoker _invoker;
        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>
        private readonly string? _instanceId;

        public CalculatorProxy(global::ShaRPC.Core.IRpcInvoker client)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = null;
        }

        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>
        public CalculatorProxy(global::ShaRPC.Core.IRpcInvoker client, string instanceId)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = instanceId ?? throw new global::System.ArgumentNullException(nameof(instanceId));
        }

        public global::System.Threading.Tasks.Task<int> AddAsync(int a, int b)
        {
            try
            {
                return (this._instanceId is null ? this._invoker.InvokeAsync<(int, int), int>("ICalculator", "AddAsync", (a, b), default) : this._invoker.InvokeOnInstanceAsync<(int, int), int>("ICalculator", this._instanceId!, "AddAsync", (a, b), default));
            }
            catch (global::System.OperationCanceledException __sharpc_canceled) when (__sharpc_canceled.CancellationToken.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled<int>(__sharpc_canceled.CancellationToken);
            }
            catch (global::System.Exception __sharpc_ex)
            {
                return global::System.Threading.Tasks.Task.FromException<int>(__sharpc_ex);
            }
        }

        public global::System.Threading.Tasks.Task<int> AddAsync(int a, int b, global::System.Threading.CancellationToken ct = default)
        {
            try
            {
                return (this._instanceId is null ? this._invoker.InvokeAsync<(int, int), int>("ICalculator", "AddAsync", (a, b), ct) : this._invoker.InvokeOnInstanceAsync<(int, int), int>("ICalculator", this._instanceId!, "AddAsync", (a, b), ct));
            }
            catch (global::System.OperationCanceledException __sharpc_canceled) when (__sharpc_canceled.CancellationToken.IsCancellationRequested)
            {
                return global::System.Threading.Tasks.Task.FromCanceled<int>(__sharpc_canceled.CancellationToken);
            }
            catch (global::System.Exception __sharpc_ex)
            {
                return global::System.Threading.Tasks.Task.FromException<int>(__sharpc_ex);
            }
        }
    }
}
