//HintName: Snap_Nested_ISubSnap.ShaRpcAsync.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Nested
{
    /// <summary>
    /// Auto-generated async sibling of <see cref="ISubSnap"/>. Use this
    /// interface from callers that must not block on RPC calls.
    /// </summary>
    public interface ISubSnapAsync
    {
        global::System.Threading.Tasks.Task<int> CountAsync(global::System.Threading.CancellationToken ct = default);
    }
}
