using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using DotBoxD.Plugins.Analyzer.Analysis.Lowering;
using Microsoft.CodeAnalysis;

namespace DotBoxD.Plugins.Analyzer.Analysis.InvokeAsync;

internal static class InvokeAsyncInterceptorEmitter
{
    public static void Emit(SourceProductionContext context, ImmutableArray<InvokeAsyncInterception> interceptions)
    {
        if (interceptions.IsDefaultOrEmpty)
        {
            return;
        }

        context.AddSource("DotBoxDInvokeAsyncInterceptors.g.cs", BuildInterceptors(interceptions));
    }

    private static string BuildInterceptors(ImmutableArray<InvokeAsyncInterception> interceptions)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.Append("namespace ").AppendLine(DotBoxDGenerationNames.TypeNames.GeneratedInterceptorsNamespace);
        builder.AppendLine("{");
        builder.AppendLine("    internal static class InvokeAsyncInterceptors");
        builder.AppendLine("    {");

        for (var i = 0; i < interceptions.Length; i++)
        {
            AppendInterceptor(builder, interceptions[i], i);
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendInterceptor(
        StringBuilder builder,
        InvokeAsyncInterception interception,
        int index)
    {
        builder.Append("        ").AppendLine(interception.AttributeSyntax);
        builder.Append("        internal static async global::System.Threading.Tasks.ValueTask<")
            .Append(interception.ReturnType)
            .Append("> InvokeAsync_")
            .Append(index.ToString(CultureInfo.InvariantCulture))
            .AppendLine("(");
        builder.Append("            this ").Append(interception.ReceiverType).AppendLine(" kernels,");
        if (interception.CaptureType is { } captureType &&
            interception.CaptureDelegateType is { } captureDelegateType)
        {
            builder.Append("            ").Append(captureType).AppendLine(" captures,");
            builder.Append("            ").Append(captureDelegateType).Append('<')
                .Append(captureType)
                .Append(", ")
                .Append(interception.ReturnType)
                .AppendLine("> lambda)");
        }
        else
        {
            builder.Append("            global::System.Func<")
                .Append(interception.HostAccessType)
                .Append(", ")
                .Append(interception.ReturnType)
                .AppendLine("> lambda)");
        }

        builder.AppendLine("        {");
        if (interception.CaptureType is not null)
        {
            builder.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(captures);");
        }

        builder.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(lambda);");
        builder.Append("            var __pluginId = await kernels.EnsureAnonymousKernelAsync(")
            .Append(Literal(interception.PluginId))
            .Append(", ")
            .Append(interception.PackageFullName)
            .AppendLine(".Create).ConfigureAwait(false);");
        builder.Append("            var __request = global::DotBoxD.Plugins.KernelRpcBinaryCodec.EncodeArguments(")
            .Append(interception.ArgumentsExpression)
            .AppendLine(");");
        builder.AppendLine("            var __response = await kernels.WireClient.InvokeKernelRpcAsync(__pluginId, __request).ConfigureAwait(false);");
        builder.AppendLine("            var __result = global::DotBoxD.Plugins.KernelRpcBinaryCodec.DecodeValue(__response);");
        if (interception.SyncOutAssignments.Count > 0)
        {
            builder.AppendLine("            __result.RequireKind(global::DotBoxD.Plugins.KernelRpcValueKind.Record);");
            builder.AppendLine("            var __fields = __result.Items;");
            builder.Append("            if (__fields.Length != ")
                .Append((interception.SyncOutAssignments.Count + 1).ToString(CultureInfo.InvariantCulture))
                .AppendLine(")");
            builder.AppendLine("            {");
            builder.AppendLine("                throw new global::System.NotSupportedException(\"InvokeAsync response field count did not match the generated capture shape.\");");
            builder.AppendLine("            }");
            for (var i = 0; i < interception.SyncOutAssignments.Count; i++)
            {
                builder.Append("            ").Append(interception.SyncOutAssignments[i]).AppendLine(";");
            }
        }

        builder.Append("            return ").Append(interception.ResultExpression).AppendLine(";");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.Append(interception.Helpers);
    }

    private static string Literal(string value)
        => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
