using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;

namespace DotBoxD.Plugins.Analyzer.Analysis.InvokeAsync;

internal static class InvokeAsyncInterceptorEmitter
{
    public static void Emit(SourceProductionContext context, ImmutableArray<InvokeAsyncInterception> interceptions)
    {
        if (interceptions.IsDefaultOrEmpty)
        {
            return;
        }

        context.AddSource("DotBoxDInvokeAsyncInterceptors.g.cs", BuildInterceptors(interceptions));
    }

    private static string BuildInterceptors(ImmutableArray<InvokeAsyncInterception> interceptions)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace DotBoxD.Plugins.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    internal static class InvokeAsyncInterceptors");
        builder.AppendLine("    {");

        for (var i = 0; i < interceptions.Length; i++)
        {
            AppendInterceptor(builder, interceptions[i], i);
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendInterceptor(
        StringBuilder builder,
        InvokeAsyncInterception interception,
        int index)
    {
        builder.Append("        ").AppendLine(interception.AttributeSyntax);
        builder.Append("        public static async global::System.Threading.Tasks.ValueTask<")
            .Append(interception.ReturnType)
            .Append("> InvokeAsync_")
            .Append(index.ToString(CultureInfo.InvariantCulture))
            .AppendLine("(");
        builder.Append("            this ").Append(interception.ReceiverType).AppendLine(" kernels,");
        builder.Append("            global::System.Func<")
            .Append(interception.HostAccessType)
            .Append(", ")
            .Append(interception.ReturnType)
            .AppendLine("> lambda)");
        builder.AppendLine("        {");
        builder.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(lambda);");
        builder.Append("            var __pluginId = await kernels.EnsureAnonymousKernelAsync(")
            .Append(Literal(interception.PluginId))
            .Append(", ")
            .Append(interception.PackageFullName)
            .AppendLine(".Create).ConfigureAwait(false);");
        builder.AppendLine("            var __request = global::DotBoxD.Plugins.KernelRpcBinaryCodec.EncodeArguments(global::System.Array.Empty<global::DotBoxD.Plugins.KernelRpcValue>());");
        builder.AppendLine("            var __response = await kernels.WireClient.InvokeKernelRpcAsync(__pluginId, __request).ConfigureAwait(false);");
        builder.AppendLine("            var __result = global::DotBoxD.Plugins.KernelRpcBinaryCodec.DecodeValue(__response);");
        builder.Append("            return ").Append(interception.ResultExpression).AppendLine(";");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.Append(interception.Helpers);
    }

    private static string Literal(string value)
        => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
