using DotBoxD.Plugins.Analyzer.Analysis.Debugging;
using DotBoxD.Plugins.Analyzer.Analysis.Lowering;
using static DotBoxD.Plugins.Analyzer.Analysis.Rpc.DotBoxDRpcJsonLowerer;
using TypeNames = DotBoxD.Plugins.Analyzer.Analysis.Lowering.DotBoxDGenerationNames.TypeNames;

namespace DotBoxD.Plugins.Analyzer.Analysis.InvokeAsync;

internal static partial class InvokeAsyncModelFactory
{
    private static GeneratedPluginPackage EmitPackage(
        string ns,
        string packageName,
        string pluginId,
        InvokeAsyncCallShape shape,
        string bodyJson,
        IEnumerable<string> effects,
        IEnumerable<string> capabilities,
        KernelSourceLocationModel source)
    {
        var json =
            "{" +
            "\"manifest\":{" +
            $"\"pluginId\":{Str(pluginId)}," +
            "\"contract\":\"AnonymousInvokeAsync\"," +
            "\"mode\":\"Auto\"," +
            $"\"effects\":[{JoinStrings(effects)}]," +
            "\"liveSettings\":[]," +
            "\"subscriptions\":[]," +
            $"\"requiredCapabilities\":[{JoinStrings(capabilities)}]," +
            "\"rpcEntrypoint\":\"Invoke\"}," +
            "\"entrypoints\":{\"shouldHandle\":\"Invoke\",\"handle\":\"Invoke\"}," +
            "\"module\":{" +
            $"\"id\":{Str(pluginId)},\"version\":\"1.0.0\",\"targetSandboxVersion\":\"1.0.0\"," +
            "\"capabilityRequests\":[]," +
            $"\"metadata\":{{\"kernel\":\"AnonymousInvokeAsync\",\"pluginId\":{Str(pluginId)}}}," +
            "\"functions\":[{" +
            "\"id\":\"Invoke\",\"visibility\":\"entrypoint\"," +
            $"\"parameters\":{shape.ParametersJson}," +
            $"\"returnType\":{shape.ReturnTypeJson}," +
            $"\"body\":{bodyJson}}}]}}}}";

        return new GeneratedPluginPackage(
            HintName(ns, packageName),
            BuildSource(ns, packageName, json, shape, source),
            ns,
            packageName);
    }

    private static string BuildSource(
        string ns,
        string packageName,
        string json,
        InvokeAsyncCallShape shape,
        KernelSourceLocationModel source)
    {
        var builder = new System.Text.StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        if (!string.IsNullOrEmpty(ns))
        {
            builder.Append("namespace ").Append(ns).AppendLine(";");
            builder.AppendLine();
        }

        builder.Append("public static class ").AppendLine(packageName);
        builder.AppendLine("{");
        builder.Append("    public static ").Append(DotBoxDGenerationNames.TypeNames.GlobalPluginPackage).AppendLine(" Create()");
        builder.AppendLine("    {");
        builder.Append("        var package = ").Append(DotBoxDGenerationNames.TypeNames.GlobalPluginPackageJsonSerializer)
            .Append(".Import(\"").Append(json.Replace("\\", "\\\\").Replace("\"", "\\\"")).AppendLine("\");");
        EmitDebugInfo(builder, shape, source);
        builder.AppendLine("        return package with { Module = module, DebugInfo = debugInfo };");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void EmitDebugInfo(
        System.Text.StringBuilder builder,
        InvokeAsyncCallShape shape,
        KernelSourceLocationModel source)
    {
        var points = SequencePoints(source).ToArray();
        builder.Append("        var spans = new ").Append(TypeNames.GlobalSourceSpan).AppendLine("[]");
        builder.AppendLine("        {");
        foreach (var point in points)
        {
            builder.Append("            new ").Append(TypeNames.GlobalSourceSpan).Append('(')
                .Append(point.StartLine).Append(", ").Append(point.StartColumn).Append(", ")
                .Append(LiteralReader.StringLiteral(point.DocumentId)).Append(", ")
                .Append(point.EndLine).Append(", ").Append(point.EndColumn).AppendLine("),");
        }

        builder.AppendLine("        };");
        builder.Append("        var module = ").Append(TypeNames.GlobalKernelDebugModuleMapper)
            .AppendLine(".ApplyFunctionSequenceSpans(package.Module, new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.IReadOnlyList<global::DotBoxD.Kernels.Model.SourceSpan>> { [\"Invoke\"] = spans });");
        builder.Append("        var documents = new ").Append(TypeNames.GlobalKernelDebugDocument).AppendLine("[]");
        builder.AppendLine("        {");
        foreach (var document in points.GroupBy(point => point.DocumentId, StringComparer.Ordinal)
                     .Select(group => group.First()))
        {
            builder.Append("            new ").Append(TypeNames.GlobalKernelDebugDocument).Append('(')
                .Append(LiteralReader.StringLiteral(document.DocumentId)).Append(", ")
                .Append(LiteralReader.StringLiteral(document.Path)).Append(", ")
                .Append(LiteralReader.StringLiteral(document.Sha256Checksum)).AppendLine("),");
        }

        builder.AppendLine("        };");
        builder.Append("        var bindings = new ").Append(TypeNames.GlobalKernelDebugVariableBinding).AppendLine("[]");
        builder.AppendLine("        {");
        foreach (var name in shape.DebugParameterNames)
        {
            builder.Append("            new ").Append(TypeNames.GlobalKernelDebugVariableBinding).Append("(\"Invoke\", ")
                .Append(LiteralReader.StringLiteral(name)).Append(", ")
                .Append(LiteralReader.StringLiteral(name)).AppendLine("),");
        }

        builder.AppendLine("        };");
        builder.Append("        var debugInfo = ").Append(TypeNames.GlobalKernelDebugInfo)
            .AppendLine(".Create(module, documents, bindings);");
    }

    private static IEnumerable<KernelSourceLocationModel> SequencePoints(KernelSourceLocationModel source)
        => source.SequencePoints.Count == 0 ? [source] : source.SequencePoints;

    private static string HintName(string ns, string packageName)
        => string.IsNullOrWhiteSpace(ns)
            ? packageName + ".g.cs"
            : ns.Replace("@", string.Empty) + "." + packageName + ".g.cs";

    private static string JoinStrings(IEnumerable<string> values)
    {
        var parts = new List<string>();
        foreach (var value in values)
        {
            parts.Add(Str(value));
        }

        return string.Join(",", parts);
    }
}
