using DotBoxD.Plugins.Analyzer.Analysis.Lowering;
using static DotBoxD.Plugins.Analyzer.Analysis.Rpc.DotBoxDRpcJsonLowerer;

namespace DotBoxD.Plugins.Analyzer.Analysis.InvokeAsync;

internal static partial class InvokeAsyncModelFactory
{
    private static GeneratedPluginPackage EmitPackage(
        string ns,
        string packageName,
        string pluginId,
        InvokeAsyncCallShape shape,
        string bodyJson,
        IEnumerable<string> effects,
        IEnumerable<string> capabilities)
    {
        var json =
            "{" +
            "\"manifest\":{" +
            $"\"pluginId\":{Str(pluginId)}," +
            "\"contract\":\"AnonymousInvokeAsync\"," +
            "\"mode\":\"Auto\"," +
            $"\"effects\":[{JoinStrings(effects)}]," +
            "\"liveSettings\":[]," +
            "\"subscriptions\":[]," +
            $"\"requiredCapabilities\":[{JoinStrings(capabilities)}]," +
            "\"rpcEntrypoint\":\"Invoke\"}," +
            "\"entrypoints\":{\"shouldHandle\":\"Invoke\",\"handle\":\"Invoke\"}," +
            "\"module\":{" +
            $"\"id\":{Str(pluginId)},\"version\":\"1.0.0\",\"targetSandboxVersion\":\"1.0.0\"," +
            "\"capabilityRequests\":[]," +
            $"\"metadata\":{{\"kernel\":\"AnonymousInvokeAsync\",\"pluginId\":{Str(pluginId)}}}," +
            "\"functions\":[{" +
            "\"id\":\"Invoke\",\"visibility\":\"entrypoint\"," +
            $"\"parameters\":{shape.ParametersJson}," +
            $"\"returnType\":{shape.ReturnTypeJson}," +
            $"\"body\":{bodyJson}}}]}}}}";

        return new GeneratedPluginPackage(
            HintName(ns, packageName),
            BuildSource(ns, packageName, json),
            ns,
            packageName);
    }

    private static string BuildSource(string ns, string packageName, string json)
    {
        var builder = new System.Text.StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        if (!string.IsNullOrEmpty(ns))
        {
            builder.Append("namespace ").Append(ns).AppendLine(";");
            builder.AppendLine();
        }

        builder.Append("public static class ").AppendLine(packageName);
        builder.AppendLine("{");
        builder.Append("    public static ").Append(DotBoxDGenerationNames.TypeNames.GlobalPluginPackage).AppendLine(" Create()");
        builder.Append("        => ").Append(DotBoxDGenerationNames.TypeNames.GlobalPluginPackageJsonSerializer)
            .Append(".Import(\"").Append(json.Replace("\\", "\\\\").Replace("\"", "\\\"")).AppendLine("\");");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string HintName(string ns, string packageName)
        => string.IsNullOrWhiteSpace(ns)
            ? packageName + ".g.cs"
            : ns.Replace("@", string.Empty) + "." + packageName + ".g.cs";

    private static string JoinStrings(IEnumerable<string> values)
    {
        var parts = new List<string>();
        foreach (var value in values)
        {
            parts.Add(Str(value));
        }

        return string.Join(",", parts);
    }
}
